/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 119 "target.c"
void __globinit_target(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 209 "/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h"
typedef unsigned long size_t;
#line 152 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE;
#line 4
struct _IO_FILE;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
struct _IO_FILE;
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
#line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE;
#line 36
struct _IO_marker;
#line 36
struct _IO_marker;
#line 37
struct _IO_codecvt;
#line 37
struct _IO_codecvt;
#line 38
struct _IO_wide_data;
#line 38
struct _IO_wide_data;
#line 43 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
#line 49 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 20 "target.c"
enum anonymous {
    INIT = 0,
    IDLE = 1,
    RUN = 2,
    STOP = 3,
    EMERGENCY = -1
} ;
#line 21
struct comedi_t;
#line 21
struct comedi_t;
#line 22
enum tag_elev_lamp_type {
    BUTTON_CALL_UP = 0,
    BUTTON_CALL_DOWN = 1,
    BUTTON_COMMAND = 2
} ;
#line 24 "target.c"
typedef long clock_t___0;
#line 25 "target.c"
typedef struct comedi_t comedi_t;
#line 26 "target.c"
typedef enum anonymous elevState;
#line 27 "target.c"
typedef enum tag_elev_lamp_type elev_button_type_t;
#line 67 "target.c"
struct comedi_t {
   char stub ;
};
#line 372 "/opt/CROWN-CLI-ubuntu18.04/bin/../include/crown.h"
extern void __CrownInt(int *x , int cnt_sym_var , int ln , char *fname  , ...)  __attribute__((__crown_skip__)) ;
#line 138 "/usr/include/stdio.h"
extern FILE *stdout ;
#line 139
extern FILE *stderr ;
#line 213
extern int fclose(FILE *__stream ) ;
#line 218
extern int fflush(FILE *__stream ) ;
#line 246
extern FILE *fopen(char    * __restrict  __filename , char    * __restrict  __modes ) ;
#line 326
extern int fprintf(FILE * __restrict  __stream , char    * __restrict  __format  , ...) ;
#line 332
extern int printf(char    * __restrict  __format  , ...) ;
#line 617 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 7 "target.c"
int __iv__max_path  ;
#line 8 "target.c"
int __iv__nondet_call_counter  ;
#line 9 "target.c"
FILE *__iv__fp  ;
#line 35
void comedi_dio_read(comedi_t *comedi_dio_read__it_g , int port , int i , int *data ) ;
#line 38
int elev_get_button_signal(elev_button_type_t button , int floor ) ;
#line 56
int io_read_bit(int channel ) ;
#line 71 "target.c"
static int button_channel_matrix[4L][3L]  = { {        785,        -1,        789}, 
   {        784,        512,        788}, 
   {        513,        514,        787}, 
   {        -1,        515,        786}};
#line 72 "target.c"
int currentFloorLocation  =    -1;
#line 73 "target.c"
elevState currentState  =    (elevState )0;
#line 75 "target.c"
static comedi_t *it_g  =    (comedi_t *)((void *)0);
#line 77 "target.c"
int lastFloorAfterEmergency  =    -1;
#line 78 "target.c"
int motorDirection  =    0;
#line 79 "target.c"
int orderMatrix[3L][4L]  = { {        0,        0,        0,        0}, 
   {        0,        0,        0,        0}, 
   {        0,        0,        0,        0}};
#line 80 "target.c"
int previousMainFloor  =    -1;
#line 81 "target.c"
elevState previousState  =    (elevState )0;
#line 82 "target.c"
clock_t___0 previousTime  =    0L;
#line 85 "target.c"
int elev_get_button_signal(elev_button_type_t button , int floor ) 
{ 
  int return_value_io_read_bit ;
  int __retres4 ;

  {
  __CrownCheckSymbolic(4, "elev_get_button_signal");
  __CrownCall(3, 1);
  __CrownStore(2, (unsigned long )(& floor));
  __CrownStore(1, (unsigned long )(& button));
  {
  __CrownLoad(8, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownLoad(7, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(6, 22, 5, (long long )(floor >= 0), (double )(floor >= 0));
  __CrownApply1(5, 26, 5, (long long )(! (floor >= 0)), (double )(! (floor >= 0)));
#line 86
  if (! (floor >= 0)) {
    __CrownBranch(9, 2, 1, __LINE__, __FILE__);
    __CrownLoad(11, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownSetCallerCalleeName(12, "elev_get_button_signal", "exit");
#line 86
    exit(0);
    __CrownEnableSymbolic(14, "elev_get_button_signal");
    __CrownClearStack(13);
  } 
    #line 86
    else {
    __CrownBranch(10, 3, 0, __LINE__, __FILE__);

  }
  }
  {
  __CrownLoad(18, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownLoad(17, (unsigned long )0, 5, (long long )4, (double )4);
  __CrownApply2(16, 20, 5, (long long )(floor < 4), (double )(floor < 4));
  __CrownApply1(15, 26, 5, (long long )(! (floor < 4)), (double )(! (floor < 4)));
#line 87
  if (! (floor < 4)) {
    __CrownBranch(19, 5, 1, __LINE__, __FILE__);
    __CrownLoad(21, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownSetCallerCalleeName(22, "elev_get_button_signal", "exit");
#line 87
    exit(0);
    __CrownEnableSymbolic(24, "elev_get_button_signal");
    __CrownClearStack(23);
  } 
    #line 87
    else {
    __CrownBranch(20, 6, 0, __LINE__, __FILE__);

  }
  }
  {
  __CrownLoad(28, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownApply1(27, 27, 5, (long long )((int )button), (double )((int )button));
  __CrownLoad(26, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(25, 13, 5, (long long )((int )button == 0), (double )((int )button == 0));
#line 88
  if ((int )button == 0) {
    __CrownBranch(29, 8, 1, __LINE__, __FILE__);

  } 
    #line 88
    else {
    __CrownBranch(30, 9, 0, __LINE__, __FILE__);
    {
    __CrownLoad(34, (unsigned long )(& button), 5, (long long )button, (double )button);
    __CrownApply1(33, 27, 5, (long long )((int )button), (double )((int )button));
    __CrownLoad(32, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(31, 13, 5, (long long )((int )button == 1), (double )((int )button == 1));
#line 88
    if ((int )button == 1) {
      __CrownBranch(35, 10, 1, __LINE__, __FILE__);

    } 
      #line 88
      else {
      __CrownBranch(36, 11, 0, __LINE__, __FILE__);
      {
      __CrownLoad(40, (unsigned long )(& button), 5, (long long )button, (double )button);
      __CrownApply1(39, 27, 5, (long long )((int )button), (double )((int )button));
      __CrownLoad(38, (unsigned long )0, 5, (long long )2, (double )2);
      __CrownApply2(37, 13, 5, (long long )((int )button == 2), (double )((int )button == 2));
#line 88
      if ((int )button == 2) {
        __CrownBranch(41, 12, 1, __LINE__, __FILE__);

      } 
        #line 88
        else {
        __CrownBranch(42, 13, 0, __LINE__, __FILE__);
        __CrownLoad(43, (unsigned long )0, 5, (long long )0, (double )0);
        __CrownSetCallerCalleeName(44, "elev_get_button_signal", "exit");
#line 88
        exit(0);
        __CrownEnableSymbolic(46, "elev_get_button_signal");
        __CrownClearStack(45);
      }
      }
    }
    }
  }
  }
  {
  __CrownLoad(50, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(49, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownApply1(48, 27, 7, (long long )((long )button), (double )((long )button));
  __CrownApply2(47, 16, 5, (long long )(0L > (long )button), (double )(0L > (long )button));
#line 90
  if (0L > (long )button) {
    __CrownBranch(51, 15, 1, __LINE__, __FILE__);
    __CrownLoad(53, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(54, (unsigned long )(& __iv__max_path));
#line 90
    __iv__max_path = 10000;
  } 
    #line 90
    else {
    __CrownBranch(52, 16, 0, __LINE__, __FILE__);
    {
    __CrownLoad(58, (unsigned long )(& button), 5, (long long )button, (double )button);
    __CrownApply1(57, 27, 7, (long long )((long )button), (double )((long )button));
    __CrownLoad(56, (unsigned long )0, 7, (long long )3L, (double )3L);
    __CrownApply2(55, 22, 5, (long long )((long )button >= 3L), (double )((long )button >= 3L));
#line 90
    if ((long )button >= 3L) {
      __CrownBranch(59, 17, 1, __LINE__, __FILE__);
      __CrownLoad(61, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(62, (unsigned long )(& __iv__max_path));
#line 90
      __iv__max_path = 10000;
    } 
      #line 90
      else {
      __CrownBranch(60, 18, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  {
  __CrownLoad(66, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(65, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownApply1(64, 28, 7, (long long )((long )floor), (double )((long )floor));
  __CrownApply2(63, 16, 5, (long long )(0L > (long )floor), (double )(0L > (long )floor));
#line 91
  if (0L > (long )floor) {
    __CrownBranch(67, 20, 1, __LINE__, __FILE__);
    __CrownLoad(69, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(70, (unsigned long )(& __iv__max_path));
#line 91
    __iv__max_path = 10000;
  } 
    #line 91
    else {
    __CrownBranch(68, 21, 0, __LINE__, __FILE__);
    {
    __CrownLoad(74, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
    __CrownApply1(73, 28, 7, (long long )((long )floor), (double )((long )floor));
    __CrownLoad(72, (unsigned long )0, 7, (long long )4L, (double )4L);
    __CrownApply2(71, 22, 5, (long long )((long )floor >= 4L), (double )((long )floor >= 4L));
#line 91
    if ((long )floor >= 4L) {
      __CrownBranch(75, 22, 1, __LINE__, __FILE__);
      __CrownLoad(77, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(78, (unsigned long )(& __iv__max_path));
#line 91
      __iv__max_path = 10000;
    } 
      #line 91
      else {
      __CrownBranch(76, 23, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  {
  __CrownLoad(82, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(81, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownApply1(80, 28, 7, (long long )((long )floor), (double )((long )floor));
  __CrownApply2(79, 16, 5, (long long )(0L > (long )floor), (double )(0L > (long )floor));
#line 92
  if (0L > (long )floor) {
    __CrownBranch(83, 25, 1, __LINE__, __FILE__);
    __CrownLoad(85, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(86, (unsigned long )(& __iv__max_path));
#line 92
    __iv__max_path = 10000;
  } 
    #line 92
    else {
    __CrownBranch(84, 26, 0, __LINE__, __FILE__);
    {
    __CrownLoad(90, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
    __CrownApply1(89, 28, 7, (long long )((long )floor), (double )((long )floor));
    __CrownLoad(88, (unsigned long )0, 7, (long long )4L, (double )4L);
    __CrownApply2(87, 22, 5, (long long )((long )floor >= 4L), (double )((long )floor >= 4L));
#line 92
    if ((long )floor >= 4L) {
      __CrownBranch(91, 27, 1, __LINE__, __FILE__);
      __CrownLoad(93, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(94, (unsigned long )(& __iv__max_path));
#line 92
      __iv__max_path = 10000;
    } 
      #line 92
      else {
      __CrownBranch(92, 28, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  __CrownLoad(95, (unsigned long )(& button_channel_matrix[(long )floor][(long )button]),
              5, (long long )button_channel_matrix[(long )floor][(long )button], (double )button_channel_matrix[(long )floor][(long )button]);
  __CrownSetCallerCalleeName(96, "elev_get_button_signal", "io_read_bit");
#line 93
  return_value_io_read_bit = io_read_bit(button_channel_matrix[(long )floor][(long )button]);
  __CrownEnableSymbolic(99, "elev_get_button_signal");
  __CrownHandleReturn(98, 5, (long long )return_value_io_read_bit, (double )return_value_io_read_bit);
  __CrownStore(97, (unsigned long )(& return_value_io_read_bit));
  __CrownLoad(102, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(101, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(100, 0, 5, (long long )(__iv__max_path + 1), (double )(__iv__max_path + 1));
  __CrownStore(103, (unsigned long )(& __iv__max_path));
#line 94
  __iv__max_path ++;
  {
  __CrownLoad(106, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(105, (unsigned long )0, 5, (long long )10000, (double )10000);
  __CrownApply2(104, 22, 5, (long long )(__iv__max_path >= 10000), (double )(__iv__max_path >= 10000));
#line 95
  if (__iv__max_path >= 10000) {
    __CrownBranch(107, 31, 1, __LINE__, __FILE__);
    __CrownLoad(109, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownStore(110, (unsigned long )(& __retres4));
#line 95
    __retres4 = 0;
#line 95
    goto return_label;
  } 
    #line 95
    else {
    __CrownBranch(108, 33, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(111, (unsigned long )0, 6, (long long )((char    * __restrict  )"Node_5_283:%d\n"),
              8);
  __CrownLoad(114, (unsigned long )(& return_value_io_read_bit), 5, (long long )return_value_io_read_bit,
              (double )return_value_io_read_bit);
  __CrownLoad(113, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(112, 13, 5, (long long )(return_value_io_read_bit == 0), (double )(return_value_io_read_bit == 0));
  __CrownSetCallerCalleeName(115, "elev_get_button_signal", "printf");
#line 96
  printf((char    * __restrict  )"Node_5_283:%d\n", return_value_io_read_bit == 0);
  __CrownEnableSymbolic(117, "elev_get_button_signal");
  __CrownClearStack(116);
  __CrownLoad(118, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(119, "elev_get_button_signal", "fflush");
#line 96
  fflush(stdout);
  __CrownEnableSymbolic(121, "elev_get_button_signal");
  __CrownClearStack(120);
  {
  __CrownLoad(124, (unsigned long )(& return_value_io_read_bit), 5, (long long )return_value_io_read_bit,
              (double )return_value_io_read_bit);
  __CrownLoad(123, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownApply2(122, 13, 5, (long long )(return_value_io_read_bit == 0), (double )(return_value_io_read_bit == 0));
#line 97
  if (return_value_io_read_bit == 0) {
    __CrownBranch(125, 36, 1, __LINE__, __FILE__);
#line 97
    goto Node_5_289;
  } 
    #line 97
    else {
    __CrownBranch(126, 37, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(127, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownStore(128, (unsigned long )(& __retres4));
#line 98
  __retres4 = 1;
#line 98
  goto return_label;
  Node_5_289: ;
  __CrownLoad(129, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(130, (unsigned long )(& __retres4));
#line 100
  __retres4 = 0;
  return_label: /* CIL Label */ 
  {
  __CrownLoad(131, (unsigned long )(& __retres4), 5, (long long )__retres4, (double )__retres4);
  __CrownReturn(132);
#line 85
  return (__retres4);
  }
}
}
#line 102 "target.c"
int io_read_bit(int channel ) 
{ 
  unsigned int data ;
  int __retres3 ;

  {
  __CrownCheckSymbolic(135, "io_read_bit");
  __CrownCall(134, 2);
  __CrownStore(133, (unsigned long )(& channel));
  __CrownLoad(136, (unsigned long )0, 4, (long long )0U, (double )0U);
  __CrownStore(137, (unsigned long )(& data));
#line 104
  data = 0U;
  __CrownLoad(138, (unsigned long )(& it_g), 6, (long long )it_g, 8);
  __CrownLoad(141, (unsigned long )(& channel), 5, (long long )channel, (double )channel);
  __CrownLoad(140, (unsigned long )0, 5, (long long )8, (double )8);
  __CrownApply2(139, 9, 5, (long long )(channel >> 8), (double )(channel >> 8));
  __CrownLoad(144, (unsigned long )(& channel), 5, (long long )channel, (double )channel);
  __CrownLoad(143, (unsigned long )0, 5, (long long )255, (double )255);
  __CrownApply2(142, 10, 5, (long long )(channel & 255), (double )(channel & 255));
  __CrownLoad(146, (unsigned long )0, 6, (long long )(& data), 8);
  __CrownApply1(145, 27, 6, (long long )((int *)(& data)), 8);
  __CrownSetCallerCalleeName(147, "io_read_bit", "comedi_dio_read");
#line 105
  comedi_dio_read(it_g, channel >> 8, channel & 255, (int *)(& data));
  __CrownEnableSymbolic(149, "io_read_bit");
  __CrownClearStack(148);
  __CrownLoad(151, (unsigned long )(& data), 4, (long long )data, (double )data);
  __CrownApply1(150, 27, 5, (long long )((int )data), (double )((int )data));
  __CrownStore(152, (unsigned long )(& __retres3));
#line 106
  __retres3 = (int )data;
  {
  __CrownLoad(153, (unsigned long )(& __retres3), 5, (long long )__retres3, (double )__retres3);
  __CrownReturn(154);
#line 102
  return (__retres3);
  }
}
}
#line 112
void comedi_dio_read(comedi_t *comedi_dio_read__it_g , int port , int i , int *data ) ;
#line 112 "target.c"
static int cnt_symbolic_var  =    1;
#line 108 "target.c"
void comedi_dio_read(comedi_t *comedi_dio_read__it_g , int port , int i , int *data ) 
{ 
  int read ;
  int return_value___VERIFIER_nondet_signed_int ;

  {
  __CrownCheckSymbolic(160, "comedi_dio_read");
  __CrownCall(159, 3);
  __CrownStore(158, (unsigned long )(& data));
  __CrownStore(157, (unsigned long )(& i));
  __CrownStore(156, (unsigned long )(& port));
  __CrownStore(155, (unsigned long )(& comedi_dio_read__it_g));
  __CrownLoad(163, (unsigned long )(& __iv__nondet_call_counter), 5, (long long )__iv__nondet_call_counter,
              (double )__iv__nondet_call_counter);
  __CrownLoad(162, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(161, 0, 5, (long long )(__iv__nondet_call_counter + 1), (double )(__iv__nondet_call_counter + 1));
  __CrownStore(164, (unsigned long )(& __iv__nondet_call_counter));
#line 111
  __iv__nondet_call_counter ++;
#line 112
  __CrownInt(& return_value___VERIFIER_nondet_signed_int, cnt_symbolic_var, 112, (char *)"target.c",
             "return_value___VERIFIER_nondet_signed_int");
  __CrownLoad(167, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
              (double )cnt_symbolic_var);
  __CrownLoad(166, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(165, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
  __CrownStore(168, (unsigned long )(& cnt_symbolic_var));
#line 112
  cnt_symbolic_var ++;
  __CrownLoad(169, (unsigned long )0, 6, (long long )((char    * __restrict  )"__iv__nondet_input_elev_get_button_signal_%d=%d\n"),
              8);
  __CrownLoad(170, (unsigned long )(& __iv__nondet_call_counter), 5, (long long )__iv__nondet_call_counter,
              (double )__iv__nondet_call_counter);
  __CrownLoad(171, (unsigned long )(& return_value___VERIFIER_nondet_signed_int),
              5, (long long )return_value___VERIFIER_nondet_signed_int, (double )return_value___VERIFIER_nondet_signed_int);
  __CrownSetCallerCalleeName(172, "comedi_dio_read", "printf");
#line 113
  printf((char    * __restrict  )"__iv__nondet_input_elev_get_button_signal_%d=%d\n",
         __iv__nondet_call_counter, return_value___VERIFIER_nondet_signed_int);
  __CrownEnableSymbolic(174, "comedi_dio_read");
  __CrownClearStack(173);
  __CrownLoad(175, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(176, "comedi_dio_read", "fflush");
#line 113
  fflush(stdout);
  __CrownEnableSymbolic(178, "comedi_dio_read");
  __CrownClearStack(177);
  __CrownLoad(179, (unsigned long )(& return_value___VERIFIER_nondet_signed_int),
              5, (long long )return_value___VERIFIER_nondet_signed_int, (double )return_value___VERIFIER_nondet_signed_int);
  __CrownStore(180, (unsigned long )(& read));
#line 114
  read = return_value___VERIFIER_nondet_signed_int;
  {
  __CrownLoad(183, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownLoad(182, (unsigned long )(& read), 5, (long long )read, (double )read);
  __CrownApply2(181, 18, 5, (long long )(0 <= read), (double )(0 <= read));
#line 115
  if (0 <= read) {
    __CrownBranch(184, 48, 1, __LINE__, __FILE__);
    {
    __CrownLoad(188, (unsigned long )(& read), 5, (long long )read, (double )read);
    __CrownLoad(187, (unsigned long )0, 5, (long long )1, (double )1);
    __CrownApply2(186, 18, 5, (long long )(read <= 1), (double )(read <= 1));
#line 115
    if (read <= 1) {
      __CrownBranch(189, 49, 1, __LINE__, __FILE__);

    } 
      #line 115
      else {
      __CrownBranch(190, 50, 0, __LINE__, __FILE__);
      __CrownLoad(191, (unsigned long )0, 5, (long long )0, (double )0);
      __CrownSetCallerCalleeName(192, "comedi_dio_read", "exit");
#line 115
      exit(0);
      __CrownEnableSymbolic(194, "comedi_dio_read");
      __CrownClearStack(193);
    }
    }
  } 
    #line 115
    else {
    __CrownBranch(185, 51, 0, __LINE__, __FILE__);
    __CrownLoad(195, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownSetCallerCalleeName(196, "comedi_dio_read", "exit");
#line 115
    exit(0);
    __CrownEnableSymbolic(198, "comedi_dio_read");
    __CrownClearStack(197);
  }
  }
  __CrownLoad(199, (unsigned long )(& read), 5, (long long )read, (double )read);
  __CrownStore(200, (unsigned long )data);
#line 116
  *data = read;

  {
  __CrownReturn(201);
#line 108
  return;
  }
}
}
#line 124
int main(void) ;
#line 124 "target.c"
static int cnt_symbolic_var___0  =    1;
#line 125
int main(void) ;
#line 125 "target.c"
static int cnt_symbolic_var___1  =    1;
#line 119 "target.c"
int main(void) 
{ 
  elev_button_type_t button ;
  int floor ;
  int __iv__return_expr_elev_get_button_signal ;
  FILE *f ;
  FILE *tmp ;
  int __retres6 ;

  {
  __globinit_target();
  __CrownCheckSymbolic(204, "main");
  __CrownCall(203, 4);
  __CrownClearStack(202);
  __CrownLoad(205, (unsigned long )0, 6, (long long )((char    * __restrict  )"input:\n"),
              8);
  __CrownSetCallerCalleeName(206, "main", "printf");
#line 123
  printf((char    * __restrict  )"input:\n");
  __CrownEnableSymbolic(208, "main");
  __CrownClearStack(207);
  __CrownLoad(209, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(210, "main", "fflush");
#line 123
  fflush(stdout);
  __CrownEnableSymbolic(212, "main");
  __CrownClearStack(211);
#line 124
  __CrownInt((int *)(& button), cnt_symbolic_var___0, 124, (char *)"target.c", "button");
  __CrownLoad(215, (unsigned long )(& cnt_symbolic_var___0), 5, (long long )cnt_symbolic_var___0,
              (double )cnt_symbolic_var___0);
  __CrownLoad(214, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(213, 0, 5, (long long )(cnt_symbolic_var___0 + 1), (double )(cnt_symbolic_var___0 + 1));
  __CrownStore(216, (unsigned long )(& cnt_symbolic_var___0));
#line 124
  cnt_symbolic_var___0 ++;
  __CrownLoad(217, (unsigned long )0, 6, (long long )((char    * __restrict  )"button=%d\n"),
              8);
  __CrownLoad(219, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownApply1(218, 27, 4, (long long )((unsigned int )button), (double )((unsigned int )button));
  __CrownSetCallerCalleeName(220, "main", "printf");
#line 124
  printf((char    * __restrict  )"button=%d\n", (unsigned int )button);
  __CrownEnableSymbolic(222, "main");
  __CrownClearStack(221);
  __CrownLoad(223, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(224, "main", "fflush");
#line 124
  fflush(stdout);
  __CrownEnableSymbolic(226, "main");
  __CrownClearStack(225);
#line 125
  __CrownInt(& floor, cnt_symbolic_var___1, 125, (char *)"target.c", "floor");
  __CrownLoad(229, (unsigned long )(& cnt_symbolic_var___1), 5, (long long )cnt_symbolic_var___1,
              (double )cnt_symbolic_var___1);
  __CrownLoad(228, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(227, 0, 5, (long long )(cnt_symbolic_var___1 + 1), (double )(cnt_symbolic_var___1 + 1));
  __CrownStore(230, (unsigned long )(& cnt_symbolic_var___1));
#line 125
  cnt_symbolic_var___1 ++;
  __CrownLoad(231, (unsigned long )0, 6, (long long )((char    * __restrict  )"floor=%d\n"),
              8);
  __CrownLoad(232, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownSetCallerCalleeName(233, "main", "printf");
#line 125
  printf((char    * __restrict  )"floor=%d\n", floor);
  __CrownEnableSymbolic(235, "main");
  __CrownClearStack(234);
  __CrownLoad(236, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(237, "main", "fflush");
#line 125
  fflush(stdout);
  __CrownEnableSymbolic(239, "main");
  __CrownClearStack(238);
  __CrownLoad(240, (unsigned long )0, 6, (long long )((char    * __restrict  )"path:\n"),
              8);
  __CrownSetCallerCalleeName(241, "main", "printf");
#line 126
  printf((char    * __restrict  )"path:\n");
  __CrownEnableSymbolic(243, "main");
  __CrownClearStack(242);
  __CrownLoad(244, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(245, "main", "fflush");
#line 126
  fflush(stdout);
  __CrownEnableSymbolic(247, "main");
  __CrownClearStack(246);
  __CrownLoad(248, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownLoad(249, (unsigned long )(& floor), 5, (long long )floor, (double )floor);
  __CrownSetCallerCalleeName(250, "main", "elev_get_button_signal");
#line 127
  __iv__return_expr_elev_get_button_signal = elev_get_button_signal(button, floor);
  __CrownEnableSymbolic(253, "main");
  __CrownHandleReturn(252, 5, (long long )__iv__return_expr_elev_get_button_signal,
                      (double )__iv__return_expr_elev_get_button_signal);
  __CrownStore(251, (unsigned long )(& __iv__return_expr_elev_get_button_signal));
#line 128
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(257, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
                (double )__iv__max_path);
    __CrownLoad(256, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownApply2(255, 20, 5, (long long )(__iv__max_path < 10000), (double )(__iv__max_path < 10000));
    __CrownApply1(254, 26, 5, (long long )(! (__iv__max_path < 10000)), (double )(! (__iv__max_path < 10000)));
#line 128
    if (! (__iv__max_path < 10000)) {
      __CrownBranch(258, 60, 1, __LINE__, __FILE__);
      __CrownLoad(261, (unsigned long )(& stderr), 6, (long long )stderr, 8);
      __CrownApply1(260, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
      __CrownLoad(262, (unsigned long )0, 6, (long long )((char    * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n"),
                  8);
      __CrownLoad(263, (unsigned long )0, 6, (long long )"__iv__max_path < 10000",
                  8);
      __CrownLoad(264, (unsigned long )0, 5, (long long )128, (double )128);
      __CrownLoad(265, (unsigned long )0, 6, (long long )"main", 8);
      __CrownLoad(266, (unsigned long )0, 6, (long long )"target.c", 8);
      __CrownSetCallerCalleeName(267, "main", "fprintf");
#line 128
      fprintf((FILE * __restrict  )stderr, (char    * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n",
              "__iv__max_path < 10000", 128, "main", "target.c");
      __CrownEnableSymbolic(269, "main");
      __CrownClearStack(268);
      __CrownLoad(270, (unsigned long )0, 6, (long long )((char    * __restrict  )"__SYM_assume_violated"),
                  8);
      __CrownLoad(271, (unsigned long )0, 6, (long long )((char    * __restrict  )"w"),
                  8);
      __CrownSetCallerCalleeName(272, "main", "fopen");
#line 128
      tmp = fopen((char    * __restrict  )"__SYM_assume_violated", (char    * __restrict  )"w");
      __CrownEnableSymbolic(275, "main");
      __CrownHandleReturn(274, 6, (long long )tmp, 8);
      __CrownStore(273, (unsigned long )(& tmp));
      __CrownLoad(276, (unsigned long )(& tmp), 6, (long long )tmp, 8);
      __CrownStore(277, (unsigned long )(& f));
#line 128
      f = tmp;
      {
      __CrownLoad(279, (unsigned long )(& f), 6, (long long )f, 8);
      __CrownApply1(278, 26, 5, (long long )(! f), (double )(! f));
#line 128
      if (! f) {
        __CrownBranch(280, 62, 1, __LINE__, __FILE__);
        __CrownLoad(283, (unsigned long )(& stderr), 6, (long long )stderr, 8);
        __CrownApply1(282, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
        __CrownLoad(284, (unsigned long )0, 6, (long long )((char    * __restrict  )"### %s file cannot be created ###\n"),
                    8);
        __CrownLoad(285, (unsigned long )0, 6, (long long )"__SYM_assume_violated",
                    8);
        __CrownSetCallerCalleeName(286, "main", "fprintf");
#line 128
        fprintf((FILE * __restrict  )stderr, (char    * __restrict  )"### %s file cannot be created ###\n",
                "__SYM_assume_violated");
        __CrownEnableSymbolic(288, "main");
        __CrownClearStack(287);
      } 
        #line 128
        else {
        __CrownBranch(281, 63, 0, __LINE__, __FILE__);
        __CrownLoad(289, (unsigned long )(& f), 6, (long long )f, 8);
        __CrownSetCallerCalleeName(290, "main", "fclose");
#line 128
        fclose(f);
        __CrownEnableSymbolic(292, "main");
        __CrownClearStack(291);
      }
      }
      __CrownLoad(293, (unsigned long )0, 5, (long long )1, (double )1);
      __CrownSetCallerCalleeName(294, "main", "exit");
#line 128
      exit(1);
      __CrownEnableSymbolic(296, "main");
      __CrownClearStack(295);
    } 
      #line 128
      else {
      __CrownBranch(259, 65, 0, __LINE__, __FILE__);

    }
    }
#line 128
    goto while_break;
  }
  while_break: /* CIL Label */ 
  __CrownLoad(297, (unsigned long )0, 6, (long long )((char    * __restrict  )"output:\n"),
              8);
  __CrownSetCallerCalleeName(298, "main", "printf");
#line 129
  printf((char    * __restrict  )"output:\n");
  __CrownEnableSymbolic(300, "main");
  __CrownClearStack(299);
  __CrownLoad(301, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(302, "main", "fflush");
#line 129
  fflush(stdout);
  __CrownEnableSymbolic(304, "main");
  __CrownClearStack(303);
  __CrownLoad(305, (unsigned long )0, 6, (long long )((char    * __restrict  )"__iv__return_expr_elev_get_button_signal=%d\n"),
              8);
  __CrownLoad(306, (unsigned long )(& __iv__return_expr_elev_get_button_signal), 5,
              (long long )__iv__return_expr_elev_get_button_signal, (double )__iv__return_expr_elev_get_button_signal);
  __CrownSetCallerCalleeName(307, "main", "printf");
#line 130
  printf((char    * __restrict  )"__iv__return_expr_elev_get_button_signal=%d\n",
         __iv__return_expr_elev_get_button_signal);
  __CrownEnableSymbolic(309, "main");
  __CrownClearStack(308);
  __CrownLoad(310, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(311, "main", "fflush");
#line 130
  fflush(stdout);
  __CrownEnableSymbolic(313, "main");
  __CrownClearStack(312);
  __CrownLoad(314, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(315, (unsigned long )(& __retres6));
#line 131
  __retres6 = 0;
  __CrownLoad(316, (unsigned long )(& __retres6), 5, (long long )__retres6, (double )__retres6);
  __CrownReturn(317);
#line 119
  return (__retres6);
}
}
void __globinit_target(void) 
{ 


  {
  __CrownInit(318);
}
}
