int __iv__current_func_call;
#include <assert.h>
#include <stdlib.h>
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
signed int FlAcpiConfigureFloppy(signed int DisketteExtension, signed int FdcInfo);
signed int FlCheckFormatParameters(signed int DisketteExtension, signed int FormatParameters);
signed int FlFdcDeviceIo(signed int DeviceObject, signed int Ioctl, signed int Data);
signed int FlQueueIrpToThread(signed int Irp, signed int DisketteExtension);
signed int FloppyCreateClose(signed int DeviceObject, signed int Irp);
signed int FloppyDeviceControl(signed int DeviceObject, signed int Irp);
signed int FloppyPnp(signed int DeviceObject, signed int Irp);
signed int FloppyPnpComplete(signed int DeviceObject, signed int Irp, signed int Context);
void FloppyProcessQueuedRequests(signed int DisketteExtension);
signed int FloppyQueueRequest(signed int DisketteExtension, signed int Irp);
signed int FloppyStartDevice(signed int DeviceObject, signed int Irp);
signed int IoBuildDeviceIoControlRequest(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock);
signed int IoDeleteSymbolicLink(signed int SymbolicLinkName);
signed int IoQueryDeviceDescription(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context);
signed int IoRegisterDeviceInterface(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName);
signed int IoSetDeviceInterfaceState(signed int SymbolicLinkName, signed int Enable);
signed int IofCallDriver(signed int DeviceObject, signed int Irp);
void IofCompleteRequest(signed int Irp, signed int PriorityBoost);
signed int KeSetEvent(signed int Event, signed int Increment, signed int Wait);
signed int KeWaitForSingleObject(signed int Object, signed int WaitReason, signed int WaitMode, signed int Alertable, signed int Timeout);
signed int ObReferenceObjectByHandle(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation);
signed int PsCreateSystemThread(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext);
signed int ZwClose(signed int Handle);
void _BLAST_init(void);
void errorFn(void);
void reach_error();
void stubMoreProcessingRequired(void);
void stub_driver_init(void);
signed int DC;
signed int DiskController;
signed int Executive;
signed int FlConfigCallBack;
signed int FloppyDiskPeripheral;
signed int FloppyThread;
signed int IPC;
signed int KernelMode;
signed int MOUNTDEV_MOUNTED_DEVICE_GUID;
signed int MPR1;
signed int MPR3;
signed int MaximumInterfaceType;
signed int NP;
signed int PagingMutex=0;
signed int PagingReferenceCount=0;
signed int SKIP1;
signed int SKIP2;
signed int Suspended;
signed int UNLOADED;
signed int compRegistered;
signed int customIrp;
signed int lowerDriverReturn;
signed int myStatus;
signed int pended;
signed int s;
signed int setEventCalled;
extern signed int __VERIFIER_nondet_signed_int();
int main() {
	signed int status;
	signed int irp;
	irp = __VERIFIER_nondet_signed_int();
	signed int pirp;
	signed int pirp__IoStatus__Status;
	signed int irp_choice;
	irp_choice = __VERIFIER_nondet_signed_int();
	signed int devobj;
	devobj = __VERIFIER_nondet_signed_int();
	FloppyThread = 0;
	KernelMode = 0;
	Suspended = 0;
	Executive = 0;
	DiskController = 0;
	FloppyDiskPeripheral = 0;
	FlConfigCallBack = 0;
	MaximumInterfaceType = 0;
	MOUNTDEV_MOUNTED_DEVICE_GUID = 0;
	myStatus = 0;
	s = 0;
	UNLOADED = 0;
	NP = 0;
	DC = 0;
	SKIP1 = 0;
	SKIP2 = 0;
	MPR1 = 0;
	MPR3 = 0;
	IPC = 0;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	status = 0;
	pirp = irp;
__iv__current_func_call = 3;	_BLAST_init();
	if (!((status >= 0))) goto Node_0_129;
	s = NP;
	customIrp = 0;
	setEventCalled = customIrp;
	lowerDriverReturn = setEventCalled;
	compRegistered = lowerDriverReturn;
	pended = compRegistered;
	pirp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((irp_choice == 0))) goto Node_0_55;
	pirp__IoStatus__Status = -1073741637;
	myStatus = -1073741637;
	Node_0_55:;
__iv__current_func_call = 4;	stub_driver_init();
	if (!((status < 0))) goto Node_0_70;
	return -1;
	Node_0_70:;
	signed int tmp_ndt_1;
	tmp_ndt_1 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_1 == 0))) goto Node_0_76;
	goto Node_0_93;
	Node_0_76:;
	signed int tmp_ndt_2;
	tmp_ndt_2 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_2 == 1))) goto Node_0_81;
	goto Node_0_95;
	Node_0_81:;
	signed int tmp_ndt_3;
	tmp_ndt_3 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_3 == 2))) goto Node_0_86;
	goto Node_0_97;
	Node_0_86:;
	signed int tmp_ndt_4;
	tmp_ndt_4 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_4 == 3))) goto Node_0_91;
	goto Node_0_99;
	Node_0_91:;
	goto Node_0_101;
	Node_0_93:;
__iv__current_func_call = 9;	status = FloppyCreateClose(devobj, pirp);
	goto Node_0_119;
	Node_0_95:;
__iv__current_func_call = 10;	status = FloppyCreateClose(devobj, pirp);
	goto Node_0_119;
	Node_0_97:;
__iv__current_func_call = 11;	status = FloppyDeviceControl(devobj, pirp);
	goto Node_0_119;
	Node_0_99:;
__iv__current_func_call = 12;	status = FloppyPnp(devobj, pirp);
	goto Node_0_119;
	Node_0_101:;
	return -1;
	Node_0_119:;
	Node_0_129:;
	if (!((pended == 1))) goto Node_0_137;
	if (!((s == NP))) goto Node_0_134;
	s = NP;
	goto Node_0_135;
	Node_0_134:;
	goto Node_0_137;
	Node_0_135:;
	goto Node_0_176;
	Node_0_137:;
	if (!((pended == 1))) goto Node_0_144;
	if (!((s == MPR3))) goto Node_0_141;
	s = MPR3;
	goto Node_0_142;
	Node_0_141:;
	goto Node_0_144;
	Node_0_142:;
	goto Node_0_175;
	Node_0_144:;
	if (!((s != UNLOADED))) goto Node_0_174;
	if (!((status != -1))) goto Node_0_173;
	if (!((s != SKIP2))) goto Node_0_157;
	if (!((s != IPC))) goto Node_0_154;
	if (!((s != DC))) goto Node_0_151;
__iv__current_func_call = 13;	errorFn();
	goto Node_0_152;
	Node_0_151:;
	goto Node_0_157;
	Node_0_152:;
	goto Node_0_155;
	Node_0_154:;
	goto Node_0_157;
	Node_0_155:;
	goto Node_0_172;
	Node_0_157:;
	if (!((pended == 1))) goto Node_0_162;
	if (!((status != 259))) goto Node_0_160;
__iv__current_func_call = 14;	errorFn();
	Node_0_160:;
	goto Node_0_171;
	Node_0_162:;
	if (!((s == DC))) goto Node_0_167;
	if (!((status == 259))) goto Node_0_165;
__iv__current_func_call = 15;	errorFn();
	Node_0_165:;
	goto Node_0_170;
	Node_0_167:;
	if (!((status != lowerDriverReturn))) goto Node_0_169;
__iv__current_func_call = 16;	errorFn();
	Node_0_169:;
	Node_0_170:;
	Node_0_171:;
	Node_0_172:;
	Node_0_173:;
	Node_0_174:;
	Node_0_175:;
	Node_0_176:;
	status = 0;
	return status;
}
signed int FloppyDeviceControl(signed int DeviceObject, signed int Irp) {
	signed int disketteExtension__HoldNewRequests;
	disketteExtension__HoldNewRequests = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__IsRemoved;
	disketteExtension__IsRemoved = __VERIFIER_nondet_signed_int();
	signed int Irp__IoStatus__Information;
	signed int disketteExtension__IsStarted;
	disketteExtension__IsStarted = __VERIFIER_nondet_signed_int();
	signed int Irp__CurrentLocation;
	Irp__CurrentLocation = __VERIFIER_nondet_signed_int();
	signed int Irp__Tail__Overlay__CurrentStackLocation;
	Irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__TargetObject;
	disketteExtension__TargetObject = __VERIFIER_nondet_signed_int();
	signed int irpSp__Parameters__DeviceIoControl__OutputBufferLength;
	irpSp__Parameters__DeviceIoControl__OutputBufferLength = __VERIFIER_nondet_signed_int();
	signed int sizeof__MOUNTDEV_NAME;
	sizeof__MOUNTDEV_NAME = __VERIFIER_nondet_signed_int();
	signed int Irp__AssociatedIrp__SystemBuffer;
	Irp__AssociatedIrp__SystemBuffer = __VERIFIER_nondet_signed_int();
	signed int mountName__NameLength;
	signed int disketteExtension__DeviceName__Length;
	disketteExtension__DeviceName__Length = __VERIFIER_nondet_signed_int();
	signed int sizeof__USHORT;
	sizeof__USHORT = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__InterfaceString__Buffer;
	disketteExtension__InterfaceString__Buffer = __VERIFIER_nondet_signed_int();
	signed int uniqueId__UniqueIdLength;
	signed int disketteExtension__InterfaceString__Length;
	disketteExtension__InterfaceString__Length = __VERIFIER_nondet_signed_int();
	signed int sizeof__MOUNTDEV_UNIQUE_ID;
	sizeof__MOUNTDEV_UNIQUE_ID = __VERIFIER_nondet_signed_int();
	signed int irpSp__Parameters__DeviceIoControl__InputBufferLength;
	irpSp__Parameters__DeviceIoControl__InputBufferLength = __VERIFIER_nondet_signed_int();
	signed int sizeof__FORMAT_PARAMETERS;
	sizeof__FORMAT_PARAMETERS = __VERIFIER_nondet_signed_int();
	signed int irpSp__Parameters__DeviceIoControl__IoControlCode___1;
	irpSp__Parameters__DeviceIoControl__IoControlCode___1 = __VERIFIER_nondet_signed_int();
	signed int sizeof__FORMAT_EX_PARAMETERS;
	sizeof__FORMAT_EX_PARAMETERS = __VERIFIER_nondet_signed_int();
	signed int formatExParameters__FormatGapLength;
	formatExParameters__FormatGapLength = __VERIFIER_nondet_signed_int();
	signed int formatExParameters__SectorsPerTrack;
	formatExParameters__SectorsPerTrack = __VERIFIER_nondet_signed_int();
	signed int sizeof__DISK_GEOMETRY;
	sizeof__DISK_GEOMETRY = __VERIFIER_nondet_signed_int();
	signed int Irp__IoStatus__Status___0;
	signed int disketteExtension;
	disketteExtension = __VERIFIER_nondet_signed_int();
	signed int ntStatus;
	signed int outputBufferLength;
	signed int lowestDriveMediaType;
	lowestDriveMediaType = __VERIFIER_nondet_signed_int();
	signed int highestDriveMediaType;
	highestDriveMediaType = __VERIFIER_nondet_signed_int();
	signed int formatExParametersSize;
	formatExParametersSize = __VERIFIER_nondet_signed_int();
	signed int formatExParameters;
	signed int tmp;
	signed int mountName;
	signed int uniqueId;
	signed int tmp___0;
	signed int __cil_tmp41;
	__cil_tmp41 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp44;
	__cil_tmp44 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp45;
	__cil_tmp45 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp50;
	__cil_tmp50 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp55;
	__cil_tmp55 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp60;
	__cil_tmp60 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp65;
	__cil_tmp65 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp66;
	__cil_tmp66 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp69;
	__cil_tmp69 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp72;
	__cil_tmp72 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp75;
	__cil_tmp75 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp78;
	__cil_tmp78 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp81;
	__cil_tmp81 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp82;
	signed int __cil_tmp83;
	signed int __cil_tmp88;
	__cil_tmp88 = __VERIFIER_nondet_signed_int();
	signed int __cil_tmp89;
	signed int __cil_tmp90;
	signed long int __cil_tmp91;
	if (!((disketteExtension__HoldNewRequests != 0))) goto Node_1_531;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 != __cil_tmp41))) goto Node_1_530;
__iv__current_func_call = 56;	ntStatus = FloppyQueueRequest(disketteExtension, Irp);
	return ntStatus;
	Node_1_530:;
	Node_1_531:;
	if (!((disketteExtension__IsRemoved != 0))) goto Node_1_667;
	Irp__IoStatus__Information = 0;
	Irp__IoStatus__Status___0 = -1073741738;
	myStatus = -1073741738;
__iv__current_func_call = 57;	IofCompleteRequest(Irp, 0);
	return -1073741738;
	Node_1_667:;
	if ((disketteExtension__IsStarted != 0)) goto Node_1_807;
	if (!((s == NP))) goto Node_1_672;
	s = SKIP1;
	goto Node_1_673;
	Node_1_672:;
__iv__current_func_call = 58;	errorFn();
	Node_1_673:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 59;	tmp = IofCallDriver(disketteExtension__TargetObject, Irp);
	return tmp;
	Node_1_807:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp44))) goto Node_1_811;
	goto Node_1_846;
	Node_1_811:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp45))) goto Node_1_814;
	goto Node_1_862;
	Node_1_814:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp50))) goto Node_1_817;
	goto Node_1_883;
	Node_1_817:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp55))) goto Node_1_820;
	goto Node_1_884;
	Node_1_820:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp60))) goto Node_1_823;
	goto Node_1_915;
	Node_1_823:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp65))) goto Node_1_826;
	goto Node_1_916;
	Node_1_826:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp66))) goto Node_1_829;
	goto Node_1_917;
	Node_1_829:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp69))) goto Node_1_832;
	goto Node_1_918;
	Node_1_832:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp72))) goto Node_1_835;
	goto Node_1_920;
	Node_1_835:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp75))) goto Node_1_838;
	goto Node_1_921;
	Node_1_838:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp78))) goto Node_1_841;
	goto Node_1_933;
	Node_1_841:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp81))) goto Node_1_844;
	goto Node_1_934;
	Node_1_844:;
	goto Node_1_935;
	Node_1_846:;
	if (!((irpSp__Parameters__DeviceIoControl__OutputBufferLength < sizeof__MOUNTDEV_NAME))) goto Node_1_850;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_850:;
	mountName = Irp__AssociatedIrp__SystemBuffer;
	mountName__NameLength = disketteExtension__DeviceName__Length;
	__cil_tmp82 = (sizeof__USHORT + mountName__NameLength);
	if (!((irpSp__Parameters__DeviceIoControl__OutputBufferLength < __cil_tmp82))) goto Node_1_858;
	ntStatus = -2147483643;
	Irp__IoStatus__Information = sizeof__MOUNTDEV_NAME;
	goto Node_1_1075;
	Node_1_858:;
	ntStatus = 0;
	Irp__IoStatus__Information = (sizeof__USHORT + mountName__NameLength);
	goto Node_1_1075;
	Node_1_862:;
	if ((disketteExtension__InterfaceString__Buffer != 0)) goto Node_1_867;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_867:;
	if (!((irpSp__Parameters__DeviceIoControl__OutputBufferLength < sizeof__MOUNTDEV_UNIQUE_ID))) goto Node_1_870;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_870:;
	uniqueId = Irp__AssociatedIrp__SystemBuffer;
	uniqueId__UniqueIdLength = disketteExtension__InterfaceString__Length;
	__cil_tmp83 = (sizeof__USHORT + uniqueId__UniqueIdLength);
	if (!((irpSp__Parameters__DeviceIoControl__OutputBufferLength < __cil_tmp83))) goto Node_1_879;
	ntStatus = -2147483643;
	Irp__IoStatus__Information = sizeof__MOUNTDEV_UNIQUE_ID;
	goto Node_1_1075;
	Node_1_879:;
	ntStatus = 0;
	Irp__IoStatus__Information = (sizeof__USHORT + uniqueId__UniqueIdLength);
	goto Node_1_1075;
	Node_1_883:;
	Node_1_884:;
	if (!((irpSp__Parameters__DeviceIoControl__InputBufferLength < sizeof__FORMAT_PARAMETERS))) goto Node_1_888;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_888:;
__iv__current_func_call = 60;	tmp___0 = FlCheckFormatParameters(disketteExtension, Irp__AssociatedIrp__SystemBuffer);
	if ((tmp___0 != 0)) goto Node_1_893;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_893:;
	if (!((irpSp__Parameters__DeviceIoControl__IoControlCode___1 == __cil_tmp88))) goto Node_1_914;
	if (!((irpSp__Parameters__DeviceIoControl__InputBufferLength < sizeof__FORMAT_EX_PARAMETERS))) goto Node_1_898;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_898:;
	formatExParameters = Irp__AssociatedIrp__SystemBuffer;
	if (!((irpSp__Parameters__DeviceIoControl__InputBufferLength < formatExParametersSize))) goto Node_1_904;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_904:;
	if (!((formatExParameters__FormatGapLength >= 256))) goto Node_1_908;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_908:;
	if (!((formatExParameters__SectorsPerTrack >= 256))) goto Node_1_911;
	ntStatus = -1073741811;
	goto Node_1_1075;
	Node_1_911:;
	Node_1_914:;
	Node_1_915:;
	Node_1_916:;
	Node_1_917:;
	Node_1_918:;
__iv__current_func_call = 61;	ntStatus = FlQueueIrpToThread(Irp, disketteExtension);
	goto Node_1_1075;
	Node_1_920:;
	Node_1_921:;
	outputBufferLength = irpSp__Parameters__DeviceIoControl__OutputBufferLength;
	if (!((outputBufferLength < sizeof__DISK_GEOMETRY))) goto Node_1_925;
	ntStatus = -1073741789;
	goto Node_1_1075;
	Node_1_925:;
	ntStatus = 0;
	__cil_tmp89 = (highestDriveMediaType - lowestDriveMediaType);
	__cil_tmp90 = (__cil_tmp89 + 1);
	if (!((outputBufferLength < __cil_tmp90))) goto Node_1_931;
	ntStatus = -2147483643;
	Node_1_931:;
	goto Node_1_1075;
	Node_1_933:;
	Node_1_934:;
	Node_1_935:;
	if (!((s == NP))) goto Node_1_939;
	s = SKIP1;
	goto Node_1_940;
	Node_1_939:;
__iv__current_func_call = 62;	errorFn();
	Node_1_940:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 63;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	return ntStatus;
	Node_1_1075:;
	__cil_tmp91 = (signed long int)(ntStatus);
	if (!((__cil_tmp91 != 259l))) goto Node_1_1094;
	Irp__IoStatus__Status___0 = ntStatus;
	myStatus = ntStatus;
__iv__current_func_call = 64;	IofCompleteRequest(Irp, 0);
	Node_1_1094:;
	return ntStatus;
}
signed int IoBuildDeviceIoControlRequest(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock) {
	signed int malloc;
	malloc = __VERIFIER_nondet_signed_int();
	customIrp = 1;
	signed int tmp_ndt_5;
	tmp_ndt_5 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_5 == 0))) goto Node_2_1236;
	goto Node_2_1238;
	Node_2_1236:;
	goto Node_2_1243;
	Node_2_1238:;
	return malloc;
	Node_2_1243:;
	return 0;
}
signed int FlFdcDeviceIo(signed int DeviceObject, signed int Ioctl, signed int Data) {
	signed int ntStatus;
	signed int irp;
	signed int irpStack;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	signed int ioStatus;
	ioStatus = __VERIFIER_nondet_signed_int();
	signed int irp__Tail__Overlay__CurrentStackLocation;
	irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	signed int irpStack__Parameters__DeviceIoControl__Type3InputBuffer;
	signed long int __cil_tmp11;
__iv__current_func_call = 70;	irp = IoBuildDeviceIoControlRequest(Ioctl, DeviceObject, 0, 0, 0, 0, 1, doneEvent, ioStatus);
	if (!((irp == 0))) goto Node_3_1288;
	return -1073741670;
	Node_3_1288:;
	irpStack = (irp__Tail__Overlay__CurrentStackLocation - 1);
	irpStack__Parameters__DeviceIoControl__Type3InputBuffer = Data;
__iv__current_func_call = 71;	ntStatus = IofCallDriver(DeviceObject, irp);
	__cil_tmp11 = (signed long int)(ntStatus);
	if (!((__cil_tmp11 == 259l))) goto Node_3_1296;
__iv__current_func_call = 72;	KeWaitForSingleObject(doneEvent, Suspended, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_3_1296:;
	return ntStatus;
}
signed int FloppyStartDevice(signed int DeviceObject, signed int Irp) {
	signed int DeviceObject__DeviceExtension;
	DeviceObject__DeviceExtension = __VERIFIER_nondet_signed_int();
	signed int Irp__Tail__Overlay__CurrentStackLocation;
	Irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	signed int Irp__IoStatus__Status;
	signed int disketteExtension__TargetObject;
	disketteExtension__TargetObject = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__MaxTransferSize;
	signed int disketteExtension__DriveType;
	disketteExtension__DriveType = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__DeviceUnit;
	signed int disketteExtension__DriveOnValue;
	signed int disketteExtension__UnderlyingPDO;
	disketteExtension__UnderlyingPDO = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__InterfaceString;
	disketteExtension__InterfaceString = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__IsStarted;
	signed int disketteExtension__HoldNewRequests;
	signed int ntStatus;
	signed int pnpStatus;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	signed int fdcInfo;
	fdcInfo = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__BufferCount;
	signed int fdcInfo__BufferSize;
	signed int fdcInfo__MaxTransferSize;
	fdcInfo__MaxTransferSize = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__AcpiBios;
	fdcInfo__AcpiBios = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__AcpiFdiSupported;
	fdcInfo__AcpiFdiSupported = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__PeripheralNumber;
	fdcInfo__PeripheralNumber = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__BusType;
	signed int fdcInfo__ControllerNumber;
	fdcInfo__ControllerNumber = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__UnitNumber;
	fdcInfo__UnitNumber = __VERIFIER_nondet_signed_int();
	signed int fdcInfo__BusNumber;
	fdcInfo__BusNumber = __VERIFIER_nondet_signed_int();
	signed int Dc;
	signed int Fp;
	signed int disketteExtension;
	signed int irpSp;
	signed int irpSp___0;
	signed int nextIrpSp;
	signed int nextIrpSp__Control;
	signed int irpSp___1;
	signed int irpSp__Control;
	signed int irpSp__Context;
	signed int InterfaceType;
	signed int KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86;
	KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 = __VERIFIER_nondet_signed_int();
	signed long int __cil_tmp42;
	signed int __cil_tmp46;
	__cil_tmp46 = __VERIFIER_nondet_signed_int();
	Dc = DiskController;
	Fp = FloppyDiskPeripheral;
	disketteExtension = DeviceObject__DeviceExtension;
	irpSp = Irp__Tail__Overlay__CurrentStackLocation;
	irpSp___0 = Irp__Tail__Overlay__CurrentStackLocation;
	nextIrpSp = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	nextIrpSp__Control = 0;
	if (!((s != NP))) goto Node_4_1419;
__iv__current_func_call = 90;	errorFn();
	goto Node_4_1424;
	Node_4_1419:;
	if (!((compRegistered != 0))) goto Node_4_1422;
__iv__current_func_call = 91;	errorFn();
	goto Node_4_1423;
	Node_4_1422:;
	compRegistered = 1;
	Node_4_1423:;
	Node_4_1424:;
	irpSp___1 = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	irpSp__Context = doneEvent;
	irpSp__Control = 224;
__iv__current_func_call = 92;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	__cil_tmp42 = (signed long int)(ntStatus);
	if (!((__cil_tmp42 == 259l))) goto Node_4_1433;
__iv__current_func_call = 93;	ntStatus = KeWaitForSingleObject(doneEvent, Executive, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_4_1433:;
	fdcInfo__BufferCount = 0;
	fdcInfo__BufferSize = 0;
__iv__current_func_call = 94;	ntStatus = FlFdcDeviceIo(disketteExtension__TargetObject, __cil_tmp46, fdcInfo);
	if (!((ntStatus >= 0))) goto Node_4_1481;
	disketteExtension__MaxTransferSize = fdcInfo__MaxTransferSize;
	if (!((fdcInfo__AcpiBios != 0))) goto Node_4_1448;
	if (!((fdcInfo__AcpiFdiSupported != 0))) goto Node_4_1445;
__iv__current_func_call = 95;	ntStatus = FlAcpiConfigureFloppy(disketteExtension, fdcInfo);
	if ((disketteExtension__DriveType == 4)) goto Node_4_1443;
	Node_4_1443:;
	goto Node_4_1446;
	Node_4_1445:;
	goto Node_4_1448;
	Node_4_1446:;
	goto Node_4_1466;
	Node_4_1448:;
	if ((disketteExtension__DriveType == 4)) goto Node_4_1449;
	Node_4_1449:;
	InterfaceType = 0;
	Node_4_1451:;
	if (!((1 != 0))) goto Node_4_1463;
	if ((InterfaceType >= MaximumInterfaceType)) goto Node_4_1465;
	fdcInfo__BusType = InterfaceType;
__iv__current_func_call = 96;	ntStatus = IoQueryDeviceDescription(fdcInfo__BusType, fdcInfo__BusNumber, Dc, fdcInfo__ControllerNumber, Fp, fdcInfo__PeripheralNumber, FlConfigCallBack, disketteExtension);
	if ((ntStatus >= 0)) goto Node_4_1465;
	InterfaceType = (InterfaceType + 1);
	goto Node_4_1451;
	Node_4_1463:;
	Node_4_1465:;
	Node_4_1466:;
	if (!((ntStatus >= 0))) goto Node_4_1480;
	if (!((KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 != 0))) goto Node_4_1472;
	disketteExtension__DeviceUnit = fdcInfo__UnitNumber;
	disketteExtension__DriveOnValue = fdcInfo__UnitNumber;
	goto Node_4_1473;
	Node_4_1472:;
	disketteExtension__DeviceUnit = fdcInfo__PeripheralNumber;
	Node_4_1473:;
__iv__current_func_call = 97;	pnpStatus = IoRegisterDeviceInterface(disketteExtension__UnderlyingPDO, MOUNTDEV_MOUNTED_DEVICE_GUID, 0, disketteExtension__InterfaceString);
	if (!((pnpStatus >= 0))) goto Node_4_1477;
__iv__current_func_call = 98;	pnpStatus = IoSetDeviceInterfaceState(disketteExtension__InterfaceString, 1);
	Node_4_1477:;
	disketteExtension__IsStarted = 1;
	disketteExtension__HoldNewRequests = 0;
	Node_4_1480:;
	Node_4_1481:;
	Irp__IoStatus__Status = ntStatus;
	myStatus = ntStatus;
__iv__current_func_call = 99;	IofCompleteRequest(Irp, 0);
	return ntStatus;
}
signed int FloppyPnp(signed int DeviceObject, signed int Irp) {
	signed int DeviceObject__DeviceExtension;
	DeviceObject__DeviceExtension = __VERIFIER_nondet_signed_int();
	signed int Irp__Tail__Overlay__CurrentStackLocation;
	Irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	signed int Irp__IoStatus__Information;
	signed int Irp__IoStatus__Status;
	signed int Irp__CurrentLocation;
	Irp__CurrentLocation = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__IsRemoved;
	disketteExtension__IsRemoved = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__IsStarted;
	disketteExtension__IsStarted = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__TargetObject;
	disketteExtension__TargetObject = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__HoldNewRequests;
	signed int disketteExtension__FloppyThread;
	disketteExtension__FloppyThread = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__InterfaceString__Buffer;
	disketteExtension__InterfaceString__Buffer = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__InterfaceString;
	disketteExtension__InterfaceString = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__ArcName__Length;
	disketteExtension__ArcName__Length = __VERIFIER_nondet_signed_int();
	signed int disketteExtension__ArcName;
	disketteExtension__ArcName = __VERIFIER_nondet_signed_int();
	signed int irpSp__MinorFunction;
	irpSp__MinorFunction = __VERIFIER_nondet_signed_int();
	signed int IoGetConfigurationInformation__FloppyCount;
	IoGetConfigurationInformation__FloppyCount = __VERIFIER_nondet_signed_int();
	signed int irpSp;
	signed int disketteExtension;
	signed int ntStatus;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	signed int irpSp___0;
	signed int nextIrpSp;
	signed int nextIrpSp__Control;
	signed int irpSp___1;
	signed int irpSp__Context;
	signed int irpSp__Control;
	signed long int __cil_tmp29;
	signed long int __cil_tmp30;
	ntStatus = 0;
	PagingReferenceCount = (PagingReferenceCount + 1);
	if ((PagingReferenceCount == 1)) goto Node_5_1625;
	Node_5_1625:;
	disketteExtension = DeviceObject__DeviceExtension;
	irpSp = Irp__Tail__Overlay__CurrentStackLocation;
	if (!((disketteExtension__IsRemoved != 0))) goto Node_5_1677;
	Irp__IoStatus__Information = 0;
	Irp__IoStatus__Status = -1073741738;
	myStatus = -1073741738;
__iv__current_func_call = 114;	IofCompleteRequest(Irp, 0);
	return -1073741738;
	Node_5_1677:;
	if (!((irpSp__MinorFunction == 0))) goto Node_5_1681;
	goto Node_5_1701;
	Node_5_1681:;
	if (!((irpSp__MinorFunction == 5))) goto Node_5_1684;
	goto Node_5_1703;
	Node_5_1684:;
	if (!((irpSp__MinorFunction == 1))) goto Node_5_1687;
	goto Node_5_1703;
	Node_5_1687:;
	if (!((irpSp__MinorFunction == 6))) goto Node_5_1690;
	goto Node_5_1785;
	Node_5_1690:;
	if (!((irpSp__MinorFunction == 3))) goto Node_5_1693;
	goto Node_5_1785;
	Node_5_1693:;
	if (!((irpSp__MinorFunction == 4))) goto Node_5_1696;
	goto Node_5_1829;
	Node_5_1696:;
	if (!((irpSp__MinorFunction == 2))) goto Node_5_1699;
	goto Node_5_1841;
	Node_5_1699:;
	goto Node_5_1862;
	Node_5_1701:;
__iv__current_func_call = 115;	ntStatus = FloppyStartDevice(DeviceObject, Irp);
	goto Node_5_1872;
	Node_5_1703:;
	if ((irpSp__MinorFunction == 5)) goto Node_5_1704;
	Node_5_1704:;
	if ((disketteExtension__IsStarted != 0)) goto Node_5_1758;
	if (!((s == NP))) goto Node_5_1709;
	s = SKIP1;
	goto Node_5_1710;
	Node_5_1709:;
__iv__current_func_call = 116;	errorFn();
	Node_5_1710:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 117;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	return ntStatus;
	Node_5_1758:;
	disketteExtension__HoldNewRequests = 1;
__iv__current_func_call = 118;	ntStatus = FlQueueIrpToThread(Irp, disketteExtension);
	__cil_tmp29 = (signed long int)(ntStatus);
	if (!((__cil_tmp29 == 259l))) goto Node_5_1778;
__iv__current_func_call = 119;	KeWaitForSingleObject(disketteExtension__FloppyThread, Executive, KernelMode, 0, 0);
	if ((disketteExtension__FloppyThread != 0)) goto Node_5_1765;
	Node_5_1765:;
	disketteExtension__FloppyThread = 0;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_5_1772;
	s = SKIP1;
	goto Node_5_1773;
	Node_5_1772:;
__iv__current_func_call = 120;	errorFn();
	Node_5_1773:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	goto Node_5_1783;
	Node_5_1778:;
	ntStatus = -1073741823;
__iv__current_func_call = 121;	Irp__IoStatus__Status = IofCallDriver(disketteExtension__TargetObject, Irp);
	myStatus = ntStatus;
	Irp__IoStatus__Information = 0;
__iv__current_func_call = 122;	IofCompleteRequest(Irp, 0);
	Node_5_1783:;
	goto Node_5_1872;
	Node_5_1785:;
	if ((irpSp__MinorFunction == 6)) goto Node_5_1786;
	Node_5_1786:;
	if ((disketteExtension__IsStarted != 0)) goto Node_5_1799;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_5_1793;
	s = SKIP1;
	goto Node_5_1794;
	Node_5_1793:;
__iv__current_func_call = 123;	errorFn();
	Node_5_1794:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 124;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_5_1827;
	Node_5_1799:;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	irpSp___0 = Irp__Tail__Overlay__CurrentStackLocation;
	nextIrpSp = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	nextIrpSp__Control = 0;
	if (!((s != NP))) goto Node_5_1807;
__iv__current_func_call = 125;	errorFn();
	goto Node_5_1812;
	Node_5_1807:;
	if (!((compRegistered != 0))) goto Node_5_1810;
__iv__current_func_call = 126;	errorFn();
	goto Node_5_1811;
	Node_5_1810:;
	compRegistered = 1;
	Node_5_1811:;
	Node_5_1812:;
	irpSp___1 = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	irpSp__Context = doneEvent;
	irpSp__Control = 224;
__iv__current_func_call = 127;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	__cil_tmp30 = (signed long int)(ntStatus);
	if (!((__cil_tmp30 == 259l))) goto Node_5_1821;
__iv__current_func_call = 128;	KeWaitForSingleObject(doneEvent, Executive, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_5_1821:;
	disketteExtension__HoldNewRequests = 0;
	Irp__IoStatus__Status = ntStatus;
	myStatus = ntStatus;
	Irp__IoStatus__Information = 0;
__iv__current_func_call = 129;	IofCompleteRequest(Irp, 0);
	Node_5_1827:;
	goto Node_5_1872;
	Node_5_1829:;
	disketteExtension__IsStarted = 0;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_5_1835;
	s = SKIP1;
	goto Node_5_1836;
	Node_5_1835:;
__iv__current_func_call = 130;	errorFn();
	Node_5_1836:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 131;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_5_1872;
	Node_5_1841:;
	disketteExtension__HoldNewRequests = 0;
	disketteExtension__IsStarted = 0;
	disketteExtension__IsRemoved = 1;
	if (!((s == NP))) goto Node_5_1847;
	s = SKIP1;
	goto Node_5_1848;
	Node_5_1847:;
__iv__current_func_call = 132;	errorFn();
	Node_5_1848:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	Irp__IoStatus__Status = 0;
	myStatus = 0;
__iv__current_func_call = 133;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	if (!((disketteExtension__InterfaceString__Buffer != 0))) goto Node_5_1856;
__iv__current_func_call = 134;	IoSetDeviceInterfaceState(disketteExtension__InterfaceString, 0);
	Node_5_1856:;
	if (!((disketteExtension__ArcName__Length != 0))) goto Node_5_1859;
__iv__current_func_call = 135;	IoDeleteSymbolicLink(disketteExtension__ArcName);
	Node_5_1859:;
	IoGetConfigurationInformation__FloppyCount = (IoGetConfigurationInformation__FloppyCount - 1);
	goto Node_5_1872;
	Node_5_1862:;
	if (!((s == NP))) goto Node_5_1866;
	s = SKIP1;
	goto Node_5_1867;
	Node_5_1866:;
__iv__current_func_call = 136;	errorFn();
	Node_5_1867:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
__iv__current_func_call = 137;	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_5_1873;
	Node_5_1872:;
	Node_5_1873:;
	PagingReferenceCount = (PagingReferenceCount - 1);
	if ((PagingReferenceCount == 0)) goto Node_5_1883;
	Node_5_1883:;
	return ntStatus;
}
signed int FloppyQueueRequest(signed int DisketteExtension, signed int Irp) {
	signed int Irp__IoStatus__Status;
	signed int Irp__IoStatus__Information;
	signed int ntStatus;
	signed int FAKE_CONDITION;
	FAKE_CONDITION = __VERIFIER_nondet_signed_int();
	PagingReferenceCount = (PagingReferenceCount + 1);
	if ((PagingReferenceCount == 1)) goto Node_6_1939;
	Node_6_1939:;
	if (!((FAKE_CONDITION != 0))) goto Node_6_1950;
	Irp__IoStatus__Status = -1073741536;
	myStatus = -1073741536;
	Irp__IoStatus__Information = 0;
__iv__current_func_call = 139;	IofCompleteRequest(Irp, 0);
	PagingReferenceCount = (PagingReferenceCount - 1);
	if ((PagingReferenceCount == 0)) goto Node_6_1947;
	Node_6_1947:;
	ntStatus = -1073741536;
	goto Node_6_1958;
	Node_6_1950:;
	Irp__IoStatus__Status = 259;
	myStatus = 259;
	if (!((pended == 0))) goto Node_6_1955;
	pended = 1;
	goto Node_6_1956;
	Node_6_1955:;
__iv__current_func_call = 140;	errorFn();
	Node_6_1956:;
	ntStatus = 259;
	Node_6_1958:;
	return ntStatus;
}
signed int FlCheckFormatParameters(signed int DisketteExtension, signed int FormatParameters) {
	signed int DriveMediaConstants__driveMediaType__MediaType;
	DriveMediaConstants__driveMediaType__MediaType = __VERIFIER_nondet_signed_int();
	signed int FormatParameters__MediaType;
	FormatParameters__MediaType = __VERIFIER_nondet_signed_int();
	signed int FAKE_CONDITION;
	FAKE_CONDITION = __VERIFIER_nondet_signed_int();
	if (!((DriveMediaConstants__driveMediaType__MediaType != FormatParameters__MediaType))) goto Node_7_1990;
	return 0;
	Node_7_1990:;
	if (!((FAKE_CONDITION != 0))) goto Node_7_2000;
	return 0;
	Node_7_2000:;
	return 1;
}
signed int KeSetEvent(signed int Event, signed int Increment, signed int Wait) {
	signed int l;
	l = __VERIFIER_nondet_signed_int();
	setEventCalled = 1;
	return l;
}
signed int FlQueueIrpToThread(signed int Irp, signed int DisketteExtension) {
	signed int status;
	signed int threadHandle;
	threadHandle = __VERIFIER_nondet_signed_int();
	signed int DisketteExtension__PoweringDown;
	DisketteExtension__PoweringDown = __VERIFIER_nondet_signed_int();
	signed int DisketteExtension__ThreadReferenceCount;
	DisketteExtension__ThreadReferenceCount = __VERIFIER_nondet_signed_int();
	signed int DisketteExtension__FloppyThread;
	DisketteExtension__FloppyThread = __VERIFIER_nondet_signed_int();
	signed int Irp__IoStatus__Status;
	signed int Irp__IoStatus__Information;
	signed int ObjAttributes;
	ObjAttributes = __VERIFIER_nondet_signed_int();
	if (!((DisketteExtension__PoweringDown == 1))) goto Node_9_2076;
	myStatus = -1073741101;
	Irp__IoStatus__Status = -1073741101;
	Irp__IoStatus__Information = 0;
	return -1073741101;
	Node_9_2076:;
	DisketteExtension__ThreadReferenceCount = (DisketteExtension__ThreadReferenceCount + 1);
	if (!((DisketteExtension__ThreadReferenceCount == 0))) goto Node_9_2130;
	DisketteExtension__ThreadReferenceCount = (DisketteExtension__ThreadReferenceCount + 1);
	PagingReferenceCount = (PagingReferenceCount + 1);
	if ((PagingReferenceCount == 1)) goto Node_9_2082;
	Node_9_2082:;
__iv__current_func_call = 150;	status = PsCreateSystemThread(threadHandle, 0, ObjAttributes, 0, 0, FloppyThread, DisketteExtension);
	if (!((status < 0))) goto Node_9_2107;
	DisketteExtension__ThreadReferenceCount = -1;
	PagingReferenceCount = (PagingReferenceCount - 1);
	if ((PagingReferenceCount == 0)) goto Node_9_2088;
	Node_9_2088:;
	return status;
	Node_9_2107:;
__iv__current_func_call = 151;	status = ObReferenceObjectByHandle(threadHandle, 1048576, 0, KernelMode, DisketteExtension__FloppyThread, 0);
__iv__current_func_call = 152;	ZwClose(threadHandle);
	if (!((status < 0))) goto Node_9_2129;
	return status;
	Node_9_2129:;
	Node_9_2130:;
	if (!((pended == 0))) goto Node_9_2134;
	pended = 1;
	goto Node_9_2135;
	Node_9_2134:;
__iv__current_func_call = 153;	errorFn();
	Node_9_2135:;
	return 259;
}
signed int FloppyCreateClose(signed int DeviceObject, signed int Irp) {
	signed int Irp__IoStatus__Status;
	signed int Irp__IoStatus__Information;
	myStatus = 0;
	Irp__IoStatus__Status = 0;
	Irp__IoStatus__Information = 1;
__iv__current_func_call = 154;	IofCompleteRequest(Irp, 0);
	return 0;
}
signed int ObReferenceObjectByHandle(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation) {
	signed int tmp_ndt_13;
	tmp_ndt_13 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_13 == 0))) goto Node_11_2171;
	goto Node_11_2173;
	Node_11_2171:;
	goto Node_11_2176;
	Node_11_2173:;
	return 0;
	Node_11_2176:;
	return -1073741823;
}
signed int KeWaitForSingleObject(signed int Object, signed int WaitReason, signed int WaitMode, signed int Alertable, signed int Timeout) {
	if (!((s == MPR3))) goto Node_12_2193;
	if (!((setEventCalled == 1))) goto Node_12_2190;
	s = NP;
	setEventCalled = 0;
	goto Node_12_2191;
	Node_12_2190:;
	goto Node_12_2193;
	Node_12_2191:;
	goto Node_12_2201;
	Node_12_2193:;
	if (!((customIrp == 1))) goto Node_12_2197;
	s = NP;
	customIrp = 0;
	goto Node_12_2200;
	Node_12_2197:;
	if (!((s == MPR3))) goto Node_12_2199;
__iv__current_func_call = 156;	errorFn();
	Node_12_2199:;
	Node_12_2200:;
	Node_12_2201:;
	signed int tmp_ndt_12;
	tmp_ndt_12 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_12 == 0))) goto Node_12_2207;
	goto Node_12_2209;
	Node_12_2207:;
	goto Node_12_2212;
	Node_12_2209:;
	return 0;
	Node_12_2212:;
	return -1073741823;
}
signed int IofCallDriver(signed int DeviceObject, signed int Irp) {
	signed int returnVal2;
	signed int compRetStatus1;
	signed int lcontext;
	lcontext = __VERIFIER_nondet_signed_int();
	unsigned long int __cil_tmp7;
	if (!((compRegistered != 0))) goto Node_13_2234;
__iv__current_func_call = 159;	compRetStatus1 = FloppyPnpComplete(DeviceObject, Irp, lcontext);
	__cil_tmp7 = (unsigned long int)(compRetStatus1);
	if (!((__cil_tmp7 == (unsigned long int)(-1073741802)))) goto Node_13_2233;
__iv__current_func_call = 160;	stubMoreProcessingRequired();
	Node_13_2233:;
	Node_13_2234:;
	signed int tmp_ndt_10;
	tmp_ndt_10 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_10 == 0))) goto Node_13_2240;
	goto Node_13_2247;
	Node_13_2240:;
	signed int tmp_ndt_11;
	tmp_ndt_11 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_11 == 1))) goto Node_13_2245;
	goto Node_13_2249;
	Node_13_2245:;
	goto Node_13_2251;
	Node_13_2247:;
	returnVal2 = 0;
	goto Node_13_2254;
	Node_13_2249:;
	returnVal2 = -1073741823;
	goto Node_13_2254;
	Node_13_2251:;
	returnVal2 = 259;
	if (FALSE) goto Node_13_2253;
	Node_13_2253:;
	Node_13_2254:;
	if (!((s == NP))) goto Node_13_2263;
	s = IPC;
	lowerDriverReturn = returnVal2;
	goto Node_13_2279;
	Node_13_2263:;
	if (!((s == MPR1))) goto Node_13_2272;
	if (!((returnVal2 == 259))) goto Node_13_2268;
	s = MPR3;
	lowerDriverReturn = returnVal2;
	goto Node_13_2270;
	Node_13_2268:;
	s = NP;
	lowerDriverReturn = returnVal2;
	Node_13_2270:;
	goto Node_13_2278;
	Node_13_2272:;
	if (!((s == SKIP1))) goto Node_13_2276;
	s = SKIP2;
	lowerDriverReturn = returnVal2;
	goto Node_13_2277;
	Node_13_2276:;
__iv__current_func_call = 163;	errorFn();
	Node_13_2277:;
	Node_13_2278:;
	Node_13_2279:;
	return returnVal2;
}
void stubMoreProcessingRequired() {
	if (!((s == NP))) goto Node_14_2292;
	s = MPR1;
	goto Node_14_2293;
	Node_14_2292:;
__iv__current_func_call = 164;	errorFn();
	Node_14_2293:;
	goto Node_14_2295;
	Node_14_2295:;
	// End of Function
}
signed int IoSetDeviceInterfaceState(signed int SymbolicLinkName, signed int Enable) {
	signed int tmp_ndt_9;
	tmp_ndt_9 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_9 == 0))) goto Node_15_2301;
	goto Node_15_2303;
	Node_15_2301:;
	goto Node_15_2306;
	Node_15_2303:;
	return 0;
	Node_15_2306:;
	return -1073741823;
}
signed int PsCreateSystemThread(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext) {
	signed int tmp_ndt_14;
	tmp_ndt_14 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_14 == 0))) goto Node_16_2320;
	goto Node_16_2322;
	Node_16_2320:;
	goto Node_16_2325;
	Node_16_2322:;
	return 0;
	Node_16_2325:;
	return -1073741823;
}
void stub_driver_init() {
	s = NP;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	goto Node_17_2341;
	Node_17_2341:;
	// End of Function
}
void FloppyProcessQueuedRequests(signed int DisketteExtension) {
	goto Node_18_2343;
	Node_18_2343:;
	// End of Function
}
signed int IoRegisterDeviceInterface(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName) {
	signed int tmp_ndt_8;
	tmp_ndt_8 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_8 == 0))) goto Node_19_2349;
	goto Node_19_2351;
	Node_19_2349:;
	goto Node_19_2354;
	Node_19_2351:;
	return 0;
	Node_19_2354:;
	return -1073741808;
}
signed int IoQueryDeviceDescription(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context) {
	signed int tmp_ndt_7;
	tmp_ndt_7 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_7 == 0))) goto Node_20_2368;
	goto Node_20_2370;
	Node_20_2368:;
	goto Node_20_2373;
	Node_20_2370:;
	return 0;
	Node_20_2373:;
	return -1073741823;
}
signed int IoDeleteSymbolicLink(signed int SymbolicLinkName) {
	signed int tmp_ndt_6;
	tmp_ndt_6 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_6 == 0))) goto Node_21_2387;
	goto Node_21_2389;
	Node_21_2387:;
	goto Node_21_2392;
	Node_21_2389:;
	return 0;
	Node_21_2392:;
	return -1073741823;
}
signed int FloppyPnpComplete(signed int DeviceObject, signed int Irp, signed int Context) {
__iv__current_func_call = 170;	KeSetEvent(Context, 1, 0);
	return -1073741802;
}
signed int ZwClose(signed int Handle) {
	signed int tmp_ndt_15;
	tmp_ndt_15 = __VERIFIER_nondet_signed_int();
	if (!((tmp_ndt_15 == 0))) goto Node_24_2456;
	goto Node_24_2458;
	Node_24_2456:;
	goto Node_24_2461;
	Node_24_2458:;
	return 0;
	Node_24_2461:;
	return -1073741823;
}
void reach_error() {
	assert(FALSE);
	// End of Function
}
signed int FlAcpiConfigureFloppy(signed int DisketteExtension, signed int FdcInfo) {
	return 0;
}
void errorFn() {
__iv__current_func_call = 173;	reach_error();
	abort();
}
void IofCompleteRequest(signed int Irp, signed int PriorityBoost) {
	if (!((s == NP))) goto Node_29_2487;
	s = DC;
	goto Node_29_2488;
	Node_29_2487:;
__iv__current_func_call = 175;	errorFn();
	Node_29_2488:;
	goto Node_29_2490;
	Node_29_2490:;
	// End of Function
}
void _BLAST_init() {
	UNLOADED = 0;
	NP = 1;
	DC = 2;
	SKIP1 = 3;
	SKIP2 = 4;
	MPR1 = 5;
	MPR3 = 6;
	IPC = 7;
	s = UNLOADED;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	goto Node_30_2506;
	Node_30_2506:;
	// End of Function
}
