/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 117 "target.c"
void __globinit_target(void) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 209 "/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h"
typedef unsigned long size_t;
#line 152 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE;
#line 4
struct _IO_FILE;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
struct _IO_FILE;
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
#line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE;
#line 36
struct _IO_marker;
#line 36
struct _IO_marker;
#line 37
struct _IO_codecvt;
#line 37
struct _IO_codecvt;
#line 38
struct _IO_wide_data;
#line 38
struct _IO_wide_data;
#line 43 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
#line 49 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 20 "target.c"
enum anonymous {
    INIT = 0,
    IDLE = 1,
    RUN = 2,
    STOP = 3,
    EMERGENCY = -1
} ;
#line 24 "target.c"
typedef long clock_t___0;
#line 26 "target.c"
typedef enum anonymous elevState;
#line 372 "/opt/CROWN-CLI-ubuntu18.04/bin/../include/crown.h"
extern void __CrownInt(int *x , int cnt_sym_var , int ln , char *fname  , ...)  __attribute__((__crown_skip__)) ;
#line 138 "/usr/include/stdio.h"
extern FILE *stdout ;
#line 139
extern FILE *stderr ;
#line 213
extern int fclose(FILE *__stream ) ;
#line 218
extern int fflush(FILE *__stream ) ;
#line 246
extern FILE *fopen(char    * __restrict  __filename , char    * __restrict  __modes ) ;
#line 326
extern int fprintf(FILE * __restrict  __stream , char    * __restrict  __format  , ...) ;
#line 332
extern int printf(char    * __restrict  __format  , ...) ;
#line 617 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 7 "target.c"
int __iv__max_path  ;
#line 8 "target.c"
int __iv__nondet_call_counter  ;
#line 9 "target.c"
FILE *__iv__fp  ;
#line 59
int isButtonPressed(void) ;
#line 72 "target.c"
int currentFloorLocation  =    -1;
#line 73 "target.c"
elevState currentState  =    (elevState )0;
#line 77 "target.c"
int lastFloorAfterEmergency  =    -1;
#line 78 "target.c"
int motorDirection  =    0;
#line 79 "target.c"
int orderMatrix[3L][4L]  = { {        0,        0,        0,        0}, 
   {        0,        0,        0,        0}, 
   {        0,        0,        0,        0}};
#line 80 "target.c"
int previousMainFloor  =    -1;
#line 81 "target.c"
elevState previousState  =    (elevState )0;
#line 82 "target.c"
clock_t___0 previousTime  =    0L;
#line 85 "target.c"
int isButtonPressed(void) 
{ 
  int button ;
  int floorNum ;
  int __retres3 ;

  {
  __CrownCheckSymbolic(2, "isButtonPressed");
  __CrownCall(1, 1);

  __CrownLoad(3, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(4, (unsigned long )(& button));
#line 87
  button = 0;
  Node_7_365: 
  __CrownLoad(7, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(6, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(5, 0, 5, (long long )(__iv__max_path + 1), (double )(__iv__max_path + 1));
  __CrownStore(8, (unsigned long )(& __iv__max_path));
#line 89
  __iv__max_path ++;
  {
  __CrownLoad(11, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(10, (unsigned long )0, 5, (long long )10000, (double )10000);
  __CrownApply2(9, 22, 5, (long long )(__iv__max_path >= 10000), (double )(__iv__max_path >= 10000));
#line 90
  if (__iv__max_path >= 10000) {
    __CrownBranch(12, 4, 1, __LINE__, __FILE__);
    __CrownLoad(14, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownStore(15, (unsigned long )(& __retres3));
#line 90
    __retres3 = 0;
#line 90
    goto return_label;
  } 
    #line 90
    else {
    __CrownBranch(13, 6, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(16, (unsigned long )0, 6, (long long )((char    * __restrict  )"Node_7_365:%d\n"),
              8);
  __CrownLoad(19, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownLoad(18, (unsigned long )0, 5, (long long )3, (double )3);
  __CrownApply2(17, 22, 5, (long long )(button >= 3), (double )(button >= 3));
  __CrownSetCallerCalleeName(20, "isButtonPressed", "printf");
#line 91
  printf((char    * __restrict  )"Node_7_365:%d\n", button >= 3);
  __CrownEnableSymbolic(22, "isButtonPressed");
  __CrownClearStack(21);
  __CrownLoad(23, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(24, "isButtonPressed", "fflush");
#line 91
  fflush(stdout);
  __CrownEnableSymbolic(26, "isButtonPressed");
  __CrownClearStack(25);
  {
  __CrownLoad(29, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownLoad(28, (unsigned long )0, 5, (long long )3, (double )3);
  __CrownApply2(27, 22, 5, (long long )(button >= 3), (double )(button >= 3));
#line 92
  if (button >= 3) {
    __CrownBranch(30, 9, 1, __LINE__, __FILE__);
#line 92
    goto Node_7_382;
  } 
    #line 92
    else {
    __CrownBranch(31, 10, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(32, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(33, (unsigned long )(& floorNum));
#line 94
  floorNum = 0;
  Node_7_369: 
  __CrownLoad(36, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(35, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(34, 0, 5, (long long )(__iv__max_path + 1), (double )(__iv__max_path + 1));
  __CrownStore(37, (unsigned long )(& __iv__max_path));
#line 96
  __iv__max_path ++;
  {
  __CrownLoad(40, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(39, (unsigned long )0, 5, (long long )10000, (double )10000);
  __CrownApply2(38, 22, 5, (long long )(__iv__max_path >= 10000), (double )(__iv__max_path >= 10000));
#line 97
  if (__iv__max_path >= 10000) {
    __CrownBranch(41, 14, 1, __LINE__, __FILE__);
    __CrownLoad(43, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownStore(44, (unsigned long )(& __retres3));
#line 97
    __retres3 = 0;
#line 97
    goto return_label;
  } 
    #line 97
    else {
    __CrownBranch(42, 16, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(45, (unsigned long )0, 6, (long long )((char    * __restrict  )"Node_7_369:%d\n"),
              8);
  __CrownLoad(48, (unsigned long )(& floorNum), 5, (long long )floorNum, (double )floorNum);
  __CrownLoad(47, (unsigned long )0, 5, (long long )4, (double )4);
  __CrownApply2(46, 22, 5, (long long )(floorNum >= 4), (double )(floorNum >= 4));
  __CrownSetCallerCalleeName(49, "isButtonPressed", "printf");
#line 98
  printf((char    * __restrict  )"Node_7_369:%d\n", floorNum >= 4);
  __CrownEnableSymbolic(51, "isButtonPressed");
  __CrownClearStack(50);
  __CrownLoad(52, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(53, "isButtonPressed", "fflush");
#line 98
  fflush(stdout);
  __CrownEnableSymbolic(55, "isButtonPressed");
  __CrownClearStack(54);
  {
  __CrownLoad(58, (unsigned long )(& floorNum), 5, (long long )floorNum, (double )floorNum);
  __CrownLoad(57, (unsigned long )0, 5, (long long )4, (double )4);
  __CrownApply2(56, 22, 5, (long long )(floorNum >= 4), (double )(floorNum >= 4));
#line 99
  if (floorNum >= 4) {
    __CrownBranch(59, 19, 1, __LINE__, __FILE__);
#line 99
    goto Node_7_378;
  } 
    #line 99
    else {
    __CrownBranch(60, 20, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(63, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(62, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(61, 0, 5, (long long )(__iv__max_path + 1), (double )(__iv__max_path + 1));
  __CrownStore(64, (unsigned long )(& __iv__max_path));
#line 100
  __iv__max_path ++;
  {
  __CrownLoad(67, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
              (double )__iv__max_path);
  __CrownLoad(66, (unsigned long )0, 5, (long long )10000, (double )10000);
  __CrownApply2(65, 22, 5, (long long )(__iv__max_path >= 10000), (double )(__iv__max_path >= 10000));
#line 101
  if (__iv__max_path >= 10000) {
    __CrownBranch(68, 23, 1, __LINE__, __FILE__);
    __CrownLoad(70, (unsigned long )0, 5, (long long )0, (double )0);
    __CrownStore(71, (unsigned long )(& __retres3));
#line 101
    __retres3 = 0;
#line 101
    goto return_label;
  } 
    #line 101
    else {
    __CrownBranch(69, 25, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(72, (unsigned long )0, 6, (long long )((char    * __restrict  )"Node_7_370:%d\n"),
              8);
  __CrownLoad(76, (unsigned long )(& orderMatrix[(long )button][(long )floorNum]),
              5, (long long )orderMatrix[(long )button][(long )floorNum], (double )orderMatrix[(long )button][(long )floorNum]);
  __CrownLoad(75, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(74, 13, 5, (long long )(orderMatrix[(long )button][(long )floorNum] == 1),
                (double )(orderMatrix[(long )button][(long )floorNum] == 1));
  __CrownApply1(73, 26, 5, (long long )(! (orderMatrix[(long )button][(long )floorNum] == 1)),
                (double )(! (orderMatrix[(long )button][(long )floorNum] == 1)));
  __CrownSetCallerCalleeName(77, "isButtonPressed", "printf");
#line 102
  printf((char    * __restrict  )"Node_7_370:%d\n", ! (orderMatrix[(long )button][(long )floorNum] == 1));
  __CrownEnableSymbolic(79, "isButtonPressed");
  __CrownClearStack(78);
  __CrownLoad(80, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(81, "isButtonPressed", "fflush");
#line 102
  fflush(stdout);
  __CrownEnableSymbolic(83, "isButtonPressed");
  __CrownClearStack(82);
  {
  __CrownLoad(87, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(86, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownApply1(85, 28, 7, (long long )((long )button), (double )((long )button));
  __CrownApply2(84, 16, 5, (long long )(0L > (long )button), (double )(0L > (long )button));
#line 103
  if (0L > (long )button) {
    __CrownBranch(88, 28, 1, __LINE__, __FILE__);
    __CrownLoad(90, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(91, (unsigned long )(& __iv__max_path));
#line 103
    __iv__max_path = 10000;
  } 
    #line 103
    else {
    __CrownBranch(89, 29, 0, __LINE__, __FILE__);
    {
    __CrownLoad(95, (unsigned long )(& button), 5, (long long )button, (double )button);
    __CrownApply1(94, 28, 7, (long long )((long )button), (double )((long )button));
    __CrownLoad(93, (unsigned long )0, 7, (long long )3L, (double )3L);
    __CrownApply2(92, 22, 5, (long long )((long )button >= 3L), (double )((long )button >= 3L));
#line 103
    if ((long )button >= 3L) {
      __CrownBranch(96, 30, 1, __LINE__, __FILE__);
      __CrownLoad(98, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(99, (unsigned long )(& __iv__max_path));
#line 103
      __iv__max_path = 10000;
    } 
      #line 103
      else {
      __CrownBranch(97, 31, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  {
  __CrownLoad(103, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(102, (unsigned long )(& floorNum), 5, (long long )floorNum, (double )floorNum);
  __CrownApply1(101, 28, 7, (long long )((long )floorNum), (double )((long )floorNum));
  __CrownApply2(100, 16, 5, (long long )(0L > (long )floorNum), (double )(0L > (long )floorNum));
#line 104
  if (0L > (long )floorNum) {
    __CrownBranch(104, 33, 1, __LINE__, __FILE__);
    __CrownLoad(106, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(107, (unsigned long )(& __iv__max_path));
#line 104
    __iv__max_path = 10000;
  } 
    #line 104
    else {
    __CrownBranch(105, 34, 0, __LINE__, __FILE__);
    {
    __CrownLoad(111, (unsigned long )(& floorNum), 5, (long long )floorNum, (double )floorNum);
    __CrownApply1(110, 28, 7, (long long )((long )floorNum), (double )((long )floorNum));
    __CrownLoad(109, (unsigned long )0, 7, (long long )4L, (double )4L);
    __CrownApply2(108, 22, 5, (long long )((long )floorNum >= 4L), (double )((long )floorNum >= 4L));
#line 104
    if ((long )floorNum >= 4L) {
      __CrownBranch(112, 35, 1, __LINE__, __FILE__);
      __CrownLoad(114, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(115, (unsigned long )(& __iv__max_path));
#line 104
      __iv__max_path = 10000;
    } 
      #line 104
      else {
      __CrownBranch(113, 36, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  {
  __CrownLoad(119, (unsigned long )0, 7, (long long )0L, (double )0L);
  __CrownLoad(118, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownApply1(117, 28, 7, (long long )((long )button), (double )((long )button));
  __CrownApply2(116, 16, 5, (long long )(0L > (long )button), (double )(0L > (long )button));
#line 105
  if (0L > (long )button) {
    __CrownBranch(120, 38, 1, __LINE__, __FILE__);
    __CrownLoad(122, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownStore(123, (unsigned long )(& __iv__max_path));
#line 105
    __iv__max_path = 10000;
  } 
    #line 105
    else {
    __CrownBranch(121, 39, 0, __LINE__, __FILE__);
    {
    __CrownLoad(127, (unsigned long )(& button), 5, (long long )button, (double )button);
    __CrownApply1(126, 28, 7, (long long )((long )button), (double )((long )button));
    __CrownLoad(125, (unsigned long )0, 7, (long long )3L, (double )3L);
    __CrownApply2(124, 22, 5, (long long )((long )button >= 3L), (double )((long )button >= 3L));
#line 105
    if ((long )button >= 3L) {
      __CrownBranch(128, 40, 1, __LINE__, __FILE__);
      __CrownLoad(130, (unsigned long )0, 5, (long long )10000, (double )10000);
      __CrownStore(131, (unsigned long )(& __iv__max_path));
#line 105
      __iv__max_path = 10000;
    } 
      #line 105
      else {
      __CrownBranch(129, 41, 0, __LINE__, __FILE__);

    }
    }
  }
  }
  {
  __CrownLoad(135, (unsigned long )(& orderMatrix[(long )button][(long )floorNum]),
              5, (long long )orderMatrix[(long )button][(long )floorNum], (double )orderMatrix[(long )button][(long )floorNum]);
  __CrownLoad(134, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(133, 13, 5, (long long )(orderMatrix[(long )button][(long )floorNum] == 1),
                (double )(orderMatrix[(long )button][(long )floorNum] == 1));
  __CrownApply1(132, 26, 5, (long long )(! (orderMatrix[(long )button][(long )floorNum] == 1)),
                (double )(! (orderMatrix[(long )button][(long )floorNum] == 1)));
#line 106
  if (! (orderMatrix[(long )button][(long )floorNum] == 1)) {
    __CrownBranch(136, 43, 1, __LINE__, __FILE__);
#line 106
    goto Node_7_375;
  } 
    #line 106
    else {
    __CrownBranch(137, 44, 0, __LINE__, __FILE__);

  }
  }
  __CrownLoad(138, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownStore(139, (unsigned long )(& __retres3));
#line 107
  __retres3 = 1;
#line 107
  goto return_label;
  Node_7_375: 
  __CrownLoad(142, (unsigned long )(& floorNum), 5, (long long )floorNum, (double )floorNum);
  __CrownLoad(141, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(140, 0, 5, (long long )(floorNum + 1), (double )(floorNum + 1));
  __CrownStore(143, (unsigned long )(& floorNum));
#line 109
  floorNum ++;
#line 110
  goto Node_7_369;
  Node_7_378: 
  __CrownLoad(146, (unsigned long )(& button), 5, (long long )button, (double )button);
  __CrownLoad(145, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(144, 0, 5, (long long )(button + 1), (double )(button + 1));
  __CrownStore(147, (unsigned long )(& button));
#line 112
  button ++;
#line 113
  goto Node_7_365;
  Node_7_382: ;
  __CrownLoad(148, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(149, (unsigned long )(& __retres3));
#line 115
  __retres3 = 0;
  return_label: /* CIL Label */ 
  {
  __CrownLoad(150, (unsigned long )(& __retres3), 5, (long long )__retres3, (double )__retres3);
  __CrownReturn(151);
#line 85
  return (__retres3);
  }
}
}
#line 120
int main(void) ;
#line 120 "target.c"
static int cnt_symbolic_var  =    1;
#line 121
int main(void) ;
#line 121 "target.c"
static int cnt_symbolic_var___0  =    1;
#line 122
int main(void) ;
#line 122 "target.c"
static int cnt_symbolic_var___1  =    1;
#line 123
int main(void) ;
#line 123 "target.c"
static int cnt_symbolic_var___2  =    1;
#line 124
int main(void) ;
#line 124 "target.c"
static int cnt_symbolic_var___3  =    1;
#line 125
int main(void) ;
#line 125 "target.c"
static int cnt_symbolic_var___4  =    1;
#line 126
int main(void) ;
#line 126 "target.c"
static int cnt_symbolic_var___5  =    1;
#line 127
int main(void) ;
#line 127 "target.c"
static int cnt_symbolic_var___6  =    1;
#line 128
int main(void) ;
#line 128 "target.c"
static int cnt_symbolic_var___7  =    1;
#line 129
int main(void) ;
#line 129 "target.c"
static int cnt_symbolic_var___8  =    1;
#line 130
int main(void) ;
#line 130 "target.c"
static int cnt_symbolic_var___9  =    1;
#line 131
int main(void) ;
#line 131 "target.c"
static int cnt_symbolic_var___10  =    1;
#line 117 "target.c"
int main(void) 
{ 
  int __iv__return_expr_isButtonPressed ;
  FILE *f ;
  FILE *tmp ;
  int __retres4 ;

  {
  __globinit_target();
  __CrownCheckSymbolic(154, "main");
  __CrownCall(153, 2);
  __CrownClearStack(152);
  __CrownLoad(155, (unsigned long )0, 6, (long long )((char    * __restrict  )"input:\n"),
              8);
  __CrownSetCallerCalleeName(156, "main", "printf");
#line 119
  printf((char    * __restrict  )"input:\n");
  __CrownEnableSymbolic(158, "main");
  __CrownClearStack(157);
  __CrownLoad(159, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(160, "main", "fflush");
#line 119
  fflush(stdout);
  __CrownEnableSymbolic(162, "main");
  __CrownClearStack(161);
#line 120
  __CrownInt(& orderMatrix[1][3], cnt_symbolic_var, 120, (char *)"target.c", "orderMatrix[1][3]");
  __CrownLoad(165, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
              (double )cnt_symbolic_var);
  __CrownLoad(164, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(163, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
  __CrownStore(166, (unsigned long )(& cnt_symbolic_var));
#line 120
  cnt_symbolic_var ++;
  __CrownLoad(167, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[1][3]=%d\n"),
              8);
  __CrownLoad(168, (unsigned long )(& orderMatrix[1][3]), 5, (long long )orderMatrix[1][3],
              (double )orderMatrix[1][3]);
  __CrownSetCallerCalleeName(169, "main", "printf");
#line 120
  printf((char    * __restrict  )"orderMatrix[1][3]=%d\n", orderMatrix[1][3]);
  __CrownEnableSymbolic(171, "main");
  __CrownClearStack(170);
  __CrownLoad(172, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(173, "main", "fflush");
#line 120
  fflush(stdout);
  __CrownEnableSymbolic(175, "main");
  __CrownClearStack(174);
#line 121
  __CrownInt(& orderMatrix[2][0], cnt_symbolic_var___0, 121, (char *)"target.c", "orderMatrix[2][0]");
  __CrownLoad(178, (unsigned long )(& cnt_symbolic_var___0), 5, (long long )cnt_symbolic_var___0,
              (double )cnt_symbolic_var___0);
  __CrownLoad(177, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(176, 0, 5, (long long )(cnt_symbolic_var___0 + 1), (double )(cnt_symbolic_var___0 + 1));
  __CrownStore(179, (unsigned long )(& cnt_symbolic_var___0));
#line 121
  cnt_symbolic_var___0 ++;
  __CrownLoad(180, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[2][0]=%d\n"),
              8);
  __CrownLoad(181, (unsigned long )(& orderMatrix[2][0]), 5, (long long )orderMatrix[2][0],
              (double )orderMatrix[2][0]);
  __CrownSetCallerCalleeName(182, "main", "printf");
#line 121
  printf((char    * __restrict  )"orderMatrix[2][0]=%d\n", orderMatrix[2][0]);
  __CrownEnableSymbolic(184, "main");
  __CrownClearStack(183);
  __CrownLoad(185, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(186, "main", "fflush");
#line 121
  fflush(stdout);
  __CrownEnableSymbolic(188, "main");
  __CrownClearStack(187);
#line 122
  __CrownInt(& orderMatrix[2][1], cnt_symbolic_var___1, 122, (char *)"target.c", "orderMatrix[2][1]");
  __CrownLoad(191, (unsigned long )(& cnt_symbolic_var___1), 5, (long long )cnt_symbolic_var___1,
              (double )cnt_symbolic_var___1);
  __CrownLoad(190, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(189, 0, 5, (long long )(cnt_symbolic_var___1 + 1), (double )(cnt_symbolic_var___1 + 1));
  __CrownStore(192, (unsigned long )(& cnt_symbolic_var___1));
#line 122
  cnt_symbolic_var___1 ++;
  __CrownLoad(193, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[2][1]=%d\n"),
              8);
  __CrownLoad(194, (unsigned long )(& orderMatrix[2][1]), 5, (long long )orderMatrix[2][1],
              (double )orderMatrix[2][1]);
  __CrownSetCallerCalleeName(195, "main", "printf");
#line 122
  printf((char    * __restrict  )"orderMatrix[2][1]=%d\n", orderMatrix[2][1]);
  __CrownEnableSymbolic(197, "main");
  __CrownClearStack(196);
  __CrownLoad(198, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(199, "main", "fflush");
#line 122
  fflush(stdout);
  __CrownEnableSymbolic(201, "main");
  __CrownClearStack(200);
#line 123
  __CrownInt(& orderMatrix[2][2], cnt_symbolic_var___2, 123, (char *)"target.c", "orderMatrix[2][2]");
  __CrownLoad(204, (unsigned long )(& cnt_symbolic_var___2), 5, (long long )cnt_symbolic_var___2,
              (double )cnt_symbolic_var___2);
  __CrownLoad(203, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(202, 0, 5, (long long )(cnt_symbolic_var___2 + 1), (double )(cnt_symbolic_var___2 + 1));
  __CrownStore(205, (unsigned long )(& cnt_symbolic_var___2));
#line 123
  cnt_symbolic_var___2 ++;
  __CrownLoad(206, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[2][2]=%d\n"),
              8);
  __CrownLoad(207, (unsigned long )(& orderMatrix[2][2]), 5, (long long )orderMatrix[2][2],
              (double )orderMatrix[2][2]);
  __CrownSetCallerCalleeName(208, "main", "printf");
#line 123
  printf((char    * __restrict  )"orderMatrix[2][2]=%d\n", orderMatrix[2][2]);
  __CrownEnableSymbolic(210, "main");
  __CrownClearStack(209);
  __CrownLoad(211, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(212, "main", "fflush");
#line 123
  fflush(stdout);
  __CrownEnableSymbolic(214, "main");
  __CrownClearStack(213);
#line 124
  __CrownInt(& orderMatrix[2][3], cnt_symbolic_var___3, 124, (char *)"target.c", "orderMatrix[2][3]");
  __CrownLoad(217, (unsigned long )(& cnt_symbolic_var___3), 5, (long long )cnt_symbolic_var___3,
              (double )cnt_symbolic_var___3);
  __CrownLoad(216, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(215, 0, 5, (long long )(cnt_symbolic_var___3 + 1), (double )(cnt_symbolic_var___3 + 1));
  __CrownStore(218, (unsigned long )(& cnt_symbolic_var___3));
#line 124
  cnt_symbolic_var___3 ++;
  __CrownLoad(219, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[2][3]=%d\n"),
              8);
  __CrownLoad(220, (unsigned long )(& orderMatrix[2][3]), 5, (long long )orderMatrix[2][3],
              (double )orderMatrix[2][3]);
  __CrownSetCallerCalleeName(221, "main", "printf");
#line 124
  printf((char    * __restrict  )"orderMatrix[2][3]=%d\n", orderMatrix[2][3]);
  __CrownEnableSymbolic(223, "main");
  __CrownClearStack(222);
  __CrownLoad(224, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(225, "main", "fflush");
#line 124
  fflush(stdout);
  __CrownEnableSymbolic(227, "main");
  __CrownClearStack(226);
#line 125
  __CrownInt(& orderMatrix[0][0], cnt_symbolic_var___4, 125, (char *)"target.c", "orderMatrix[0][0]");
  __CrownLoad(230, (unsigned long )(& cnt_symbolic_var___4), 5, (long long )cnt_symbolic_var___4,
              (double )cnt_symbolic_var___4);
  __CrownLoad(229, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(228, 0, 5, (long long )(cnt_symbolic_var___4 + 1), (double )(cnt_symbolic_var___4 + 1));
  __CrownStore(231, (unsigned long )(& cnt_symbolic_var___4));
#line 125
  cnt_symbolic_var___4 ++;
  __CrownLoad(232, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[0][0]=%d\n"),
              8);
  __CrownLoad(233, (unsigned long )(& orderMatrix[0][0]), 5, (long long )orderMatrix[0][0],
              (double )orderMatrix[0][0]);
  __CrownSetCallerCalleeName(234, "main", "printf");
#line 125
  printf((char    * __restrict  )"orderMatrix[0][0]=%d\n", orderMatrix[0][0]);
  __CrownEnableSymbolic(236, "main");
  __CrownClearStack(235);
  __CrownLoad(237, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(238, "main", "fflush");
#line 125
  fflush(stdout);
  __CrownEnableSymbolic(240, "main");
  __CrownClearStack(239);
#line 126
  __CrownInt(& orderMatrix[0][1], cnt_symbolic_var___5, 126, (char *)"target.c", "orderMatrix[0][1]");
  __CrownLoad(243, (unsigned long )(& cnt_symbolic_var___5), 5, (long long )cnt_symbolic_var___5,
              (double )cnt_symbolic_var___5);
  __CrownLoad(242, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(241, 0, 5, (long long )(cnt_symbolic_var___5 + 1), (double )(cnt_symbolic_var___5 + 1));
  __CrownStore(244, (unsigned long )(& cnt_symbolic_var___5));
#line 126
  cnt_symbolic_var___5 ++;
  __CrownLoad(245, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[0][1]=%d\n"),
              8);
  __CrownLoad(246, (unsigned long )(& orderMatrix[0][1]), 5, (long long )orderMatrix[0][1],
              (double )orderMatrix[0][1]);
  __CrownSetCallerCalleeName(247, "main", "printf");
#line 126
  printf((char    * __restrict  )"orderMatrix[0][1]=%d\n", orderMatrix[0][1]);
  __CrownEnableSymbolic(249, "main");
  __CrownClearStack(248);
  __CrownLoad(250, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(251, "main", "fflush");
#line 126
  fflush(stdout);
  __CrownEnableSymbolic(253, "main");
  __CrownClearStack(252);
#line 127
  __CrownInt(& orderMatrix[0][2], cnt_symbolic_var___6, 127, (char *)"target.c", "orderMatrix[0][2]");
  __CrownLoad(256, (unsigned long )(& cnt_symbolic_var___6), 5, (long long )cnt_symbolic_var___6,
              (double )cnt_symbolic_var___6);
  __CrownLoad(255, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(254, 0, 5, (long long )(cnt_symbolic_var___6 + 1), (double )(cnt_symbolic_var___6 + 1));
  __CrownStore(257, (unsigned long )(& cnt_symbolic_var___6));
#line 127
  cnt_symbolic_var___6 ++;
  __CrownLoad(258, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[0][2]=%d\n"),
              8);
  __CrownLoad(259, (unsigned long )(& orderMatrix[0][2]), 5, (long long )orderMatrix[0][2],
              (double )orderMatrix[0][2]);
  __CrownSetCallerCalleeName(260, "main", "printf");
#line 127
  printf((char    * __restrict  )"orderMatrix[0][2]=%d\n", orderMatrix[0][2]);
  __CrownEnableSymbolic(262, "main");
  __CrownClearStack(261);
  __CrownLoad(263, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(264, "main", "fflush");
#line 127
  fflush(stdout);
  __CrownEnableSymbolic(266, "main");
  __CrownClearStack(265);
#line 128
  __CrownInt(& orderMatrix[0][3], cnt_symbolic_var___7, 128, (char *)"target.c", "orderMatrix[0][3]");
  __CrownLoad(269, (unsigned long )(& cnt_symbolic_var___7), 5, (long long )cnt_symbolic_var___7,
              (double )cnt_symbolic_var___7);
  __CrownLoad(268, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(267, 0, 5, (long long )(cnt_symbolic_var___7 + 1), (double )(cnt_symbolic_var___7 + 1));
  __CrownStore(270, (unsigned long )(& cnt_symbolic_var___7));
#line 128
  cnt_symbolic_var___7 ++;
  __CrownLoad(271, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[0][3]=%d\n"),
              8);
  __CrownLoad(272, (unsigned long )(& orderMatrix[0][3]), 5, (long long )orderMatrix[0][3],
              (double )orderMatrix[0][3]);
  __CrownSetCallerCalleeName(273, "main", "printf");
#line 128
  printf((char    * __restrict  )"orderMatrix[0][3]=%d\n", orderMatrix[0][3]);
  __CrownEnableSymbolic(275, "main");
  __CrownClearStack(274);
  __CrownLoad(276, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(277, "main", "fflush");
#line 128
  fflush(stdout);
  __CrownEnableSymbolic(279, "main");
  __CrownClearStack(278);
#line 129
  __CrownInt(& orderMatrix[1][0], cnt_symbolic_var___8, 129, (char *)"target.c", "orderMatrix[1][0]");
  __CrownLoad(282, (unsigned long )(& cnt_symbolic_var___8), 5, (long long )cnt_symbolic_var___8,
              (double )cnt_symbolic_var___8);
  __CrownLoad(281, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(280, 0, 5, (long long )(cnt_symbolic_var___8 + 1), (double )(cnt_symbolic_var___8 + 1));
  __CrownStore(283, (unsigned long )(& cnt_symbolic_var___8));
#line 129
  cnt_symbolic_var___8 ++;
  __CrownLoad(284, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[1][0]=%d\n"),
              8);
  __CrownLoad(285, (unsigned long )(& orderMatrix[1][0]), 5, (long long )orderMatrix[1][0],
              (double )orderMatrix[1][0]);
  __CrownSetCallerCalleeName(286, "main", "printf");
#line 129
  printf((char    * __restrict  )"orderMatrix[1][0]=%d\n", orderMatrix[1][0]);
  __CrownEnableSymbolic(288, "main");
  __CrownClearStack(287);
  __CrownLoad(289, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(290, "main", "fflush");
#line 129
  fflush(stdout);
  __CrownEnableSymbolic(292, "main");
  __CrownClearStack(291);
#line 130
  __CrownInt(& orderMatrix[1][1], cnt_symbolic_var___9, 130, (char *)"target.c", "orderMatrix[1][1]");
  __CrownLoad(295, (unsigned long )(& cnt_symbolic_var___9), 5, (long long )cnt_symbolic_var___9,
              (double )cnt_symbolic_var___9);
  __CrownLoad(294, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(293, 0, 5, (long long )(cnt_symbolic_var___9 + 1), (double )(cnt_symbolic_var___9 + 1));
  __CrownStore(296, (unsigned long )(& cnt_symbolic_var___9));
#line 130
  cnt_symbolic_var___9 ++;
  __CrownLoad(297, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[1][1]=%d\n"),
              8);
  __CrownLoad(298, (unsigned long )(& orderMatrix[1][1]), 5, (long long )orderMatrix[1][1],
              (double )orderMatrix[1][1]);
  __CrownSetCallerCalleeName(299, "main", "printf");
#line 130
  printf((char    * __restrict  )"orderMatrix[1][1]=%d\n", orderMatrix[1][1]);
  __CrownEnableSymbolic(301, "main");
  __CrownClearStack(300);
  __CrownLoad(302, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(303, "main", "fflush");
#line 130
  fflush(stdout);
  __CrownEnableSymbolic(305, "main");
  __CrownClearStack(304);
#line 131
  __CrownInt(& orderMatrix[1][2], cnt_symbolic_var___10, 131, (char *)"target.c",
             "orderMatrix[1][2]");
  __CrownLoad(308, (unsigned long )(& cnt_symbolic_var___10), 5, (long long )cnt_symbolic_var___10,
              (double )cnt_symbolic_var___10);
  __CrownLoad(307, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(306, 0, 5, (long long )(cnt_symbolic_var___10 + 1), (double )(cnt_symbolic_var___10 + 1));
  __CrownStore(309, (unsigned long )(& cnt_symbolic_var___10));
#line 131
  cnt_symbolic_var___10 ++;
  __CrownLoad(310, (unsigned long )0, 6, (long long )((char    * __restrict  )"orderMatrix[1][2]=%d\n"),
              8);
  __CrownLoad(311, (unsigned long )(& orderMatrix[1][2]), 5, (long long )orderMatrix[1][2],
              (double )orderMatrix[1][2]);
  __CrownSetCallerCalleeName(312, "main", "printf");
#line 131
  printf((char    * __restrict  )"orderMatrix[1][2]=%d\n", orderMatrix[1][2]);
  __CrownEnableSymbolic(314, "main");
  __CrownClearStack(313);
  __CrownLoad(315, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(316, "main", "fflush");
#line 131
  fflush(stdout);
  __CrownEnableSymbolic(318, "main");
  __CrownClearStack(317);
  __CrownLoad(319, (unsigned long )0, 6, (long long )((char    * __restrict  )"path:\n"),
              8);
  __CrownSetCallerCalleeName(320, "main", "printf");
#line 132
  printf((char    * __restrict  )"path:\n");
  __CrownEnableSymbolic(322, "main");
  __CrownClearStack(321);
  __CrownLoad(323, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(324, "main", "fflush");
#line 132
  fflush(stdout);
  __CrownEnableSymbolic(326, "main");
  __CrownClearStack(325);
  __CrownSetCallerCalleeName(327, "main", "isButtonPressed");
#line 133
  __iv__return_expr_isButtonPressed = isButtonPressed();
  __CrownEnableSymbolic(330, "main");
  __CrownHandleReturn(329, 5, (long long )__iv__return_expr_isButtonPressed, (double )__iv__return_expr_isButtonPressed);
  __CrownStore(328, (unsigned long )(& __iv__return_expr_isButtonPressed));
#line 134
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrownLoad(334, (unsigned long )(& __iv__max_path), 5, (long long )__iv__max_path,
                (double )__iv__max_path);
    __CrownLoad(333, (unsigned long )0, 5, (long long )10000, (double )10000);
    __CrownApply2(332, 20, 5, (long long )(__iv__max_path < 10000), (double )(__iv__max_path < 10000));
    __CrownApply1(331, 26, 5, (long long )(! (__iv__max_path < 10000)), (double )(! (__iv__max_path < 10000)));
#line 134
    if (! (__iv__max_path < 10000)) {
      __CrownBranch(335, 59, 1, __LINE__, __FILE__);
      __CrownLoad(338, (unsigned long )(& stderr), 6, (long long )stderr, 8);
      __CrownApply1(337, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
      __CrownLoad(339, (unsigned long )0, 6, (long long )((char    * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n"),
                  8);
      __CrownLoad(340, (unsigned long )0, 6, (long long )"__iv__max_path < 10000",
                  8);
      __CrownLoad(341, (unsigned long )0, 5, (long long )134, (double )134);
      __CrownLoad(342, (unsigned long )0, 6, (long long )"main", 8);
      __CrownLoad(343, (unsigned long )0, 6, (long long )"target.c", 8);
      __CrownSetCallerCalleeName(344, "main", "fprintf");
#line 134
      fprintf((FILE * __restrict  )stderr, (char    * __restrict  )"### SYM_assume(%s) is violated at Line %d (%s in %s) ###\n",
              "__iv__max_path < 10000", 134, "main", "target.c");
      __CrownEnableSymbolic(346, "main");
      __CrownClearStack(345);
      __CrownLoad(347, (unsigned long )0, 6, (long long )((char    * __restrict  )"__SYM_assume_violated"),
                  8);
      __CrownLoad(348, (unsigned long )0, 6, (long long )((char    * __restrict  )"w"),
                  8);
      __CrownSetCallerCalleeName(349, "main", "fopen");
#line 134
      tmp = fopen((char    * __restrict  )"__SYM_assume_violated", (char    * __restrict  )"w");
      __CrownEnableSymbolic(352, "main");
      __CrownHandleReturn(351, 6, (long long )tmp, 8);
      __CrownStore(350, (unsigned long )(& tmp));
      __CrownLoad(353, (unsigned long )(& tmp), 6, (long long )tmp, 8);
      __CrownStore(354, (unsigned long )(& f));
#line 134
      f = tmp;
      {
      __CrownLoad(356, (unsigned long )(& f), 6, (long long )f, 8);
      __CrownApply1(355, 26, 5, (long long )(! f), (double )(! f));
#line 134
      if (! f) {
        __CrownBranch(357, 61, 1, __LINE__, __FILE__);
        __CrownLoad(360, (unsigned long )(& stderr), 6, (long long )stderr, 8);
        __CrownApply1(359, 27, 6, (long long )((FILE * __restrict  )stderr), 8);
        __CrownLoad(361, (unsigned long )0, 6, (long long )((char    * __restrict  )"### %s file cannot be created ###\n"),
                    8);
        __CrownLoad(362, (unsigned long )0, 6, (long long )"__SYM_assume_violated",
                    8);
        __CrownSetCallerCalleeName(363, "main", "fprintf");
#line 134
        fprintf((FILE * __restrict  )stderr, (char    * __restrict  )"### %s file cannot be created ###\n",
                "__SYM_assume_violated");
        __CrownEnableSymbolic(365, "main");
        __CrownClearStack(364);
      } 
        #line 134
        else {
        __CrownBranch(358, 62, 0, __LINE__, __FILE__);
        __CrownLoad(366, (unsigned long )(& f), 6, (long long )f, 8);
        __CrownSetCallerCalleeName(367, "main", "fclose");
#line 134
        fclose(f);
        __CrownEnableSymbolic(369, "main");
        __CrownClearStack(368);
      }
      }
      __CrownLoad(370, (unsigned long )0, 5, (long long )1, (double )1);
      __CrownSetCallerCalleeName(371, "main", "exit");
#line 134
      exit(1);
      __CrownEnableSymbolic(373, "main");
      __CrownClearStack(372);
    } 
      #line 134
      else {
      __CrownBranch(336, 64, 0, __LINE__, __FILE__);

    }
    }
#line 134
    goto while_break;
  }
  while_break: /* CIL Label */ 
  __CrownLoad(374, (unsigned long )0, 6, (long long )((char    * __restrict  )"output:\n"),
              8);
  __CrownSetCallerCalleeName(375, "main", "printf");
#line 135
  printf((char    * __restrict  )"output:\n");
  __CrownEnableSymbolic(377, "main");
  __CrownClearStack(376);
  __CrownLoad(378, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(379, "main", "fflush");
#line 135
  fflush(stdout);
  __CrownEnableSymbolic(381, "main");
  __CrownClearStack(380);
  __CrownLoad(382, (unsigned long )0, 6, (long long )((char    * __restrict  )"__iv__return_expr_isButtonPressed=%d\n"),
              8);
  __CrownLoad(383, (unsigned long )(& __iv__return_expr_isButtonPressed), 5, (long long )__iv__return_expr_isButtonPressed,
              (double )__iv__return_expr_isButtonPressed);
  __CrownSetCallerCalleeName(384, "main", "printf");
#line 136
  printf((char    * __restrict  )"__iv__return_expr_isButtonPressed=%d\n", __iv__return_expr_isButtonPressed);
  __CrownEnableSymbolic(386, "main");
  __CrownClearStack(385);
  __CrownLoad(387, (unsigned long )(& stdout), 6, (long long )stdout, 8);
  __CrownSetCallerCalleeName(388, "main", "fflush");
#line 136
  fflush(stdout);
  __CrownEnableSymbolic(390, "main");
  __CrownClearStack(389);
  __CrownLoad(391, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(392, (unsigned long )(& __retres4));
#line 137
  __retres4 = 0;
  __CrownLoad(393, (unsigned long )(& __retres4), 5, (long long )__retres4, (double )__retres4);
  __CrownReturn(394);
#line 117
  return (__retres4);
}
}
void __globinit_target(void) 
{ 


  {
  __CrownInit(395);
}
}
