#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#define __CPROVER_assume(a) if (!(a)) exit(0)
typedef _Bool __CPROVER_bool;
FILE *__iv__fp;
#include <assert.h>
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
enum FSM { STANDBY=0, SCAN_PRIMARY=1, SCAN_SECONDARY=2, DRIVE_PATROL=3, DRIVE_TO_BEACON_FAST=4, DRIVE_TO_BEACON_SLOW=5, DRIVE_TO_WALL=6, TARGET_ACQUIRING=7, TARGET_DISPOSING=8, SIGNAL_COMPLETION=9 };
typedef enum FSM State;
signed int SensorValue(signed int sensor);
State acquireTarget();
void backUp();
void check_property();
void clearTimer(signed int t1);
State closeRangeApproach();
State disposeOfTarget();
State findAWall();
void initialize();
State longRangeApproach();
signed int medianFilter();
State onPatrol();
State primaryScan();
State secondaryScan();
State standingBy();
void stopWheels();
State taskComplete();
signed int time1(signed int t1);
void turnAround();
void update_prop_automata();
void wait1Msec(signed int sec);
signed int IRMax=0;
signed int ambientIR=5000;
signed int brobot_max_loss;
signed int __VERIFIER_nondet_signed_int(){ signed int __iv_temp; if (-1 == fscanf(__iv__fp, "%d", &__iv_temp)) exit(0); return __iv_temp; }
signed int brobot_signal_loss;
signed int isAllReached=0;
State machineState=/*enum*/STANDBY;
float motor[4l];
signed int reachedStates[10l]={ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
signed int sonarMax=0;
__CPROVER_bool __iv__branch_expr;
int __iv__return_expr_main;
State __iv__return_expr_standingBy;
State __iv__return_expr_secondaryScan;
signed int __iv__return_expr_medianFilter;
State __iv__return_expr_closeRangeApproach;
State __iv__return_expr_longRangeApproach;
signed int __iv__return_expr_SensorValue;
State __iv__return_expr_findAWall;
State __iv__return_expr_disposeOfTarget;
State __iv__return_expr_onPatrol;
State __iv__return_expr_primaryScan;
signed int __iv__return_expr_time1;
State __iv__return_expr_acquireTarget;
State __iv__return_expr_taskComplete;
signed int __iv__medianFilter_stub();
int medianFilter_stub_index;
signed int medianFilter___iv__return_expr_medianFilter_list[] = {602, 32769, 602, 1, 513, 138};
int main(int argc, char* argv[]) {
	__iv__fp = fopen(argv[1], "r");
	printf("_tr_call:initialize;_tr_call_id:0;\n");fflush(stdout);
	initialize();
	Node_0_1:;
	__iv__branch_expr = !((1 != 0));
	printf("_tr_node_id:Node_0_1;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((1 != 0))) goto Node_0_39;
	__iv__branch_expr = ((signed int)(machineState) == 0);
	printf("_tr_node_id:Node_0_3;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 0)) goto Node_0_14;
	__iv__branch_expr = ((signed int)(machineState) == 1);
	printf("_tr_node_id:Node_0_4;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 1)) goto Node_0_16;
	__iv__branch_expr = ((signed int)(machineState) == 2);
	printf("_tr_node_id:Node_0_5;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 2)) goto Node_0_18;
	__iv__branch_expr = ((signed int)(machineState) == 3);
	printf("_tr_node_id:Node_0_6;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 3)) goto Node_0_20;
	__iv__branch_expr = ((signed int)(machineState) == 4);
	printf("_tr_node_id:Node_0_7;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 4)) goto Node_0_22;
	__iv__branch_expr = ((signed int)(machineState) == 5);
	printf("_tr_node_id:Node_0_8;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 5)) goto Node_0_24;
	__iv__branch_expr = ((signed int)(machineState) == 7);
	printf("_tr_node_id:Node_0_9;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 7)) goto Node_0_26;
	__iv__branch_expr = ((signed int)(machineState) == 6);
	printf("_tr_node_id:Node_0_10;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 6)) goto Node_0_28;
	__iv__branch_expr = ((signed int)(machineState) == 8);
	printf("_tr_node_id:Node_0_11;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 8)) goto Node_0_30;
	__iv__branch_expr = ((signed int)(machineState) == 9);
	printf("_tr_node_id:Node_0_12;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 9)) goto Node_0_32;
	goto Node_0_34;
	Node_0_14:;
	printf("_tr_call:standingBy;_tr_call_id:1;\n");fflush(stdout);
		machineState = standingBy();
	printf("_tr_node_id:Node_0_14;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_16:;
	printf("_tr_call:primaryScan;_tr_call_id:2;\n");fflush(stdout);
		machineState = primaryScan();
	printf("_tr_node_id:Node_0_16;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_18:;
	printf("_tr_call:secondaryScan;_tr_call_id:3;\n");fflush(stdout);
		machineState = secondaryScan();
	printf("_tr_node_id:Node_0_18;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_20:;
	printf("_tr_call:onPatrol;_tr_call_id:4;\n");fflush(stdout);
		machineState = onPatrol();
	printf("_tr_node_id:Node_0_20;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_22:;
	printf("_tr_call:longRangeApproach;_tr_call_id:5;\n");fflush(stdout);
		machineState = longRangeApproach();
	printf("_tr_node_id:Node_0_22;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_24:;
	printf("_tr_call:closeRangeApproach;_tr_call_id:6;\n");fflush(stdout);
		machineState = closeRangeApproach();
	printf("_tr_node_id:Node_0_24;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_26:;
	printf("_tr_call:acquireTarget;_tr_call_id:7;\n");fflush(stdout);
		machineState = acquireTarget();
	printf("_tr_node_id:Node_0_26;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_28:;
	printf("_tr_call:findAWall;_tr_call_id:8;\n");fflush(stdout);
		machineState = findAWall();
	printf("_tr_node_id:Node_0_28;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_30:;
	printf("_tr_call:disposeOfTarget;_tr_call_id:9;\n");fflush(stdout);
		machineState = disposeOfTarget();
	printf("_tr_node_id:Node_0_30;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_32:;
	printf("_tr_call:taskComplete;_tr_call_id:10;\n");fflush(stdout);
		machineState = taskComplete();
	printf("_tr_node_id:Node_0_32;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_34:;
	Node_0_35:;
	printf("_tr_call:update_prop_automata;_tr_call_id:11;\n");fflush(stdout);
	update_prop_automata();
	printf("_tr_call:check_property;_tr_call_id:12;\n");fflush(stdout);
	check_property();
	goto Node_0_1;
	Node_0_39:;
	printf("_tr_return;\n");fflush(stdout);
}
State standingBy() {
	printf("_tr_call:stopWheels;_tr_call_id:14;\n");fflush(stdout);
	stopWheels();
	printf("_tr_node_id:Node_1_43;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:15;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 3);fflush(stdout);
		return_value_SensorValue = SensorValue(3);
	printf("_tr_node_id:Node_1_45;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue == 0);
	printf("_tr_node_id:Node_1_47;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue == 0)) goto Node_1_53;
	__iv__return_expr_standingBy = 	(State)(1);
	printf("_tr_node_id:Node_1_48;_tr_assign:__iv__return_expr_standingBy=%d;\n", __iv__return_expr_standingBy);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_standingBy;
	Node_1_53:;
	__iv__return_expr_standingBy = 	(State)(0);
	printf("_tr_node_id:Node_1_53;_tr_assign:__iv__return_expr_standingBy=%d;\n", __iv__return_expr_standingBy);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_standingBy;
}
State secondaryScan() {
		IRMax = 0;
	printf("_tr_node_id:Node_2_62;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:16;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_2_64;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_2_65:;
	printf("_tr_call:time1;_tr_call_id:17;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_2_65;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 3000);
	printf("_tr_node_id:Node_2_66;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 3000)) goto Node_2_81;
	printf("_tr_node_id:Node_2_69;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:18;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_2_71;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (IRMax >= return_value_SensorValue);
	printf("_tr_node_id:Node_2_73;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((IRMax >= return_value_SensorValue)) goto Node_2_75;
	printf("_tr_call:SensorValue;_tr_call_id:19;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_2_74;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_2_75:;
	unsigned int __iv__index_expr_var0 = (unsigned) (0);
		motor[0] = (float)((25.0 * 1.3));
	printf("_tr_node_id:Node_2_76;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var0, motor[__iv__index_expr_var0]);fflush(stdout);
	unsigned int __iv__index_expr_var1 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_2_77;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var1, motor[__iv__index_expr_var1]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_2_80;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_2_65;
	Node_2_81:;
	printf("_tr_call:stopWheels;_tr_call_id:20;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:21;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	printf("_tr_call:clearTimer;_tr_call_id:22;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_2_85;_tr_decl:return_value_time1_0;\n");fflush(stdout);
	signed int return_value_time1_0;
	Node_2_86:;
	printf("_tr_call:time1;_tr_call_id:23;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_0 = time1(0);
	printf("_tr_node_id:Node_2_86;_tr_assign:return_value_time1_0=%d;\n", return_value_time1_0);fflush(stdout);
	__iv__branch_expr = (return_value_time1_0 >= 6000);
	printf("_tr_node_id:Node_2_87;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_0 >= 6000)) goto Node_2_102;
	printf("_tr_node_id:Node_2_90;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:24;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(2);
	printf("_tr_node_id:Node_2_92;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = !((return_value_SensorValue_0 >= IRMax));
	printf("_tr_node_id:Node_2_94;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_SensorValue_0 >= IRMax))) goto Node_2_96;
	printf("_tr_call:SensorValue;_tr_call_id:25;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_2_95;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_2_96:;
	unsigned int __iv__index_expr_var2 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_2_97;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var2, motor[__iv__index_expr_var2]);fflush(stdout);
	unsigned int __iv__index_expr_var3 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_2_98;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var3, motor[__iv__index_expr_var3]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_2_101;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_2_86;
	Node_2_102:;
	printf("_tr_call:stopWheels;_tr_call_id:26;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:27;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	printf("_tr_call:clearTimer;_tr_call_id:28;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_2_106;_tr_decl:return_value_time1_1;\n");fflush(stdout);
	signed int return_value_time1_1;
	Node_2_107:;
	printf("_tr_call:time1;_tr_call_id:29;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_1 = time1(0);
	printf("_tr_node_id:Node_2_107;_tr_assign:return_value_time1_1=%d;\n", return_value_time1_1);fflush(stdout);
	__iv__branch_expr = (return_value_time1_1 >= 6000);
	printf("_tr_node_id:Node_2_108;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_1 >= 6000)) goto Node_2_132;
	printf("_tr_node_id:Node_2_111;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	printf("_tr_call:SensorValue;_tr_call_id:30;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(2);
	printf("_tr_node_id:Node_2_113;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
	__iv__branch_expr = ((IRMax + -20) >= return_value_SensorValue_1);
	printf("_tr_node_id:Node_2_115;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((IRMax + -20) >= return_value_SensorValue_1)) goto Node_2_124;
	printf("_tr_call:stopWheels;_tr_call_id:31;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_secondaryScan = 	(State)(5);
	printf("_tr_node_id:Node_2_117;_tr_assign:__iv__return_expr_secondaryScan=%d;\n", __iv__return_expr_secondaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_secondaryScan;
	Node_2_124:;
	unsigned int __iv__index_expr_var4 = (unsigned) (0);
		motor[0] = (float)((25.0 * 1.3));
	printf("_tr_node_id:Node_2_125;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var4, motor[__iv__index_expr_var4]);fflush(stdout);
	unsigned int __iv__index_expr_var5 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_2_126;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var5, motor[__iv__index_expr_var5]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_2_127;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:32;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_2_131;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_2_107;
	Node_2_132:;
	printf("_tr_call:stopWheels;_tr_call_id:33;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_secondaryScan = 	(State)(3);
	printf("_tr_node_id:Node_2_134;_tr_assign:__iv__return_expr_secondaryScan=%d;\n", __iv__return_expr_secondaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_secondaryScan;
}
signed int medianFilter() {
	printf("_tr_node_id:Node_3_140;_tr_decl:first;\n");fflush(stdout);
	signed int first;
		first = 0;
	printf("_tr_node_id:Node_3_141;_tr_assign:first=%d;\n", first);fflush(stdout);
	printf("_tr_node_id:Node_3_142;_tr_decl:second;\n");fflush(stdout);
	signed int second;
		second = 0;
	printf("_tr_node_id:Node_3_143;_tr_assign:second=%d;\n", second);fflush(stdout);
	printf("_tr_node_id:Node_3_144;_tr_decl:third;\n");fflush(stdout);
	signed int third;
		third = 0;
	printf("_tr_node_id:Node_3_145;_tr_assign:third=%d;\n", third);fflush(stdout);
	printf("_tr_call:SensorValue;_tr_call_id:34;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		first = SensorValue(1);
	printf("_tr_node_id:Node_3_146;_tr_assign:first=%d;\n", first);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:35;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	printf("_tr_call:SensorValue;_tr_call_id:36;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		second = SensorValue(1);
	printf("_tr_node_id:Node_3_148;_tr_assign:second=%d;\n", second);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:37;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	printf("_tr_call:SensorValue;_tr_call_id:38;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		third = SensorValue(1);
	printf("_tr_node_id:Node_3_150;_tr_assign:third=%d;\n", third);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:39;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	__iv__branch_expr = !((((first >= second) && (third >= first)) || ((second >= first) && (first >= third))));
	printf("_tr_node_id:Node_3_152;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((((first >= second) && (third >= first)) || ((second >= first) && (first >= third))))) goto Node_3_159;
	__iv__return_expr_medianFilter = 	first;
	printf("_tr_node_id:Node_3_153;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
	Node_3_159:;
	__iv__branch_expr = !((((second >= first) && (third >= second)) || ((first >= second) && (second >= third))));
	printf("_tr_node_id:Node_3_159;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((((second >= first) && (third >= second)) || ((first >= second) && (second >= third))))) goto Node_3_166;
	__iv__return_expr_medianFilter = 	second;
	printf("_tr_node_id:Node_3_160;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
	Node_3_166:;
	__iv__return_expr_medianFilter = 	third;
	printf("_tr_node_id:Node_3_166;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
}
State closeRangeApproach() {
	printf("_tr_node_id:Node_4_178;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_node_id:Node_4_179;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_node_id:Node_4_180;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	Node_4_181:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:40;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_4_181;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter >= 141));
	printf("_tr_node_id:Node_4_182;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter >= 141))) goto Node_4_220;
	printf("_tr_call:SensorValue;_tr_call_id:41;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_4_185;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 20) >= return_value_SensorValue);
	printf("_tr_node_id:Node_4_186;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 20) >= return_value_SensorValue)) goto Node_4_220;
	unsigned int __iv__index_expr_var6 = (unsigned) (0);
		motor[0] = (float)((20.0 * 1.3));
	printf("_tr_node_id:Node_4_189;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var6, motor[__iv__index_expr_var6]);fflush(stdout);
	unsigned int __iv__index_expr_var7 = (unsigned) (1);
		motor[1] = 20.0f;
	printf("_tr_node_id:Node_4_190;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var7, motor[__iv__index_expr_var7]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_4_191;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:42;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	printf("_tr_node_id:Node_4_193;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:43;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(4);
	printf("_tr_node_id:Node_4_196;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	printf("_tr_node_id:Node_4_197;_tr_decl:tmp_if_expr;\n");fflush(stdout);
	__CPROVER_bool tmp_if_expr;
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_4_198;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_4_201;
		tmp_if_expr = (1 != 0);
	printf("_tr_node_id:Node_4_199;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	goto Node_4_203;
	Node_4_201:;
	printf("_tr_call:SensorValue;_tr_call_id:44;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(5);
	printf("_tr_node_id:Node_4_201;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
		tmp_if_expr = ((return_value_SensorValue_1 != 0) ? 1 : 0 != 0);
	printf("_tr_node_id:Node_4_202;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	Node_4_203:;
	__iv__branch_expr = !tmp_if_expr;
	printf("_tr_node_id:Node_4_204;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!tmp_if_expr) goto Node_4_215;
	printf("_tr_call:backUp;_tr_call_id:45;\n");fflush(stdout);
	backUp();
	printf("_tr_call:stopWheels;_tr_call_id:46;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_closeRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_4_207;_tr_assign:__iv__return_expr_closeRangeApproach=%d;\n", __iv__return_expr_closeRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_closeRangeApproach;
	Node_4_215:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_4_219;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_4_181;
	Node_4_220:;
	__iv__return_expr_closeRangeApproach = 	(State)(7);
	printf("_tr_node_id:Node_4_221;_tr_assign:__iv__return_expr_closeRangeApproach=%d;\n", __iv__return_expr_closeRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_closeRangeApproach;
}
void initialize() {
		brobot_max_loss = 5;
	printf("_tr_node_id:Node_5_227;_tr_assign:brobot_max_loss=%d;\n", brobot_max_loss);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
State longRangeApproach() {
	printf("_tr_node_id:Node_6_229;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:47;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_6_231;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	printf("_tr_node_id:Node_6_233;_tr_decl:return_value_medianFilter_0;\n");fflush(stdout);
	signed int return_value_medianFilter_0;
	printf("_tr_node_id:Node_6_234;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_node_id:Node_6_235;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	__iv__branch_expr = (return_value_medianFilter >= 601);
	printf("_tr_node_id:Node_6_236;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_medianFilter >= 601)) goto Node_6_245;
	__iv__return_expr_longRangeApproach = 	(State)(5);
	printf("_tr_node_id:Node_6_237;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
	Node_6_245:;
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_6_245;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:48;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	Node_6_247:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:49;\n");fflush(stdout);
		return_value_medianFilter_0 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_6_247;_tr_assign:return_value_medianFilter_0=%d;\n", return_value_medianFilter_0);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_0 >= 601));
	printf("_tr_node_id:Node_6_248;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_0 >= 601))) goto Node_6_288;
	printf("_tr_call:SensorValue;_tr_call_id:50;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_6_251;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 50) >= return_value_SensorValue);
	printf("_tr_node_id:Node_6_252;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 50) >= return_value_SensorValue)) goto Node_6_288;
	unsigned int __iv__index_expr_var8 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_6_255;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var8, motor[__iv__index_expr_var8]);fflush(stdout);
	unsigned int __iv__index_expr_var9 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_6_256;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var9, motor[__iv__index_expr_var9]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_6_257;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:51;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	printf("_tr_node_id:Node_6_259;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:52;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(4);
	printf("_tr_node_id:Node_6_262;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	printf("_tr_node_id:Node_6_263;_tr_decl:tmp_if_expr;\n");fflush(stdout);
	__CPROVER_bool tmp_if_expr;
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_6_264;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_6_267;
		tmp_if_expr = (1 != 0);
	printf("_tr_node_id:Node_6_265;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	goto Node_6_269;
	Node_6_267:;
	printf("_tr_call:SensorValue;_tr_call_id:53;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(5);
	printf("_tr_node_id:Node_6_267;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
		tmp_if_expr = ((return_value_SensorValue_1 != 0) ? 1 : 0 != 0);
	printf("_tr_node_id:Node_6_268;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	Node_6_269:;
	__iv__branch_expr = !tmp_if_expr;
	printf("_tr_node_id:Node_6_270;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!tmp_if_expr) goto Node_6_283;
	printf("_tr_call:backUp;_tr_call_id:54;\n");fflush(stdout);
	backUp();
	printf("_tr_call:stopWheels;_tr_call_id:55;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_longRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_6_273;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
	Node_6_283:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_6_287;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_6_247;
	Node_6_288:;
	__iv__return_expr_longRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_6_289;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
}
signed int SensorValue(signed int sensor) {
	printf("_tr_node_id:Node_7_304;_tr_decl:res;\n");fflush(stdout);
	signed int res;
	printf("_tr_node_id:Node_7_305;_tr_decl:return_value___VERIFIER_nondet_unsigned_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:56;\n");fflush(stdout);
		return_value___VERIFIER_nondet_unsigned_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_7_308;_tr_assign:return_value___VERIFIER_nondet_unsigned_int=%d;\n", return_value___VERIFIER_nondet_unsigned_int);fflush(stdout);
		res = return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_node_id:Node_7_309;_tr_assign:res=%d;\n", res);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:57;\n");fflush(stdout);
	__CPROVER_assume(((0 <= res) && (res <= 65535)));
	__iv__return_expr_SensorValue = 	res;
	printf("_tr_node_id:Node_7_311;_tr_assign:__iv__return_expr_SensorValue=%d;\n", __iv__return_expr_SensorValue);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_SensorValue;
}
State findAWall() {
	printf("_tr_call:backUp;_tr_call_id:58;\n");fflush(stdout);
	backUp();
	printf("_tr_call:turnAround;_tr_call_id:59;\n");fflush(stdout);
	turnAround();
	printf("_tr_node_id:Node_8_319;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_node_id:Node_8_320;_tr_decl:return_value_medianFilter_0;\n");fflush(stdout);
	signed int return_value_medianFilter_0;
	printf("_tr_node_id:Node_8_321;_tr_decl:return_value_medianFilter_1;\n");fflush(stdout);
	signed int return_value_medianFilter_1;
	Node_8_322:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:60;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_8_322;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter >= 141));
	printf("_tr_node_id:Node_8_323;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter >= 141))) goto Node_8_369;
	unsigned int __iv__index_expr_var10 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_8_326;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var10, motor[__iv__index_expr_var10]);fflush(stdout);
	unsigned int __iv__index_expr_var11 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_8_327;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var11, motor[__iv__index_expr_var11]);fflush(stdout);
	printf("_tr_node_id:Node_8_328;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:61;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue = SensorValue(4);
	printf("_tr_node_id:Node_8_330;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue == 0);
	printf("_tr_node_id:Node_8_332;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue == 0)) goto Node_8_345;
	unsigned int __iv__index_expr_var12 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_8_333;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var12, motor[__iv__index_expr_var12]);fflush(stdout);
	unsigned int __iv__index_expr_var13 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_8_334;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var13, motor[__iv__index_expr_var13]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:62;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	Node_8_336:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:63;\n");fflush(stdout);
		return_value_medianFilter_0 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_8_336;_tr_assign:return_value_medianFilter_0=%d;\n", return_value_medianFilter_0);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_0 >= 141));
	printf("_tr_node_id:Node_8_337;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_0 >= 141))) goto Node_8_343;
	unsigned int __iv__index_expr_var14 = (unsigned) (0);
		motor[0] = (float)(-((20.0 * 1.3)));
	printf("_tr_node_id:Node_8_340;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var14, motor[__iv__index_expr_var14]);fflush(stdout);
	unsigned int __iv__index_expr_var15 = (unsigned) (1);
		motor[1] = 20.0f;
	printf("_tr_node_id:Node_8_341;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var15, motor[__iv__index_expr_var15]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_8_342;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_8_336;
	Node_8_343:;
	goto Node_8_369;
	Node_8_345:;
	printf("_tr_node_id:Node_8_346;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:64;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(5);
	printf("_tr_node_id:Node_8_348;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_8_350;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_8_363;
	unsigned int __iv__index_expr_var16 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_8_351;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var16, motor[__iv__index_expr_var16]);fflush(stdout);
	unsigned int __iv__index_expr_var17 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_8_352;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var17, motor[__iv__index_expr_var17]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:65;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	Node_8_354:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:66;\n");fflush(stdout);
		return_value_medianFilter_1 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_8_354;_tr_assign:return_value_medianFilter_1=%d;\n", return_value_medianFilter_1);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_1 >= 141));
	printf("_tr_node_id:Node_8_355;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_1 >= 141))) goto Node_8_361;
	unsigned int __iv__index_expr_var18 = (unsigned) (0);
		motor[0] = (float)((20.0 * 1.3));
	printf("_tr_node_id:Node_8_358;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var18, motor[__iv__index_expr_var18]);fflush(stdout);
	unsigned int __iv__index_expr_var19 = (unsigned) (1);
		motor[1] = (float)(-20);
	printf("_tr_node_id:Node_8_359;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var19, motor[__iv__index_expr_var19]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_8_360;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_8_354;
	Node_8_361:;
	goto Node_8_369;
	Node_8_363:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_8_368;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_8_322;
	Node_8_369:;
	printf("_tr_call:stopWheels;_tr_call_id:67;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_findAWall = 	(State)(8);
	printf("_tr_node_id:Node_8_371;_tr_assign:__iv__return_expr_findAWall=%d;\n", __iv__return_expr_findAWall);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_findAWall;
}
State disposeOfTarget() {
	unsigned int __iv__index_expr_var20 = (unsigned) (2);
		motor[2] = (float)(-10);
	printf("_tr_node_id:Node_9_377;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var20, motor[__iv__index_expr_var20]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:68;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 800);fflush(stdout);
	wait1Msec(800);
	unsigned int __iv__index_expr_var21 = (unsigned) (3);
		motor[3] = 20.0f;
	printf("_tr_node_id:Node_9_379;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var21, motor[__iv__index_expr_var21]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:69;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1200);fflush(stdout);
	wait1Msec(1200);
	printf("_tr_node_id:Node_9_381;_tr_decl:tmp_assign;\n");fflush(stdout);
	float tmp_assign;
		tmp_assign = 0.0f;
	printf("_tr_node_id:Node_9_382;_tr_assign:tmp_assign=%f;\n", tmp_assign);fflush(stdout);
	unsigned int __iv__index_expr_var22 = (unsigned) (2);
		motor[2] = tmp_assign;
	printf("_tr_node_id:Node_9_383;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var22, motor[__iv__index_expr_var22]);fflush(stdout);
	unsigned int __iv__index_expr_var23 = (unsigned) (3);
		motor[3] = tmp_assign;
	printf("_tr_node_id:Node_9_384;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var23, motor[__iv__index_expr_var23]);fflush(stdout);
	__iv__return_expr_disposeOfTarget = 	(State)(9);
	printf("_tr_node_id:Node_9_385;_tr_assign:__iv__return_expr_disposeOfTarget=%d;\n", __iv__return_expr_disposeOfTarget);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_disposeOfTarget;
}
State onPatrol() {
		sonarMax = 0;
	printf("_tr_node_id:Node_10_389;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:70;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_10_391;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_10_392:;
	printf("_tr_call:time1;_tr_call_id:71;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_10_392;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 6000);
	printf("_tr_node_id:Node_10_393;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 6000)) goto Node_10_408;
	printf("_tr_node_id:Node_10_396;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:72;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		return_value_SensorValue = SensorValue(1);
	printf("_tr_node_id:Node_10_398;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = !((return_value_SensorValue >= sonarMax));
	printf("_tr_node_id:Node_10_400;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_SensorValue >= sonarMax))) goto Node_10_402;
	printf("_tr_call:SensorValue;_tr_call_id:73;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		sonarMax = SensorValue(1);
	printf("_tr_node_id:Node_10_401;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	Node_10_402:;
	unsigned int __iv__index_expr_var24 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_10_403;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var24, motor[__iv__index_expr_var24]);fflush(stdout);
	unsigned int __iv__index_expr_var25 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_10_404;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var25, motor[__iv__index_expr_var25]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_10_407;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_10_392;
	Node_10_408:;
	printf("_tr_call:clearTimer;_tr_call_id:74;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_10_410;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	Node_10_411:;
	printf("_tr_call:SensorValue;_tr_call_id:75;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(1);
	printf("_tr_node_id:Node_10_411;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = !(((sonarMax + -100) >= return_value_SensorValue_0));
	printf("_tr_node_id:Node_10_412;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((sonarMax + -100) >= return_value_SensorValue_0))) goto Node_10_418;
	unsigned int __iv__index_expr_var26 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_10_415;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var26, motor[__iv__index_expr_var26]);fflush(stdout);
	unsigned int __iv__index_expr_var27 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_10_416;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var27, motor[__iv__index_expr_var27]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_10_417;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_10_411;
	Node_10_418:;
	printf("_tr_call:stopWheels;_tr_call_id:76;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var28 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_10_420;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var28, motor[__iv__index_expr_var28]);fflush(stdout);
	unsigned int __iv__index_expr_var29 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_10_421;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var29, motor[__iv__index_expr_var29]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:77;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 2500);fflush(stdout);
	wait1Msec(2500);
	printf("_tr_call:stopWheels;_tr_call_id:78;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_onPatrol = 	(State)(1);
	printf("_tr_node_id:Node_10_424;_tr_assign:__iv__return_expr_onPatrol=%d;\n", __iv__return_expr_onPatrol);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_onPatrol;
}
void clearTimer(signed int t1) {
	printf("_tr_return;\n");fflush(stdout);
}
void check_property() {
	(void)sizeof(signed int)  ;
	(void)sizeof(signed int)  ;
	if(!(!((isAllReached != 0)))) { printf("violated property: Node_12_433\n"); fflush(stdout); exit(0); }
	printf("_tr_return;\n");fflush(stdout);
}
State primaryScan() {
		IRMax = 0;
	printf("_tr_node_id:Node_13_435;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
		sonarMax = 0;
	printf("_tr_node_id:Node_13_436;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:80;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_13_438;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_13_439:;
	printf("_tr_call:time1;_tr_call_id:81;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_13_439;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 4000);
	printf("_tr_node_id:Node_13_440;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 4000)) goto Node_13_464;
	printf("_tr_node_id:Node_13_443;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:82;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_13_445;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (IRMax >= return_value_SensorValue);
	printf("_tr_node_id:Node_13_447;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((IRMax >= return_value_SensorValue)) goto Node_13_449;
	printf("_tr_call:SensorValue;_tr_call_id:83;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_13_448;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_13_449:;
	printf("_tr_node_id:Node_13_450;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:84;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(2);
	printf("_tr_node_id:Node_13_452;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue_0 >= ambientIR);
	printf("_tr_node_id:Node_13_454;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 >= ambientIR)) goto Node_13_456;
	printf("_tr_call:SensorValue;_tr_call_id:85;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		ambientIR = SensorValue(2);
	printf("_tr_node_id:Node_13_455;_tr_assign:ambientIR=%d;\n", ambientIR);fflush(stdout);
	Node_13_456:;
	unsigned int __iv__index_expr_var30 = (unsigned) (0);
		motor[0] = (float)(-((30.0 * 1.3)));
	printf("_tr_node_id:Node_13_457;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var30, motor[__iv__index_expr_var30]);fflush(stdout);
	unsigned int __iv__index_expr_var31 = (unsigned) (1);
		motor[1] = 30.0f;
	printf("_tr_node_id:Node_13_458;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var31, motor[__iv__index_expr_var31]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_13_463;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_13_439;
	Node_13_464:;
	printf("_tr_call:clearTimer;_tr_call_id:86;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_13_466;_tr_decl:return_value_time1_0;\n");fflush(stdout);
	signed int return_value_time1_0;
	Node_13_467:;
	printf("_tr_call:time1;_tr_call_id:87;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_0 = time1(0);
	printf("_tr_node_id:Node_13_467;_tr_assign:return_value_time1_0=%d;\n", return_value_time1_0);fflush(stdout);
	__iv__branch_expr = (return_value_time1_0 >= 4000);
	printf("_tr_node_id:Node_13_468;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_0 >= 4000)) goto Node_13_491;
	printf("_tr_node_id:Node_13_471;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	printf("_tr_call:SensorValue;_tr_call_id:88;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(2);
	printf("_tr_node_id:Node_13_473;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 50) >= return_value_SensorValue_1);
	printf("_tr_node_id:Node_13_475;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 50) >= return_value_SensorValue_1)) goto Node_13_483;
	printf("_tr_call:stopWheels;_tr_call_id:89;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_primaryScan = 	(State)(4);
	printf("_tr_node_id:Node_13_477;_tr_assign:__iv__return_expr_primaryScan=%d;\n", __iv__return_expr_primaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_primaryScan;
	Node_13_483:;
	unsigned int __iv__index_expr_var32 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_13_484;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var32, motor[__iv__index_expr_var32]);fflush(stdout);
	unsigned int __iv__index_expr_var33 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_13_485;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var33, motor[__iv__index_expr_var33]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_13_486;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:90;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_13_490;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_13_467;
	Node_13_491:;
	printf("_tr_call:stopWheels;_tr_call_id:91;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_primaryScan = 	(State)(3);
	printf("_tr_node_id:Node_13_493;_tr_assign:__iv__return_expr_primaryScan=%d;\n", __iv__return_expr_primaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_primaryScan;
}
signed int time1(signed int t1) {
	printf("_tr_node_id:Node_14_498;_tr_decl:res;\n");fflush(stdout);
	signed int res;
	printf("_tr_node_id:Node_14_499;_tr_decl:return_value___VERIFIER_nondet_unsigned_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:92;\n");fflush(stdout);
		return_value___VERIFIER_nondet_unsigned_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_14_502;_tr_assign:return_value___VERIFIER_nondet_unsigned_int=%d;\n", return_value___VERIFIER_nondet_unsigned_int);fflush(stdout);
		res = return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_node_id:Node_14_503;_tr_assign:res=%d;\n", res);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:93;\n");fflush(stdout);
	__CPROVER_assume(((0 <= res) && (res <= 65535)));
	__iv__return_expr_time1 = 	res;
	printf("_tr_node_id:Node_14_505;_tr_assign:__iv__return_expr_time1=%d;\n", __iv__return_expr_time1);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_time1;
}
State acquireTarget() {
	printf("_tr_call:stopWheels;_tr_call_id:94;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var34 = (unsigned) (2);
		motor[2] = (float)(-20);
	printf("_tr_node_id:Node_15_512;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var34, motor[__iv__index_expr_var34]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:95;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1500);fflush(stdout);
	wait1Msec(1500);
	unsigned int __iv__index_expr_var35 = (unsigned) (2);
		motor[2] = 0.0f;
	printf("_tr_node_id:Node_15_514;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var35, motor[__iv__index_expr_var35]);fflush(stdout);
	unsigned int __iv__index_expr_var36 = (unsigned) (3);
		motor[3] = (float)(-10);
	printf("_tr_node_id:Node_15_515;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var36, motor[__iv__index_expr_var36]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:96;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	unsigned int __iv__index_expr_var37 = (unsigned) (3);
		motor[3] = (float)(-30);
	printf("_tr_node_id:Node_15_517;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var37, motor[__iv__index_expr_var37]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:97;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 500);fflush(stdout);
	wait1Msec(500);
	unsigned int __iv__index_expr_var38 = (unsigned) (3);
		motor[3] = (float)(-10);
	printf("_tr_node_id:Node_15_519;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var38, motor[__iv__index_expr_var38]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:98;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	unsigned int __iv__index_expr_var39 = (unsigned) (2);
		motor[2] = 30.0f;
	printf("_tr_node_id:Node_15_521;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var39, motor[__iv__index_expr_var39]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:99;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 900);fflush(stdout);
	wait1Msec(900);
	unsigned int __iv__index_expr_var40 = (unsigned) (2);
		motor[2] = 10.0f;
	printf("_tr_node_id:Node_15_523;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var40, motor[__iv__index_expr_var40]);fflush(stdout);
	__iv__return_expr_acquireTarget = 	(State)(6);
	printf("_tr_node_id:Node_15_524;_tr_assign:__iv__return_expr_acquireTarget=%d;\n", __iv__return_expr_acquireTarget);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_acquireTarget;
}
void backUp() {
	printf("_tr_call:stopWheels;_tr_call_id:100;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:101;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	unsigned int __iv__index_expr_var41 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_16_529;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var41, motor[__iv__index_expr_var41]);fflush(stdout);
	unsigned int __iv__index_expr_var42 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_16_530;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var42, motor[__iv__index_expr_var42]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:102;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1500);fflush(stdout);
	wait1Msec(1500);
	printf("_tr_call:stopWheels;_tr_call_id:103;\n");fflush(stdout);
	stopWheels();
	printf("_tr_return;\n");fflush(stdout);
}
void stopWheels() {
	printf("_tr_node_id:Node_17_534;_tr_decl:tmp_assign;\n");fflush(stdout);
	float tmp_assign;
		tmp_assign = 0.0f;
	printf("_tr_node_id:Node_17_535;_tr_assign:tmp_assign=%f;\n", tmp_assign);fflush(stdout);
	unsigned int __iv__index_expr_var43 = (unsigned) (1);
		motor[1] = tmp_assign;
	printf("_tr_node_id:Node_17_536;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var43, motor[__iv__index_expr_var43]);fflush(stdout);
	unsigned int __iv__index_expr_var44 = (unsigned) (0);
		motor[0] = tmp_assign;
	printf("_tr_node_id:Node_17_537;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var44, motor[__iv__index_expr_var44]);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
State taskComplete() {
	printf("_tr_call:stopWheels;_tr_call_id:104;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:backUp;_tr_call_id:105;\n");fflush(stdout);
	backUp();
	printf("_tr_node_id:Node_19_571;_tr_decl:i;\n");fflush(stdout);
	signed int i;
		i = 0;
	printf("_tr_node_id:Node_19_572;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_19_574:;
	__iv__branch_expr = (i >= 3);
	printf("_tr_node_id:Node_19_574;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 3)) goto Node_19_582;
	unsigned int __iv__index_expr_var45 = (unsigned) (2);
		motor[2] = 30.0f;
	printf("_tr_node_id:Node_19_575;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var45, motor[__iv__index_expr_var45]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:106;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 2000);fflush(stdout);
	wait1Msec(2000);
	unsigned int __iv__index_expr_var46 = (unsigned) (2);
		motor[2] = (float)(-30);
	printf("_tr_node_id:Node_19_577;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var46, motor[__iv__index_expr_var46]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:107;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	printf("_tr_call:turnAround;_tr_call_id:108;\n");fflush(stdout);
	turnAround();
		i = (i + 1);
	printf("_tr_node_id:Node_19_580;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_19_574;
	Node_19_582:;
	__iv__return_expr_taskComplete = 	(State)(0);
	printf("_tr_node_id:Node_19_583;_tr_assign:__iv__return_expr_taskComplete=%d;\n", __iv__return_expr_taskComplete);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_taskComplete;
}
void update_prop_automata() {
	unsigned int __iv__index_expr_var47 = (unsigned) ((signed long int)(machineState));
		reachedStates[(signed long int)(machineState)] = (reachedStates[(signed long int)(machineState)] + 1);
	printf("_tr_node_id:Node_20_587;_tr_assign:reachedStates[%u]=%d;\n", __iv__index_expr_var47, reachedStates[__iv__index_expr_var47]);fflush(stdout);
		isAllReached = 1;
	printf("_tr_node_id:Node_20_588;_tr_assign:isAllReached=%d;\n", isAllReached);fflush(stdout);
	printf("_tr_node_id:Node_20_589;_tr_decl:i;\n");fflush(stdout);
	signed int i;
		i = 0;
	printf("_tr_node_id:Node_20_590;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_20_592:;
	__iv__branch_expr = (i >= 10);
	printf("_tr_node_id:Node_20_592;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 10)) goto Node_20_599;
	__iv__branch_expr = !((reachedStates[(signed long int)(i)] == 0));
	printf("_tr_node_id:Node_20_593;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((reachedStates[(signed long int)(i)] == 0))) goto Node_20_596;
		isAllReached = 0;
	printf("_tr_node_id:Node_20_594;_tr_assign:isAllReached=%d;\n", isAllReached);fflush(stdout);
	goto Node_20_599;
	Node_20_596:;
		i = (i + 1);
	printf("_tr_node_id:Node_20_597;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_20_592;
	Node_20_599:;
	printf("_tr_return;\n");fflush(stdout);
}
void wait1Msec(signed int sec) {
	printf("_tr_return;\n");fflush(stdout);
}
void turnAround() {
	printf("_tr_call:stopWheels;_tr_call_id:109;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var48 = (unsigned) (0);
		motor[0] = (float)(-((30.0 * 1.3)));
	printf("_tr_node_id:Node_22_605;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var48, motor[__iv__index_expr_var48]);fflush(stdout);
	unsigned int __iv__index_expr_var49 = (unsigned) (1);
		motor[1] = 30.0f;
	printf("_tr_node_id:Node_22_606;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var49, motor[__iv__index_expr_var49]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:110;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	printf("_tr_call:stopWheels;_tr_call_id:111;\n");fflush(stdout);
	stopWheels();
	printf("_tr_return;\n");fflush(stdout);
}
signed int __iv__medianFilter_stub(){
	__iv__return_expr_medianFilter = medianFilter___iv__return_expr_medianFilter_list[medianFilter_stub_index];
	medianFilter_stub_index++;
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
}
