#include <assert.h>
#include <stdlib.h>
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
signed int FlAcpiConfigureFloppy(signed int DisketteExtension, signed int FdcInfo);
signed int FlFdcDeviceIo(signed int DeviceObject, signed int Ioctl, signed int Data);
signed int FlQueueIrpToThread(signed int Irp, signed int DisketteExtension);
signed int FloppyPnp(signed int DeviceObject, signed int Irp);
signed int FloppyPnpComplete(signed int DeviceObject, signed int Irp, signed int Context);
void FloppyProcessQueuedRequests(signed int DisketteExtension);
signed int FloppyStartDevice(signed int DeviceObject, signed int Irp);
signed int IoBuildDeviceIoControlRequest(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock);
signed int IoDeleteSymbolicLink(signed int SymbolicLinkName);
signed int IoQueryDeviceDescription(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context);
signed int IoRegisterDeviceInterface(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName);
signed int IoSetDeviceInterfaceState(signed int SymbolicLinkName, signed int Enable);
signed int IofCallDriver(signed int DeviceObject, signed int Irp);
void IofCompleteRequest(signed int Irp, signed int PriorityBoost);
signed int KeSetEvent(signed int Event, signed int Increment, signed int Wait);
signed int KeWaitForSingleObject(signed int Object, signed int WaitReason, signed int WaitMode, signed int Alertable, signed int Timeout);
signed int ObReferenceObjectByHandle(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation);
signed int PsCreateSystemThread(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext);
signed int ZwClose(signed int Handle);
void _BLAST_init(void);
void errorFn(void);
void reach_error();
void stubMoreProcessingRequired(void);
void stub_driver_init(void);
signed int DC;
signed int DiskController;
signed int Executive;
signed int FlConfigCallBack;
signed int FloppyDiskPeripheral;
signed int FloppyThread;
signed int IPC;
signed int KernelMode;
signed int MOUNTDEV_MOUNTED_DEVICE_GUID;
signed int MPR1;
signed int MPR3;
signed int MaximumInterfaceType;
signed int NP;
signed int PagingMutex=0;
signed int PagingReferenceCount=0;
signed int SKIP1;
signed int SKIP2;
signed int Suspended;
signed int UNLOADED;
signed int compRegistered;
signed int customIrp;
signed int lowerDriverReturn;
signed int myStatus;
signed int pended;
signed int s;
signed int setEventCalled;
extern signed int __VERIFIER_nondet_signed_int();
signed int __iv__ObReferenceObjectByHandle_stub(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation);
signed int __iv__IoQueryDeviceDescription_stub(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context);
signed int __iv__ZwClose_stub(signed int Handle);
signed int __iv__IoRegisterDeviceInterface_stub(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName);
signed int __iv__IoSetDeviceInterfaceState_stub(signed int SymbolicLinkName, signed int Enable);
signed int __iv__IoBuildDeviceIoControlRequest_stub(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock);
signed int __iv__IoDeleteSymbolicLink_stub(signed int SymbolicLinkName);
signed int __iv__PsCreateSystemThread_stub(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext);
int main() {
	signed int status;
	signed int irp;
	irp = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", irp);
	signed int pirp;
	signed int pirp__IoStatus__Status;
	signed int irp_choice;
	irp_choice = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", irp_choice);
	signed int devobj;
	devobj = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", devobj);
	FloppyThread = 0;
	KernelMode = 0;
	Suspended = 0;
	Executive = 0;
	DiskController = 0;
	FloppyDiskPeripheral = 0;
	FlConfigCallBack = 0;
	MaximumInterfaceType = 0;
	MOUNTDEV_MOUNTED_DEVICE_GUID = 0;
	myStatus = 0;
	s = 0;
	UNLOADED = 0;
	NP = 0;
	DC = 0;
	SKIP1 = 0;
	SKIP2 = 0;
	MPR1 = 0;
	MPR3 = 0;
	IPC = 0;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	status = 0;
	pirp = irp;
	_BLAST_init();
	if (!((status >= 0))) goto Node_0_99;
	s = NP;
	customIrp = 0;
	setEventCalled = customIrp;
	lowerDriverReturn = setEventCalled;
	compRegistered = lowerDriverReturn;
	pended = compRegistered;
	pirp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((irp_choice == 0))) goto Node_0_55;
	pirp__IoStatus__Status = -1073741637;
	myStatus = -1073741637;
	Node_0_55:;
	stub_driver_init();
	if (!((status < 0))) goto Node_0_70;
	return -1;
	Node_0_70:;
	signed int tmp_ndt_1;
	tmp_ndt_1 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_1);
	if (!((tmp_ndt_1 == 3))) goto Node_0_76;
	goto Node_0_78;
	Node_0_76:;
	goto Node_0_80;
	Node_0_78:;
	status = FloppyPnp(devobj, pirp);
	goto Node_0_95;
	Node_0_80:;
	return -1;
	Node_0_95:;
	Node_0_99:;
	if (!((pended == 1))) goto Node_0_107;
	if (!((s == NP))) goto Node_0_104;
	s = NP;
	goto Node_0_105;
	Node_0_104:;
	goto Node_0_107;
	Node_0_105:;
	goto Node_0_146;
	Node_0_107:;
	if (!((pended == 1))) goto Node_0_114;
	if (!((s == MPR3))) goto Node_0_111;
	s = MPR3;
	goto Node_0_112;
	Node_0_111:;
	goto Node_0_114;
	Node_0_112:;
	goto Node_0_145;
	Node_0_114:;
	if (!((s != UNLOADED))) goto Node_0_144;
	if (!((status != -1))) goto Node_0_143;
	if (!((s != SKIP2))) goto Node_0_127;
	if (!((s != IPC))) goto Node_0_124;
	if (!((s != DC))) goto Node_0_121;
	errorFn();
	goto Node_0_122;
	Node_0_121:;
	goto Node_0_127;
	Node_0_122:;
	goto Node_0_125;
	Node_0_124:;
	goto Node_0_127;
	Node_0_125:;
	goto Node_0_142;
	Node_0_127:;
	if (!((pended == 1))) goto Node_0_132;
	if (!((status != 259))) goto Node_0_130;
	errorFn();
	Node_0_130:;
	goto Node_0_141;
	Node_0_132:;
	if (!((s == DC))) goto Node_0_137;
	if (!((status == 259))) goto Node_0_135;
	errorFn();
	Node_0_135:;
	goto Node_0_140;
	Node_0_137:;
	if (!((status != lowerDriverReturn))) goto Node_0_139;
	errorFn();
	Node_0_139:;
	Node_0_140:;
	Node_0_141:;
	Node_0_142:;
	Node_0_143:;
	Node_0_144:;
	Node_0_145:;
	Node_0_146:;
	status = 0;
	return status;
}
signed int KeSetEvent(signed int Event, signed int Increment, signed int Wait) {
	signed int l;
	l = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", l);
	setEventCalled = 1;
	return l;
}
signed int IofCallDriver(signed int DeviceObject, signed int Irp) {
	signed int returnVal2;
	signed int compRetStatus1;
	signed int lcontext;
	lcontext = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", lcontext);
	unsigned long int __cil_tmp7;
	if (!((compRegistered != 0))) goto Node_3_189;
	compRetStatus1 = FloppyPnpComplete(DeviceObject, Irp, lcontext);
	__cil_tmp7 = (unsigned long int)(compRetStatus1);
	if (!((__cil_tmp7 == (unsigned long int)(-1073741802)))) goto Node_3_188;
	stubMoreProcessingRequired();
	Node_3_188:;
	Node_3_189:;
	signed int tmp_ndt_12;
	tmp_ndt_12 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_12);
	if (!((tmp_ndt_12 == 0))) goto Node_3_195;
	goto Node_3_202;
	Node_3_195:;
	signed int tmp_ndt_7;
	tmp_ndt_7 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_7);
	if (!((tmp_ndt_7 == 1))) goto Node_3_200;
	goto Node_3_204;
	Node_3_200:;
	goto Node_3_206;
	Node_3_202:;
	returnVal2 = 0;
	goto Node_3_209;
	Node_3_204:;
	returnVal2 = -1073741823;
	goto Node_3_209;
	Node_3_206:;
	returnVal2 = 259;
	if (FALSE) goto Node_3_208;
	Node_3_208:;
	Node_3_209:;
	if (!((s == NP))) goto Node_3_218;
	s = IPC;
	lowerDriverReturn = returnVal2;
	goto Node_3_234;
	Node_3_218:;
	if (!((s == MPR1))) goto Node_3_227;
	if (!((returnVal2 == 259))) goto Node_3_223;
	s = MPR3;
	lowerDriverReturn = returnVal2;
	goto Node_3_225;
	Node_3_223:;
	s = NP;
	lowerDriverReturn = returnVal2;
	Node_3_225:;
	goto Node_3_233;
	Node_3_227:;
	if (!((s == SKIP1))) goto Node_3_231;
	s = SKIP2;
	lowerDriverReturn = returnVal2;
	goto Node_3_232;
	Node_3_231:;
	errorFn();
	Node_3_232:;
	Node_3_233:;
	Node_3_234:;
	return returnVal2;
}
signed int IoBuildDeviceIoControlRequest(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock) {
	signed int malloc;
	malloc = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", malloc);
	customIrp = 1;
	signed int tmp_ndt_2;
	tmp_ndt_2 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_2);
	if (!((tmp_ndt_2 == 0))) goto Node_4_254;
	goto Node_4_256;
	Node_4_254:;
	goto Node_4_261;
	Node_4_256:;
	return malloc;
	Node_4_261:;
	return 0;
}
signed int FlFdcDeviceIo(signed int DeviceObject, signed int Ioctl, signed int Data) {
	signed int ntStatus;
	signed int irp;
	signed int irpStack;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", doneEvent);
	signed int ioStatus;
	ioStatus = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", ioStatus);
	signed int irp__Tail__Overlay__CurrentStackLocation;
	irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", irp__Tail__Overlay__CurrentStackLocation);
	signed int irpStack__Parameters__DeviceIoControl__Type3InputBuffer;
	signed long int __cil_tmp11;
	irp = __iv__IoBuildDeviceIoControlRequest_stub(Ioctl, DeviceObject, 0, 0, 0, 0, 1, doneEvent, ioStatus);
	if (!((irp == 0))) goto Node_5_306;
	return -1073741670;
	Node_5_306:;
	irpStack = (irp__Tail__Overlay__CurrentStackLocation - 1);
	irpStack__Parameters__DeviceIoControl__Type3InputBuffer = Data;
	ntStatus = IofCallDriver(DeviceObject, irp);
	__cil_tmp11 = (signed long int)(ntStatus);
	if (!((__cil_tmp11 == 259l))) goto Node_5_314;
	KeWaitForSingleObject(doneEvent, Suspended, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_5_314:;
	return ntStatus;
}
signed int FloppyStartDevice(signed int DeviceObject, signed int Irp) {
	signed int DeviceObject__DeviceExtension;
	DeviceObject__DeviceExtension = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", DeviceObject__DeviceExtension);
	signed int Irp__Tail__Overlay__CurrentStackLocation;
	Irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", Irp__Tail__Overlay__CurrentStackLocation);
	signed int Irp__IoStatus__Status;
	signed int disketteExtension__TargetObject;
	disketteExtension__TargetObject = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__TargetObject);
	signed int disketteExtension__MaxTransferSize;
	signed int disketteExtension__DriveType;
	disketteExtension__DriveType = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__DriveType);
	signed int disketteExtension__DeviceUnit;
	signed int disketteExtension__UnderlyingPDO;
	disketteExtension__UnderlyingPDO = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__UnderlyingPDO);
	signed int disketteExtension__InterfaceString;
	disketteExtension__InterfaceString = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__InterfaceString);
	signed int disketteExtension__IsStarted;
	signed int disketteExtension__HoldNewRequests;
	signed int ntStatus;
	signed int pnpStatus;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", doneEvent);
	signed int fdcInfo;
	fdcInfo = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo);
	signed int fdcInfo__BufferCount;
	signed int fdcInfo__BufferSize;
	signed int fdcInfo__MaxTransferSize;
	fdcInfo__MaxTransferSize = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__MaxTransferSize);
	signed int fdcInfo__AcpiBios;
	fdcInfo__AcpiBios = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__AcpiBios);
	signed int fdcInfo__AcpiFdiSupported;
	fdcInfo__AcpiFdiSupported = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__AcpiFdiSupported);
	signed int fdcInfo__PeripheralNumber;
	fdcInfo__PeripheralNumber = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__PeripheralNumber);
	signed int fdcInfo__BusType;
	signed int fdcInfo__ControllerNumber;
	fdcInfo__ControllerNumber = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__ControllerNumber);
	signed int fdcInfo__UnitNumber;
	fdcInfo__UnitNumber = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__UnitNumber);
	signed int fdcInfo__BusNumber;
	fdcInfo__BusNumber = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", fdcInfo__BusNumber);
	signed int Dc;
	signed int Fp;
	signed int disketteExtension;
	signed int irpSp;
	signed int irpSp___0;
	signed int nextIrpSp;
	signed int nextIrpSp__Control;
	signed int irpSp___1;
	signed int irpSp__Control;
	signed int irpSp__Context;
	signed int InterfaceType;
	signed int KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86;
	KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86);
	signed long int __cil_tmp42;
	signed int __cil_tmp43;
	signed int __cil_tmp44;
	signed int __cil_tmp45;
	signed int __cil_tmp46;
	Dc = DiskController;
	Fp = FloppyDiskPeripheral;
	disketteExtension = DeviceObject__DeviceExtension;
	irpSp = Irp__Tail__Overlay__CurrentStackLocation;
	irpSp___0 = Irp__Tail__Overlay__CurrentStackLocation;
	nextIrpSp = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	nextIrpSp__Control = 0;
	if (!((s != NP))) goto Node_6_434;
	errorFn();
	goto Node_6_439;
	Node_6_434:;
	if (!((compRegistered != 0))) goto Node_6_437;
	errorFn();
	goto Node_6_438;
	Node_6_437:;
	compRegistered = 1;
	Node_6_438:;
	Node_6_439:;
	irpSp___1 = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	irpSp__Context = doneEvent;
	irpSp__Control = 224;
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	__cil_tmp42 = (signed long int)(ntStatus);
	if (!((__cil_tmp42 == 259l))) goto Node_6_448;
	ntStatus = KeWaitForSingleObject(doneEvent, Executive, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_6_448:;
	fdcInfo__BufferCount = 0;
	fdcInfo__BufferSize = 0;
	__cil_tmp43 = 3080;
	__cil_tmp44 = 458752;
	__cil_tmp45 = 461832;
	__cil_tmp46 = 461835;
	ntStatus = FlFdcDeviceIo(disketteExtension__TargetObject, __cil_tmp46, fdcInfo);
	if (!((ntStatus >= 0))) goto Node_6_499;
	disketteExtension__MaxTransferSize = fdcInfo__MaxTransferSize;
	if (!((fdcInfo__AcpiBios != 0))) goto Node_6_467;
	if (!((fdcInfo__AcpiFdiSupported != 0))) goto Node_6_464;
	ntStatus = FlAcpiConfigureFloppy(disketteExtension, fdcInfo);
	if ((disketteExtension__DriveType == 4)) goto Node_6_462;
	Node_6_462:;
	goto Node_6_465;
	Node_6_464:;
	goto Node_6_467;
	Node_6_465:;
	goto Node_6_485;
	Node_6_467:;
	if ((disketteExtension__DriveType == 4)) goto Node_6_468;
	Node_6_468:;
	InterfaceType = 0;
	Node_6_470:;
	if (!((1 != 0))) goto Node_6_482;
	if ((InterfaceType >= MaximumInterfaceType)) goto Node_6_484;
	fdcInfo__BusType = InterfaceType;
	ntStatus = __iv__IoQueryDeviceDescription_stub(fdcInfo__BusType, fdcInfo__BusNumber, Dc, fdcInfo__ControllerNumber, Fp, fdcInfo__PeripheralNumber, FlConfigCallBack, disketteExtension);
	if ((ntStatus >= 0)) goto Node_6_484;
	InterfaceType = (InterfaceType + 1);
	goto Node_6_470;
	Node_6_482:;
	Node_6_484:;
	Node_6_485:;
	if (!((ntStatus >= 0))) goto Node_6_498;
	if (!((KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 != 0))) goto Node_6_490;
	disketteExtension__DeviceUnit = fdcInfo__UnitNumber;
	goto Node_6_491;
	Node_6_490:;
	disketteExtension__DeviceUnit = fdcInfo__PeripheralNumber;
	Node_6_491:;
	pnpStatus = __iv__IoRegisterDeviceInterface_stub(disketteExtension__UnderlyingPDO, MOUNTDEV_MOUNTED_DEVICE_GUID, 0, disketteExtension__InterfaceString);
	if (!((pnpStatus >= 0))) goto Node_6_495;
	pnpStatus = __iv__IoSetDeviceInterfaceState_stub(disketteExtension__InterfaceString, 1);
	Node_6_495:;
	disketteExtension__IsStarted = 1;
	disketteExtension__HoldNewRequests = 0;
	Node_6_498:;
	Node_6_499:;
	Irp__IoStatus__Status = ntStatus;
	myStatus = ntStatus;
	IofCompleteRequest(Irp, 0);
	return ntStatus;
}
signed int FloppyPnp(signed int DeviceObject, signed int Irp) {
	signed int DeviceObject__DeviceExtension;
	DeviceObject__DeviceExtension = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", DeviceObject__DeviceExtension);
	signed int Irp__Tail__Overlay__CurrentStackLocation;
	Irp__Tail__Overlay__CurrentStackLocation = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", Irp__Tail__Overlay__CurrentStackLocation);
	signed int Irp__IoStatus__Information;
	signed int Irp__IoStatus__Status;
	signed int Irp__CurrentLocation;
	Irp__CurrentLocation = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", Irp__CurrentLocation);
	signed int disketteExtension__IsRemoved;
	disketteExtension__IsRemoved = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__IsRemoved);
	signed int disketteExtension__IsStarted;
	disketteExtension__IsStarted = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__IsStarted);
	signed int disketteExtension__TargetObject;
	disketteExtension__TargetObject = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__TargetObject);
	signed int disketteExtension__HoldNewRequests;
	signed int disketteExtension__FloppyThread;
	disketteExtension__FloppyThread = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__FloppyThread);
	signed int disketteExtension__InterfaceString__Buffer;
	disketteExtension__InterfaceString__Buffer = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__InterfaceString__Buffer);
	signed int disketteExtension__InterfaceString;
	disketteExtension__InterfaceString = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__InterfaceString);
	signed int disketteExtension__ArcName__Length;
	disketteExtension__ArcName__Length = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__ArcName__Length);
	signed int disketteExtension__ArcName;
	disketteExtension__ArcName = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", disketteExtension__ArcName);
	signed int irpSp__MinorFunction;
	irpSp__MinorFunction = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", irpSp__MinorFunction);
	signed int IoGetConfigurationInformation__FloppyCount;
	IoGetConfigurationInformation__FloppyCount = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", IoGetConfigurationInformation__FloppyCount);
	signed int irpSp;
	signed int disketteExtension;
	signed int ntStatus;
	signed int doneEvent;
	doneEvent = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", doneEvent);
	signed int irpSp___0;
	signed int nextIrpSp;
	signed int nextIrpSp__Control;
	signed int irpSp___1;
	signed int irpSp__Context;
	signed int irpSp__Control;
	signed long int __cil_tmp29;
	signed long int __cil_tmp30;
	ntStatus = 0;
	PagingReferenceCount = (PagingReferenceCount + 1);
	if ((PagingReferenceCount == 1)) goto Node_7_642;
	Node_7_642:;
	disketteExtension = DeviceObject__DeviceExtension;
	irpSp = Irp__Tail__Overlay__CurrentStackLocation;
	if (!((disketteExtension__IsRemoved != 0))) goto Node_7_694;
	Irp__IoStatus__Information = 0;
	Irp__IoStatus__Status = -1073741738;
	myStatus = -1073741738;
	IofCompleteRequest(Irp, 0);
	return -1073741738;
	Node_7_694:;
	if (!((irpSp__MinorFunction == 0))) goto Node_7_698;
	goto Node_7_718;
	Node_7_698:;
	if (!((irpSp__MinorFunction == 5))) goto Node_7_701;
	goto Node_7_720;
	Node_7_701:;
	if (!((irpSp__MinorFunction == 1))) goto Node_7_704;
	goto Node_7_720;
	Node_7_704:;
	if (!((irpSp__MinorFunction == 6))) goto Node_7_707;
	goto Node_7_802;
	Node_7_707:;
	if (!((irpSp__MinorFunction == 3))) goto Node_7_710;
	goto Node_7_802;
	Node_7_710:;
	if (!((irpSp__MinorFunction == 4))) goto Node_7_713;
	goto Node_7_846;
	Node_7_713:;
	if (!((irpSp__MinorFunction == 2))) goto Node_7_716;
	goto Node_7_858;
	Node_7_716:;
	goto Node_7_879;
	Node_7_718:;
	ntStatus = FloppyStartDevice(DeviceObject, Irp);
	goto Node_7_889;
	Node_7_720:;
	if ((irpSp__MinorFunction == 5)) goto Node_7_721;
	Node_7_721:;
	if ((disketteExtension__IsStarted != 0)) goto Node_7_775;
	if (!((s == NP))) goto Node_7_726;
	s = SKIP1;
	goto Node_7_727;
	Node_7_726:;
	errorFn();
	Node_7_727:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	return ntStatus;
	Node_7_775:;
	disketteExtension__HoldNewRequests = 1;
	ntStatus = FlQueueIrpToThread(Irp, disketteExtension);
	__cil_tmp29 = (signed long int)(ntStatus);
	if (!((__cil_tmp29 == 259l))) goto Node_7_795;
	KeWaitForSingleObject(disketteExtension__FloppyThread, Executive, KernelMode, 0, 0);
	if ((disketteExtension__FloppyThread != 0)) goto Node_7_782;
	Node_7_782:;
	disketteExtension__FloppyThread = 0;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_7_789;
	s = SKIP1;
	goto Node_7_790;
	Node_7_789:;
	errorFn();
	Node_7_790:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	goto Node_7_800;
	Node_7_795:;
	ntStatus = -1073741823;
	Irp__IoStatus__Status = IofCallDriver(disketteExtension__TargetObject, Irp);
	myStatus = ntStatus;
	Irp__IoStatus__Information = 0;
	IofCompleteRequest(Irp, 0);
	Node_7_800:;
	goto Node_7_889;
	Node_7_802:;
	if ((irpSp__MinorFunction == 6)) goto Node_7_803;
	Node_7_803:;
	if ((disketteExtension__IsStarted != 0)) goto Node_7_816;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_7_810;
	s = SKIP1;
	goto Node_7_811;
	Node_7_810:;
	errorFn();
	Node_7_811:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_7_844;
	Node_7_816:;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	irpSp___0 = Irp__Tail__Overlay__CurrentStackLocation;
	nextIrpSp = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	nextIrpSp__Control = 0;
	if (!((s != NP))) goto Node_7_824;
	errorFn();
	goto Node_7_829;
	Node_7_824:;
	if (!((compRegistered != 0))) goto Node_7_827;
	errorFn();
	goto Node_7_828;
	Node_7_827:;
	compRegistered = 1;
	Node_7_828:;
	Node_7_829:;
	irpSp___1 = (Irp__Tail__Overlay__CurrentStackLocation - 1);
	irpSp__Context = doneEvent;
	irpSp__Control = 224;
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	__cil_tmp30 = (signed long int)(ntStatus);
	if (!((__cil_tmp30 == 259l))) goto Node_7_838;
	KeWaitForSingleObject(doneEvent, Executive, KernelMode, 0, 0);
	ntStatus = myStatus;
	Node_7_838:;
	disketteExtension__HoldNewRequests = 0;
	Irp__IoStatus__Status = ntStatus;
	myStatus = ntStatus;
	Irp__IoStatus__Information = 0;
	IofCompleteRequest(Irp, 0);
	Node_7_844:;
	goto Node_7_889;
	Node_7_846:;
	disketteExtension__IsStarted = 0;
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	if (!((s == NP))) goto Node_7_852;
	s = SKIP1;
	goto Node_7_853;
	Node_7_852:;
	errorFn();
	Node_7_853:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_7_889;
	Node_7_858:;
	disketteExtension__HoldNewRequests = 0;
	disketteExtension__IsStarted = 0;
	disketteExtension__IsRemoved = 1;
	if (!((s == NP))) goto Node_7_864;
	s = SKIP1;
	goto Node_7_865;
	Node_7_864:;
	errorFn();
	Node_7_865:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	Irp__IoStatus__Status = 0;
	myStatus = 0;
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	if (!((disketteExtension__InterfaceString__Buffer != 0))) goto Node_7_873;
	__iv__IoSetDeviceInterfaceState_stub(disketteExtension__InterfaceString, 0);
	Node_7_873:;
	if (!((disketteExtension__ArcName__Length != 0))) goto Node_7_876;
	__iv__IoDeleteSymbolicLink_stub(disketteExtension__ArcName);
	Node_7_876:;
	IoGetConfigurationInformation__FloppyCount = (IoGetConfigurationInformation__FloppyCount - 1);
	goto Node_7_889;
	Node_7_879:;
	if (!((s == NP))) goto Node_7_883;
	s = SKIP1;
	goto Node_7_884;
	Node_7_883:;
	errorFn();
	Node_7_884:;
	Irp__CurrentLocation = (Irp__CurrentLocation + 1);
	Irp__Tail__Overlay__CurrentStackLocation = (Irp__Tail__Overlay__CurrentStackLocation + 1);
	ntStatus = IofCallDriver(disketteExtension__TargetObject, Irp);
	goto Node_7_890;
	Node_7_889:;
	Node_7_890:;
	PagingReferenceCount = (PagingReferenceCount - 1);
	if ((PagingReferenceCount == 0)) goto Node_7_900;
	Node_7_900:;
	return ntStatus;
}
signed int FlQueueIrpToThread(signed int Irp, signed int DisketteExtension) {
	signed int status;
	signed int threadHandle;
	threadHandle = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", threadHandle);
	signed int DisketteExtension__PoweringDown;
	DisketteExtension__PoweringDown = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", DisketteExtension__PoweringDown);
	signed int DisketteExtension__ThreadReferenceCount;
	DisketteExtension__ThreadReferenceCount = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", DisketteExtension__ThreadReferenceCount);
	signed int DisketteExtension__FloppyThread;
	DisketteExtension__FloppyThread = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", DisketteExtension__FloppyThread);
	signed int Irp__IoStatus__Status;
	signed int Irp__IoStatus__Information;
	signed int ObjAttributes;
	ObjAttributes = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", ObjAttributes);
	if (!((DisketteExtension__PoweringDown == 1))) goto Node_8_994;
	myStatus = -1073741101;
	Irp__IoStatus__Status = -1073741101;
	Irp__IoStatus__Information = 0;
	return -1073741101;
	Node_8_994:;
	DisketteExtension__ThreadReferenceCount = (DisketteExtension__ThreadReferenceCount + 1);
	if (!((DisketteExtension__ThreadReferenceCount == 0))) goto Node_8_1048;
	DisketteExtension__ThreadReferenceCount = (DisketteExtension__ThreadReferenceCount + 1);
	PagingReferenceCount = (PagingReferenceCount + 1);
	if ((PagingReferenceCount == 1)) goto Node_8_1000;
	Node_8_1000:;
	status = __iv__PsCreateSystemThread_stub(threadHandle, 0, ObjAttributes, 0, 0, FloppyThread, DisketteExtension);
	if (!((status < 0))) goto Node_8_1025;
	DisketteExtension__ThreadReferenceCount = -1;
	PagingReferenceCount = (PagingReferenceCount - 1);
	if ((PagingReferenceCount == 0)) goto Node_8_1006;
	Node_8_1006:;
	return status;
	Node_8_1025:;
	status = __iv__ObReferenceObjectByHandle_stub(threadHandle, 1048576, 0, KernelMode, DisketteExtension__FloppyThread, 0);
	__iv__ZwClose_stub(threadHandle);
	if (!((status < 0))) goto Node_8_1047;
	return status;
	Node_8_1047:;
	Node_8_1048:;
	if (!((pended == 0))) goto Node_8_1052;
	pended = 1;
	goto Node_8_1053;
	Node_8_1052:;
	errorFn();
	Node_8_1053:;
	return 259;
}
signed int ZwClose(signed int Handle) {
	signed int tmp_ndt_11;
	tmp_ndt_11 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_11);
	if (!((tmp_ndt_11 == 0))) goto Node_9_1078;
	goto Node_9_1080;
	Node_9_1078:;
	goto Node_9_1083;
	Node_9_1080:;
	return 0;
	Node_9_1083:;
	return -1073741823;
}
signed int PsCreateSystemThread(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext) {
	signed int tmp_ndt_10;
	tmp_ndt_10 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_10);
	if (!((tmp_ndt_10 == 0))) goto Node_10_1097;
	goto Node_10_1099;
	Node_10_1097:;
	goto Node_10_1102;
	Node_10_1099:;
	return 0;
	Node_10_1102:;
	return -1073741823;
}
signed int ObReferenceObjectByHandle(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation) {
	signed int tmp_ndt_9;
	tmp_ndt_9 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_9);
	if (!((tmp_ndt_9 == 0))) goto Node_11_1116;
	goto Node_11_1118;
	Node_11_1116:;
	goto Node_11_1121;
	Node_11_1118:;
	return 0;
	Node_11_1121:;
	return -1073741823;
}
signed int KeWaitForSingleObject(signed int Object, signed int WaitReason, signed int WaitMode, signed int Alertable, signed int Timeout) {
	if (!((s == MPR3))) goto Node_12_1138;
	if (!((setEventCalled == 1))) goto Node_12_1135;
	s = NP;
	setEventCalled = 0;
	goto Node_12_1136;
	Node_12_1135:;
	goto Node_12_1138;
	Node_12_1136:;
	goto Node_12_1146;
	Node_12_1138:;
	if (!((customIrp == 1))) goto Node_12_1142;
	s = NP;
	customIrp = 0;
	goto Node_12_1145;
	Node_12_1142:;
	if (!((s == MPR3))) goto Node_12_1144;
	errorFn();
	Node_12_1144:;
	Node_12_1145:;
	Node_12_1146:;
	signed int tmp_ndt_8;
	tmp_ndt_8 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_8);
	if (!((tmp_ndt_8 == 0))) goto Node_12_1152;
	goto Node_12_1154;
	Node_12_1152:;
	goto Node_12_1157;
	Node_12_1154:;
	return 0;
	Node_12_1157:;
	return -1073741823;
}
signed int IoQueryDeviceDescription(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context) {
	signed int tmp_ndt_4;
	tmp_ndt_4 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_4);
	if (!((tmp_ndt_4 == 0))) goto Node_13_1171;
	goto Node_13_1173;
	Node_13_1171:;
	goto Node_13_1176;
	Node_13_1173:;
	return 0;
	Node_13_1176:;
	return -1073741823;
}
signed int IoRegisterDeviceInterface(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName) {
	signed int tmp_ndt_5;
	tmp_ndt_5 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_5);
	if (!((tmp_ndt_5 == 0))) goto Node_14_1190;
	goto Node_14_1192;
	Node_14_1190:;
	goto Node_14_1195;
	Node_14_1192:;
	return 0;
	Node_14_1195:;
	return -1073741808;
}
signed int IoDeleteSymbolicLink(signed int SymbolicLinkName) {
	signed int tmp_ndt_3;
	tmp_ndt_3 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_3);
	if (!((tmp_ndt_3 == 0))) goto Node_15_1209;
	goto Node_15_1211;
	Node_15_1209:;
	goto Node_15_1214;
	Node_15_1211:;
	return 0;
	Node_15_1214:;
	return -1073741823;
}
signed int FloppyPnpComplete(signed int DeviceObject, signed int Irp, signed int Context) {
	KeSetEvent(Context, 1, 0);
	return -1073741802;
}
void stub_driver_init() {
	s = NP;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	goto Node_17_1234;
	Node_17_1234:;
	// End of Function
}
void FloppyProcessQueuedRequests(signed int DisketteExtension) {
	goto Node_19_1282;
	Node_19_1282:;
	// End of Function
}
void IofCompleteRequest(signed int Irp, signed int PriorityBoost) {
	if (!((s == NP))) goto Node_20_1286;
	s = DC;
	goto Node_20_1287;
	Node_20_1286:;
	errorFn();
	Node_20_1287:;
	goto Node_20_1289;
	Node_20_1289:;
	// End of Function
}
void reach_error() {
	if (!(FALSE)) __CPROVER_printf("violated property: Node_21_1290");
	assert(FALSE);
	// End of Function
}
signed int FlAcpiConfigureFloppy(signed int DisketteExtension, signed int FdcInfo) {
	return 0;
}
signed int IoSetDeviceInterfaceState(signed int SymbolicLinkName, signed int Enable) {
	signed int tmp_ndt_6;
	tmp_ndt_6 = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__test_case:%d", tmp_ndt_6);
	if (!((tmp_ndt_6 == 0))) goto Node_23_1300;
	goto Node_23_1302;
	Node_23_1300:;
	goto Node_23_1305;
	Node_23_1302:;
	return 0;
	Node_23_1305:;
	return -1073741823;
}
void errorFn() {
	reach_error();
	abort();
}
void stubMoreProcessingRequired() {
	if (!((s == NP))) goto Node_25_1321;
	s = MPR1;
	goto Node_25_1322;
	Node_25_1321:;
	errorFn();
	Node_25_1322:;
	goto Node_25_1324;
	Node_25_1324:;
	// End of Function
}
void _BLAST_init() {
	UNLOADED = 0;
	NP = 1;
	DC = 2;
	SKIP1 = 3;
	SKIP2 = 4;
	MPR1 = 5;
	MPR3 = 6;
	IPC = 7;
	s = UNLOADED;
	pended = 0;
	compRegistered = 0;
	lowerDriverReturn = 0;
	setEventCalled = 0;
	customIrp = 0;
	goto Node_26_1340;
	Node_26_1340:;
	// End of Function
}
signed int __iv__ObReferenceObjectByHandle_stub(signed int Handle, signed int DesiredAccess, signed int ObjectType, signed int AccessMode, signed int Object, signed int HandleInformation){
	__CPROVER_printf("__iv__stub_call:ObReferenceObjectByHandle");
	signed int __iv__return_expr_ObReferenceObjectByHandle = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_ObReferenceObjectByHandle == -1073741823 || __iv__return_expr_ObReferenceObjectByHandle == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_ObReferenceObjectByHandle=%d", __iv__return_expr_ObReferenceObjectByHandle);
	return __iv__return_expr_ObReferenceObjectByHandle;
}
signed int __iv__IoQueryDeviceDescription_stub(signed int BusType, signed int BusNumber, signed int ControllerType, signed int ControllerNumber, signed int PeripheralType, signed int PeripheralNumber, signed int CalloutRoutine, signed int Context){
	__CPROVER_printf("__iv__stub_call:IoQueryDeviceDescription");
	signed int __iv__return_expr_IoQueryDeviceDescription = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_IoQueryDeviceDescription == -1073741823 || __iv__return_expr_IoQueryDeviceDescription == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_IoQueryDeviceDescription=%d", __iv__return_expr_IoQueryDeviceDescription);
	return __iv__return_expr_IoQueryDeviceDescription;
}
signed int __iv__ZwClose_stub(signed int Handle){
	__CPROVER_printf("__iv__stub_call:ZwClose");
	signed int __iv__return_expr_ZwClose = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_ZwClose == -1073741823 || __iv__return_expr_ZwClose == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_ZwClose=%d", __iv__return_expr_ZwClose);
	return __iv__return_expr_ZwClose;
}
signed int __iv__IoRegisterDeviceInterface_stub(signed int PhysicalDeviceObject, signed int InterfaceClassGuid, signed int ReferenceString, signed int SymbolicLinkName){
	__CPROVER_printf("__iv__stub_call:IoRegisterDeviceInterface");
	signed int __iv__return_expr_IoRegisterDeviceInterface = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_IoRegisterDeviceInterface == -1073741808 || __iv__return_expr_IoRegisterDeviceInterface == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_IoRegisterDeviceInterface=%d", __iv__return_expr_IoRegisterDeviceInterface);
	return __iv__return_expr_IoRegisterDeviceInterface;
}
signed int __iv__IoSetDeviceInterfaceState_stub(signed int SymbolicLinkName, signed int Enable){
	__CPROVER_printf("__iv__stub_call:IoSetDeviceInterfaceState");
	signed int __iv__return_expr_IoSetDeviceInterfaceState = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_IoSetDeviceInterfaceState == -1073741823 || __iv__return_expr_IoSetDeviceInterfaceState == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_IoSetDeviceInterfaceState=%d", __iv__return_expr_IoSetDeviceInterfaceState);
	return __iv__return_expr_IoSetDeviceInterfaceState;
}
signed int __iv__IoBuildDeviceIoControlRequest_stub(signed int IoControlCode, signed int DeviceObject, signed int InputBuffer, signed int InputBufferLength, signed int OutputBuffer, signed int OutputBufferLength, signed int InternalDeviceIoControl, signed int Event, signed int IoStatusBlock){
	__CPROVER_printf("__iv__stub_call:IoBuildDeviceIoControlRequest");
	customIrp = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(customIrp == 1);
	signed int __iv__return_expr_IoBuildDeviceIoControlRequest = __VERIFIER_nondet_signed_int();
	__CPROVER_printf("__iv__stub_output:customIrp=%d", customIrp);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_IoBuildDeviceIoControlRequest=%d", __iv__return_expr_IoBuildDeviceIoControlRequest);
	return __iv__return_expr_IoBuildDeviceIoControlRequest;
}
signed int __iv__IoDeleteSymbolicLink_stub(signed int SymbolicLinkName){
	__CPROVER_printf("__iv__stub_call:IoDeleteSymbolicLink");
	signed int __iv__return_expr_IoDeleteSymbolicLink = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_IoDeleteSymbolicLink == -1073741823 || __iv__return_expr_IoDeleteSymbolicLink == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_IoDeleteSymbolicLink=%d", __iv__return_expr_IoDeleteSymbolicLink);
	return __iv__return_expr_IoDeleteSymbolicLink;
}
signed int __iv__PsCreateSystemThread_stub(signed int ThreadHandle, signed int DesiredAccess, signed int ObjectAttributes, signed int ProcessHandle, signed int ClientId, signed int StartRoutine, signed int StartContext){
	__CPROVER_printf("__iv__stub_call:PsCreateSystemThread");
	signed int __iv__return_expr_PsCreateSystemThread = __VERIFIER_nondet_signed_int();
	__CPROVER_assume(__iv__return_expr_PsCreateSystemThread == -1073741823 || __iv__return_expr_PsCreateSystemThread == 0);
	__CPROVER_printf("__iv__stub_output:__iv__return_expr_PsCreateSystemThread=%d", __iv__return_expr_PsCreateSystemThread);
	return __iv__return_expr_PsCreateSystemThread;
}
