#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#define __CPROVER_assume(a) if (!(a)) exit(0)
typedef _Bool __CPROVER_bool;
FILE *__iv__fp;
#include <assert.h>
#ifndef NULL
#define NULL ((void*)0)
#endif
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
enum anonymous { INIT=0, IDLE=1, RUN=2, STOP=3, EMERGENCY=-1 };
struct comedi_t;
enum tag_elev_lamp_type { BUTTON_CALL_UP=0, BUTTON_CALL_DOWN=1, BUTTON_COMMAND=2 };
enum tag_elev_motor_direction { DIRN_DOWN=-1, DIRN_STOP=0, DIRN_UP=1 };
typedef signed long int clock_t;
typedef struct comedi_t comedi_t;
typedef enum anonymous elevState;
typedef enum tag_elev_lamp_type elev_button_type_t;
typedef enum tag_elev_motor_direction elev_motor_direction_t;
void check_property();
clock_t clock();
void comedi_data_read(comedi_t *comedi_data_read__it_g, signed int port, signed int channel, signed int i, signed int j, signed int *data);
void comedi_data_write(comedi_t *comedi_data_write__it_g, signed int port, signed int channel, signed int i, signed int j, signed int mode);
signed int comedi_dio_config(comedi_t *comedi_dio_config__it_g, signed int port, signed int i, signed int mode);
void comedi_dio_read(comedi_t *comedi_dio_read__it_g, signed int port, signed int i, signed int *data);
void comedi_dio_write(comedi_t *comedi_dio_write__it_g, signed int port, signed int i, signed int mode);
comedi_t * comedi_open( char *src);
signed int elev_get_button_signal(elev_button_type_t button, signed int floor);
signed int elev_get_floor_sensor_signal(void);
signed int elev_get_obstruction_signal(void);
signed int elev_get_stop_signal(void);
signed int elev_init(void);
void elev_set_button_lamp(elev_button_type_t button, signed int floor, signed int value);
void elev_set_door_open_lamp(signed int value);
void elev_set_floor_indicator(signed int floor);
void elev_set_motor_direction(elev_motor_direction_t dirn);
void elev_set_stop_lamp(signed int value);
signed int emergencyStopHandler();
signed int floorIsOrdered(signed int floorNum, signed int motorDir);
void flushOrders();
signed int getTimerStatus();
void initStates();
void io_clear_bit(signed int channel);
signed int io_init();
signed int io_read_analog(signed int channel);
signed int io_read_bit(signed int channel);
void io_set_bit(signed int channel);
void io_write_analog(signed int channel, signed int value);
signed int isButtonPressed();
signed int isTimerActive();
void removeFromOrderMatrix(signed int floorNum);
signed int setDirection(signed int currentFloor, signed int lastDirection);
void setOrdersHigh();
void startTimer(double length);
void stateController();
void timerDeactivate();
void update_prop_automata();
struct comedi_t
{
  char stub;
};
static  signed int button_channel_matrix[4l][3l]={ { 0x300 + 17, -1, 0x300 + 21 }, { 0x300 + 16, 0x200 + 0, 0x300 + 20 }, { 0x200 + 1, 0x200 + 2, 0x300 + 19 }, { -1, 0x200 + 3, 0x300 + 18 } };
signed int currentFloorLocation=-1;
elevState currentState=/*enum*/INIT;
signed int dstFloor;
static double duration;
signed long int elev_clock=0l;
signed int elev_floor;
signed int elev_motor;
static comedi_t *it_g=((comedi_t *)NULL);
signed int lastFloorAfterEmergency=-1;
signed int motorDirection=0;
signed int myFloor;
signed int orderMatrix[3l][4l]={ { 0, 0, 0, 0 }, { 0, 0, 0, 0 }, { 0, 0, 0, 0 } };
signed int __VERIFIER_nondet_signed_int(){ signed int __iv_temp; if (-1 == fscanf(__iv__fp, "%d", &__iv_temp)) exit(0); return __iv_temp; }
signed int previousMainFloor=-1;
elevState previousState=/*enum*/INIT;
signed int state=0;
clock_t timer=0l;
static signed int timerActive=0;
static clock_t timerStarted;
__CPROVER_bool __iv__branch_expr;
int __iv__return_expr_main;
signed int __iv__return_expr_elev_init;
signed int __iv__return_expr_elev_get_floor_sensor_signal;
signed int __iv__return_expr_comedi_dio_config;
signed int __iv__return_expr_emergencyStopHandler;
signed int __iv__return_expr_elev_get_stop_signal;
signed int __iv__return_expr_setDirection;
signed int __iv__return_expr_isButtonPressed;
signed int __iv__return_expr_io_read_bit;
signed int __iv__return_expr_io_init;
signed int __iv__return_expr_getTimerStatus;
signed int __iv__return_expr_floorIsOrdered;
signed int __iv__return_expr_isTimerActive;
signed int __iv__return_expr_elev_get_button_signal;
comedi_t* __iv__return_expr_comedi_open;
clock_t __iv__return_expr_clock;
signed int __iv__return_expr_io_read_analog;
signed int __iv__return_expr_elev_get_obstruction_signal;
signed int __iv__floorIsOrdered_stub(signed int floorNum, signed int motorDir);
signed int __iv__elev_get_button_signal_stub(elev_button_type_t button, signed int floor);
signed int __iv__isButtonPressed_stub();
int main(int argc, char* argv[]) {
	__iv__fp = fopen(argv[1], "r");
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:0;\n");fflush(stdout);
		myFloor = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_0_0;_tr_assign:myFloor=%d;\n", myFloor);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:1;\n");fflush(stdout);
	__CPROVER_assume(((0 <= myFloor) && (myFloor <= 3)));
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:2;\n");fflush(stdout);
		dstFloor = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_0_2;_tr_assign:dstFloor=%d;\n", dstFloor);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:3;\n");fflush(stdout);
	__CPROVER_assume(((0 <= dstFloor) && (dstFloor <= 3)));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:4;\n");fflush(stdout);
	__CPROVER_assume((myFloor != dstFloor));
	printf("_tr_node_id:Node_0_5;_tr_decl:return_value_elev_init;\n");fflush(stdout);
	signed int return_value_elev_init;
	printf("_tr_call:elev_init;_tr_call_id:5;\n");fflush(stdout);
		return_value_elev_init = elev_init();
	printf("_tr_node_id:Node_0_7;_tr_assign:return_value_elev_init=%d;\n", return_value_elev_init);fflush(stdout);
	__iv__branch_expr = (return_value_elev_init == 0);
	printf("_tr_node_id:Node_0_9;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_elev_init == 0)) goto Node_0_17;
	printf("_tr_call:initStates;_tr_call_id:6;\n");fflush(stdout);
	initStates();
	Node_0_11:;
	__iv__branch_expr = !((1 != 0));
	printf("_tr_node_id:Node_0_11;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((1 != 0))) goto Node_0_16;
	printf("_tr_call:stateController;_tr_call_id:7;\n");fflush(stdout);
	stateController();
	printf("_tr_call:update_prop_automata;_tr_call_id:8;\n");fflush(stdout);
	update_prop_automata();
	printf("_tr_call:check_property;_tr_call_id:9;\n");fflush(stdout);
	check_property();
	goto Node_0_11;
	Node_0_16:;
	Node_0_17:;
	printf("_tr_return;\n");fflush(stdout);
}
void initStates() {
	printf("_tr_node_id:Node_1_22;_tr_decl:return_value_elev_get_floor_sensor_signal_0;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal_0;
	printf("_tr_node_id:Node_1_23;_tr_decl:return_value_elev_get_floor_sensor_signal;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal;
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:11;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal_0 = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_1_25;_tr_assign:return_value_elev_get_floor_sensor_signal_0=%d;\n", return_value_elev_get_floor_sensor_signal_0);fflush(stdout);
	__iv__branch_expr = !((return_value_elev_get_floor_sensor_signal_0 == -1));
	printf("_tr_node_id:Node_1_27;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_elev_get_floor_sensor_signal_0 == -1))) goto Node_1_35;
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:12;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(1));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(1));
	Node_1_29:;
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:13;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_1_29;_tr_assign:return_value_elev_get_floor_sensor_signal=%d;\n", return_value_elev_get_floor_sensor_signal);fflush(stdout);
	__iv__branch_expr = !((return_value_elev_get_floor_sensor_signal == -1));
	printf("_tr_node_id:Node_1_30;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_elev_get_floor_sensor_signal == -1))) goto Node_1_34;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_1_33;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_1_29;
	Node_1_34:;
	Node_1_35:;
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:14;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(0));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(0));
		previousState = (elevState)(1);
	printf("_tr_node_id:Node_1_37;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
		currentState = (elevState)(1);
	printf("_tr_node_id:Node_1_38;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
signed int elev_init() {
	printf("_tr_node_id:Node_2_43;_tr_decl:i;\n");fflush(stdout);
	signed int i;
	printf("_tr_node_id:Node_2_44;_tr_decl:return_value_io_init;\n");fflush(stdout);
	signed int return_value_io_init;
	printf("_tr_call:io_init;_tr_call_id:15;\n");fflush(stdout);
		return_value_io_init = io_init();
	printf("_tr_node_id:Node_2_46;_tr_assign:return_value_io_init=%d;\n", return_value_io_init);fflush(stdout);
	__iv__branch_expr = !((return_value_io_init == 0));
	printf("_tr_node_id:Node_2_48;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_io_init == 0))) goto Node_2_55;
	__iv__return_expr_elev_init = 	0;
	printf("_tr_node_id:Node_2_49;_tr_assign:__iv__return_expr_elev_init=%d;\n", __iv__return_expr_elev_init);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_init;
	Node_2_55:;
		i = 0;
	printf("_tr_node_id:Node_2_55;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_2_57:;
	__iv__branch_expr = (i >= 4);
	printf("_tr_node_id:Node_2_57;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 4)) goto Node_2_67;
	__iv__branch_expr = (i == 0);
	printf("_tr_node_id:Node_2_58;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i == 0)) goto Node_2_60;
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:16;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(1));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", i);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 0);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(1), i, 0);
	Node_2_60:;
	__iv__branch_expr = (i == 3);
	printf("_tr_node_id:Node_2_61;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i == 3)) goto Node_2_63;
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:17;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(0));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", i);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 0);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(0), i, 0);
	Node_2_63:;
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:18;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(2));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", i);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 0);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(2), i, 0);
		i = (i + 1);
	printf("_tr_node_id:Node_2_65;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_2_57;
	Node_2_67:;
	printf("_tr_call:elev_set_floor_indicator;_tr_call_id:19;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", 0);fflush(stdout);
	elev_set_floor_indicator(0);
	__iv__return_expr_elev_init = 	1;
	printf("_tr_node_id:Node_2_69;_tr_assign:__iv__return_expr_elev_init=%d;\n", __iv__return_expr_elev_init);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_init;
}
signed int elev_get_floor_sensor_signal() {
	printf("_tr_node_id:Node_3_80;_tr_decl:return_value_isTimerActive;\n");fflush(stdout);
	signed int return_value_isTimerActive;
	printf("_tr_call:isTimerActive;_tr_call_id:20;\n");fflush(stdout);
		return_value_isTimerActive = isTimerActive();
	printf("_tr_node_id:Node_3_82;_tr_assign:return_value_isTimerActive=%d;\n", return_value_isTimerActive);fflush(stdout);
	__iv__branch_expr = (return_value_isTimerActive == 0);
	printf("_tr_node_id:Node_3_84;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_isTimerActive == 0)) goto Node_3_111;
	__iv__branch_expr = (elev_motor == 0);
	printf("_tr_node_id:Node_3_85;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((elev_motor == 0)) goto Node_3_110;
	printf("_tr_node_id:Node_3_86;_tr_decl:return_value_getTimerStatus;\n");fflush(stdout);
	signed int return_value_getTimerStatus;
	printf("_tr_call:getTimerStatus;_tr_call_id:21;\n");fflush(stdout);
		return_value_getTimerStatus = getTimerStatus();
	printf("_tr_node_id:Node_3_88;_tr_assign:return_value_getTimerStatus=%d;\n", return_value_getTimerStatus);fflush(stdout);
	__iv__branch_expr = (return_value_getTimerStatus == 0);
	printf("_tr_node_id:Node_3_90;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_getTimerStatus == 0)) goto Node_3_101;
	printf("_tr_call:timerDeactivate;_tr_call_id:22;\n");fflush(stdout);
	timerDeactivate();
		elev_floor = (elev_floor + elev_motor);
	printf("_tr_node_id:Node_3_92;_tr_assign:elev_floor=%d;\n", elev_floor);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:23;\n");fflush(stdout);
	__CPROVER_assume(((0 <= elev_floor) && (elev_floor < 4)));
	__iv__return_expr_elev_get_floor_sensor_signal = 	elev_floor;
	printf("_tr_node_id:Node_3_94;_tr_assign:__iv__return_expr_elev_get_floor_sensor_signal=%d;\n", __iv__return_expr_elev_get_floor_sensor_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_floor_sensor_signal;
	Node_3_101:;
	__iv__return_expr_elev_get_floor_sensor_signal = 	-1;
	printf("_tr_node_id:Node_3_101;_tr_assign:__iv__return_expr_elev_get_floor_sensor_signal=%d;\n", __iv__return_expr_elev_get_floor_sensor_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_floor_sensor_signal;
	Node_3_110:;
	Node_3_111:;
	__iv__return_expr_elev_get_floor_sensor_signal = 	elev_floor;
	printf("_tr_node_id:Node_3_112;_tr_assign:__iv__return_expr_elev_get_floor_sensor_signal=%d;\n", __iv__return_expr_elev_get_floor_sensor_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_floor_sensor_signal;
}
signed int comedi_dio_config(comedi_t* comedi_dio_config__it_g, signed int port, signed int i, signed int mode) {
	printf("_tr_node_id:Node_4_117;_tr_decl:status;\n");fflush(stdout);
	signed int status;
	printf("_tr_node_id:Node_4_118;_tr_decl:return_value___VERIFIER_nondet_signed_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_signed_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:24;\n");fflush(stdout);
		return_value___VERIFIER_nondet_signed_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_4_121;_tr_assign:return_value___VERIFIER_nondet_signed_int=%d;\n", return_value___VERIFIER_nondet_signed_int);fflush(stdout);
		status = return_value___VERIFIER_nondet_signed_int;
	printf("_tr_node_id:Node_4_122;_tr_assign:status=%d;\n", status);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:25;\n");fflush(stdout);
	__CPROVER_assume(((0 <= status) && (status <= 1)));
	__iv__return_expr_comedi_dio_config = 	status;
	printf("_tr_node_id:Node_4_124;_tr_assign:__iv__return_expr_comedi_dio_config=%d;\n", __iv__return_expr_comedi_dio_config);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_comedi_dio_config;
}
void stateController() {
	printf("_tr_call:setOrdersHigh;_tr_call_id:26;\n");fflush(stdout);
	setOrdersHigh();
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:27;\n");fflush(stdout);
		currentFloorLocation = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_5_131;_tr_assign:currentFloorLocation=%d;\n", currentFloorLocation);fflush(stdout);
	printf("_tr_node_id:Node_5_132;_tr_decl:return_value_isButtonPressed;\n");fflush(stdout);
	signed int return_value_isButtonPressed;
	printf("_tr_node_id:Node_5_133;_tr_decl:return_value_floorIsOrdered;\n");fflush(stdout);
	signed int return_value_floorIsOrdered;
	printf("_tr_node_id:Node_5_134;_tr_decl:return_value_isTimerActive;\n");fflush(stdout);
	signed int return_value_isTimerActive;
	printf("_tr_node_id:Node_5_135;_tr_decl:return_value_elev_get_floor_sensor_signal;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal;
	printf("_tr_node_id:Node_5_136;_tr_decl:return_value_isTimerActive_0;\n");fflush(stdout);
	signed int return_value_isTimerActive_0;
	printf("_tr_node_id:Node_5_137;_tr_decl:return_value_getTimerStatus;\n");fflush(stdout);
	signed int return_value_getTimerStatus;
	__iv__branch_expr = !((!((currentFloorLocation == -1)) || !((lastFloorAfterEmergency == -1))));
	printf("_tr_node_id:Node_5_138;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((!((currentFloorLocation == -1)) || !((lastFloorAfterEmergency == -1))))) goto Node_5_196;
	__iv__branch_expr = (lastFloorAfterEmergency == -1);
	printf("_tr_node_id:Node_5_139;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((lastFloorAfterEmergency == -1)) goto Node_5_142;
		previousMainFloor = lastFloorAfterEmergency;
	printf("_tr_node_id:Node_5_140;_tr_assign:previousMainFloor=%d;\n", previousMainFloor);fflush(stdout);
	goto Node_5_143;
	Node_5_142:;
		previousMainFloor = currentFloorLocation;
	printf("_tr_node_id:Node_5_142;_tr_assign:previousMainFloor=%d;\n", previousMainFloor);fflush(stdout);
	Node_5_143:;
	printf("_tr_call:elev_set_floor_indicator;_tr_call_id:28;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", previousMainFloor);fflush(stdout);
	elev_set_floor_indicator(previousMainFloor);
	__iv__branch_expr = ((signed int)(previousState) == 0);
	printf("_tr_node_id:Node_5_146;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(previousState) == 0)) goto Node_5_152;
	__iv__branch_expr = ((signed int)(previousState) == 1);
	printf("_tr_node_id:Node_5_147;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(previousState) == 1)) goto Node_5_153;
	__iv__branch_expr = ((signed int)(previousState) == 2);
	printf("_tr_node_id:Node_5_148;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(previousState) == 2)) goto Node_5_160;
	__iv__branch_expr = ((signed int)(previousState) == 3);
	printf("_tr_node_id:Node_5_149;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(previousState) == 3)) goto Node_5_166;
	__iv__branch_expr = ((signed int)(previousState) == -1);
	printf("_tr_node_id:Node_5_150;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(previousState) == -1)) goto Node_5_194;
	goto Node_5_195;
	Node_5_152:;
	goto Node_5_195;
	Node_5_153:;
	printf("_tr_call:__iv__isButtonPressed_stub;_tr_call_id:29;\n");fflush(stdout);
		return_value_isButtonPressed = __iv__isButtonPressed_stub();
	printf("_tr_node_id:Node_5_153;_tr_assign:return_value_isButtonPressed=%d;\n", return_value_isButtonPressed);fflush(stdout);
	__iv__branch_expr = (return_value_isButtonPressed == 0);
	printf("_tr_node_id:Node_5_154;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_isButtonPressed == 0)) goto Node_5_158;
	printf("_tr_call:setDirection;_tr_call_id:30;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:currentFloor=%d;\n", previousMainFloor);fflush(stdout);
	printf("_tr_param;_tr_assign:lastDirection=%d;\n", motorDirection);fflush(stdout);
		motorDirection = setDirection(previousMainFloor, motorDirection);
	printf("_tr_node_id:Node_5_155;_tr_assign:motorDirection=%d;\n", motorDirection);fflush(stdout);
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:31;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(motorDirection));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(motorDirection));
		previousState = (elevState)(2);
	printf("_tr_node_id:Node_5_157;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
	Node_5_158:;
	goto Node_5_195;
	Node_5_160:;
	printf("_tr_call:__iv__floorIsOrdered_stub;_tr_call_id:32;\n");fflush(stdout);
		return_value_floorIsOrdered = __iv__floorIsOrdered_stub(previousMainFloor, motorDirection);
	printf("_tr_node_id:Node_5_160;_tr_assign:return_value_floorIsOrdered=%d;\n", return_value_floorIsOrdered);fflush(stdout);
	__iv__branch_expr = (return_value_floorIsOrdered == 0);
	printf("_tr_node_id:Node_5_161;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_floorIsOrdered == 0)) goto Node_5_163;
		previousState = (elevState)(3);
	printf("_tr_node_id:Node_5_162;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
	Node_5_163:;
		lastFloorAfterEmergency = -1;
	printf("_tr_node_id:Node_5_164;_tr_assign:lastFloorAfterEmergency=%d;\n", lastFloorAfterEmergency);fflush(stdout);
	goto Node_5_195;
	Node_5_166:;
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:33;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(0));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(0));
		motorDirection = 0;
	printf("_tr_node_id:Node_5_167;_tr_assign:motorDirection=%d;\n", motorDirection);fflush(stdout);
	printf("_tr_call:isTimerActive;_tr_call_id:34;\n");fflush(stdout);
		return_value_isTimerActive = isTimerActive();
	printf("_tr_node_id:Node_5_168;_tr_assign:return_value_isTimerActive=%d;\n", return_value_isTimerActive);fflush(stdout);
	__iv__branch_expr = !((return_value_isTimerActive == 0));
	printf("_tr_node_id:Node_5_169;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_isTimerActive == 0))) goto Node_5_174;
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:35;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_5_170;_tr_assign:return_value_elev_get_floor_sensor_signal=%d;\n", return_value_elev_get_floor_sensor_signal);fflush(stdout);
	__iv__branch_expr = (return_value_elev_get_floor_sensor_signal == -1);
	printf("_tr_node_id:Node_5_171;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_elev_get_floor_sensor_signal == -1)) goto Node_5_173;
	printf("_tr_call:startTimer;_tr_call_id:36;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:length=%lf;\n", 3.0);fflush(stdout);
	startTimer(3.0);
	Node_5_173:;
	Node_5_174:;
	printf("_tr_call:isTimerActive;_tr_call_id:37;\n");fflush(stdout);
		return_value_isTimerActive_0 = isTimerActive();
	printf("_tr_node_id:Node_5_175;_tr_assign:return_value_isTimerActive_0=%d;\n", return_value_isTimerActive_0);fflush(stdout);
	__iv__branch_expr = !((return_value_isTimerActive_0 == 1));
	printf("_tr_node_id:Node_5_176;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_isTimerActive_0 == 1))) goto Node_5_187;
	printf("_tr_node_id:Node_5_177;_tr_decl:return_value_floorIsOrdered_0;\n");fflush(stdout);
	signed int return_value_floorIsOrdered_0;
	printf("_tr_call:__iv__floorIsOrdered_stub;_tr_call_id:38;\n");fflush(stdout);
		return_value_floorIsOrdered_0 = __iv__floorIsOrdered_stub(previousMainFloor, motorDirection);
	printf("_tr_node_id:Node_5_180;_tr_assign:return_value_floorIsOrdered_0=%d;\n", return_value_floorIsOrdered_0);fflush(stdout);
	__iv__branch_expr = (return_value_floorIsOrdered_0 == 0);
	printf("_tr_node_id:Node_5_181;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_floorIsOrdered_0 == 0)) goto Node_5_184;
	printf("_tr_call:startTimer;_tr_call_id:39;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:length=%lf;\n", 3.0);fflush(stdout);
	startTimer(3.0);
	printf("_tr_call:removeFromOrderMatrix;_tr_call_id:40;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:floorNum=%d;\n", previousMainFloor);fflush(stdout);
	removeFromOrderMatrix(previousMainFloor);
	Node_5_184:;
	Node_5_187:;
	printf("_tr_call:getTimerStatus;_tr_call_id:41;\n");fflush(stdout);
		return_value_getTimerStatus = getTimerStatus();
	printf("_tr_node_id:Node_5_188;_tr_assign:return_value_getTimerStatus=%d;\n", return_value_getTimerStatus);fflush(stdout);
	__iv__branch_expr = (return_value_getTimerStatus == 0);
	printf("_tr_node_id:Node_5_189;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_getTimerStatus == 0)) goto Node_5_192;
		previousState = (elevState)(1);
	printf("_tr_node_id:Node_5_190;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
	printf("_tr_call:timerDeactivate;_tr_call_id:42;\n");fflush(stdout);
	timerDeactivate();
	Node_5_192:;
	goto Node_5_195;
	Node_5_194:;
	Node_5_195:;
	Node_5_196:;
	printf("_tr_node_id:Node_5_197;_tr_decl:return_value_elev_get_stop_signal;\n");fflush(stdout);
	signed int return_value_elev_get_stop_signal;
	printf("_tr_call:elev_get_stop_signal;_tr_call_id:43;\n");fflush(stdout);
		return_value_elev_get_stop_signal = elev_get_stop_signal();
	printf("_tr_node_id:Node_5_199;_tr_assign:return_value_elev_get_stop_signal=%d;\n", return_value_elev_get_stop_signal);fflush(stdout);
	__iv__branch_expr = (return_value_elev_get_stop_signal == 0);
	printf("_tr_node_id:Node_5_201;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_elev_get_stop_signal == 0)) goto Node_5_215;
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:44;\n");fflush(stdout);
	__CPROVER_assume((0 != 0));
	printf("_tr_node_id:Node_5_203;_tr_decl:return_value_emergencyStopHandler;\n");fflush(stdout);
	signed int return_value_emergencyStopHandler;
	printf("_tr_call:emergencyStopHandler;_tr_call_id:45;\n");fflush(stdout);
		return_value_emergencyStopHandler = emergencyStopHandler();
	printf("_tr_node_id:Node_5_205;_tr_assign:return_value_emergencyStopHandler=%d;\n", return_value_emergencyStopHandler);fflush(stdout);
	__iv__branch_expr = !((return_value_emergencyStopHandler == -1));
	printf("_tr_node_id:Node_5_207;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_emergencyStopHandler == -1))) goto Node_5_211;
		previousState = (elevState)(1);
	printf("_tr_node_id:Node_5_208;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
		lastFloorAfterEmergency = previousMainFloor;
	printf("_tr_node_id:Node_5_209;_tr_assign:lastFloorAfterEmergency=%d;\n", lastFloorAfterEmergency);fflush(stdout);
	goto Node_5_212;
	Node_5_211:;
		previousState = (elevState)(3);
	printf("_tr_node_id:Node_5_211;_tr_assign:previousState=%d;\n", previousState);fflush(stdout);
	Node_5_212:;
	Node_5_215:;
		elev_clock = (elev_clock + 1l);
	printf("_tr_node_id:Node_5_216;_tr_assign:elev_clock=%ld;\n", elev_clock);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
signed int emergencyStopHandler() {
	printf("_tr_node_id:Node_6_226;_tr_decl:return_value_elev_get_floor_sensor_signal;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal;
	printf("_tr_node_id:Node_6_227;_tr_decl:return_value_elev_get_stop_signal;\n");fflush(stdout);
	signed int return_value_elev_get_stop_signal;
	printf("_tr_node_id:Node_6_228;_tr_decl:return_value_elev_get_floor_sensor_signal_0;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal_0;
	__iv__branch_expr = ((signed int)(currentState) == 0);
	printf("_tr_node_id:Node_6_230;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(currentState) == 0)) goto Node_6_236;
	__iv__branch_expr = ((signed int)(currentState) == 1);
	printf("_tr_node_id:Node_6_231;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(currentState) == 1)) goto Node_6_241;
	__iv__branch_expr = ((signed int)(currentState) == 2);
	printf("_tr_node_id:Node_6_232;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(currentState) == 2)) goto Node_6_244;
	__iv__branch_expr = ((signed int)(currentState) == 3);
	printf("_tr_node_id:Node_6_233;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(currentState) == 3)) goto Node_6_251;
	__iv__branch_expr = ((signed int)(currentState) == -1);
	printf("_tr_node_id:Node_6_234;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(currentState) == -1)) goto Node_6_254;
	goto Node_6_278;
	Node_6_236:;
	__iv__return_expr_emergencyStopHandler = 	0;
	printf("_tr_node_id:Node_6_236;_tr_assign:__iv__return_expr_emergencyStopHandler=%d;\n", __iv__return_expr_emergencyStopHandler);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_emergencyStopHandler;
	Node_6_241:;
		currentState = (elevState)(-1);
	printf("_tr_node_id:Node_6_241;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:46;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(0));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(0));
	goto Node_6_278;
	Node_6_244:;
		currentState = (elevState)(-1);
	printf("_tr_node_id:Node_6_244;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:47;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(0));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(0));
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:48;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_6_246;_tr_assign:return_value_elev_get_floor_sensor_signal=%d;\n", return_value_elev_get_floor_sensor_signal);fflush(stdout);
	__iv__branch_expr = !((return_value_elev_get_floor_sensor_signal == -1));
	printf("_tr_node_id:Node_6_247;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_elev_get_floor_sensor_signal == -1))) goto Node_6_249;
		currentState = (elevState)(1);
	printf("_tr_node_id:Node_6_248;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	Node_6_249:;
	goto Node_6_278;
	Node_6_251:;
		currentState = (elevState)(-1);
	printf("_tr_node_id:Node_6_251;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
		currentState = (elevState)(1);
	printf("_tr_node_id:Node_6_252;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	goto Node_6_278;
	Node_6_254:;
	printf("_tr_call:flushOrders;_tr_call_id:49;\n");fflush(stdout);
	flushOrders();
	printf("_tr_call:elev_set_motor_direction;_tr_call_id:50;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:dirn=%d;\n", (elev_motor_direction_t)(0));fflush(stdout);
	elev_set_motor_direction((elev_motor_direction_t)(0));
	Node_6_256:;
	printf("_tr_call:elev_get_stop_signal;_tr_call_id:51;\n");fflush(stdout);
		return_value_elev_get_stop_signal = elev_get_stop_signal();
	printf("_tr_node_id:Node_6_256;_tr_assign:return_value_elev_get_stop_signal=%d;\n", return_value_elev_get_stop_signal);fflush(stdout);
	__iv__branch_expr = (return_value_elev_get_stop_signal == 0);
	printf("_tr_node_id:Node_6_257;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_elev_get_stop_signal == 0)) goto Node_6_261;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_6_260;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_6_256;
	Node_6_261:;
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:52;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal_0 = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_6_262;_tr_assign:return_value_elev_get_floor_sensor_signal_0=%d;\n", return_value_elev_get_floor_sensor_signal_0);fflush(stdout);
	__iv__branch_expr = !((return_value_elev_get_floor_sensor_signal_0 == -1));
	printf("_tr_node_id:Node_6_263;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_elev_get_floor_sensor_signal_0 == -1))) goto Node_6_271;
		currentState = (elevState)(1);
	printf("_tr_node_id:Node_6_264;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	__iv__return_expr_emergencyStopHandler = 	-1;
	printf("_tr_node_id:Node_6_265;_tr_assign:__iv__return_expr_emergencyStopHandler=%d;\n", __iv__return_expr_emergencyStopHandler);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_emergencyStopHandler;
	Node_6_271:;
		currentState = (elevState)(3);
	printf("_tr_node_id:Node_6_271;_tr_assign:currentState=%d;\n", currentState);fflush(stdout);
	__iv__return_expr_emergencyStopHandler = 	1;
	printf("_tr_node_id:Node_6_272;_tr_assign:__iv__return_expr_emergencyStopHandler=%d;\n", __iv__return_expr_emergencyStopHandler);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_emergencyStopHandler;
	Node_6_278:;
	__iv__return_expr_emergencyStopHandler = 	-1;
	printf("_tr_node_id:Node_6_279;_tr_assign:__iv__return_expr_emergencyStopHandler=%d;\n", __iv__return_expr_emergencyStopHandler);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_emergencyStopHandler;
}
signed int elev_get_stop_signal() {
	printf("_tr_node_id:Node_7_290;_tr_decl:return_value_io_read_bit;\n");fflush(stdout);
	signed int return_value_io_read_bit;
	printf("_tr_call:io_read_bit;_tr_call_id:53;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:channel=%d;\n", (0x300 + 22));fflush(stdout);
		return_value_io_read_bit = io_read_bit((0x300 + 22));
	printf("_tr_node_id:Node_7_292;_tr_assign:return_value_io_read_bit=%d;\n", return_value_io_read_bit);fflush(stdout);
	__iv__return_expr_elev_get_stop_signal = 	return_value_io_read_bit;
	printf("_tr_node_id:Node_7_294;_tr_assign:__iv__return_expr_elev_get_stop_signal=%d;\n", __iv__return_expr_elev_get_stop_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_stop_signal;
}
void setOrdersHigh() {
	printf("_tr_node_id:Node_8_299;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_8_300;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_8_302:;
	__iv__branch_expr = (button >= 3);
	printf("_tr_node_id:Node_8_302;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 3)) goto Node_8_323;
	printf("_tr_node_id:Node_8_303;_tr_decl:floorNum;\n");fflush(stdout);
	signed int floorNum;
		floorNum = 0;
	printf("_tr_node_id:Node_8_304;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	Node_8_306:;
	__iv__branch_expr = (floorNum >= 4);
	printf("_tr_node_id:Node_8_306;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorNum >= 4)) goto Node_8_319;
	printf("_tr_node_id:Node_8_307;_tr_decl:return_value_elev_get_button_signal;\n");fflush(stdout);
	signed int return_value_elev_get_button_signal;
	printf("_tr_call:__iv__elev_get_button_signal_stub;_tr_call_id:54;\n");fflush(stdout);
		return_value_elev_get_button_signal = __iv__elev_get_button_signal_stub((elev_button_type_t)(button), floorNum);
	printf("_tr_node_id:Node_8_309;_tr_assign:return_value_elev_get_button_signal=%d;\n", return_value_elev_get_button_signal);fflush(stdout);
	__iv__branch_expr = (return_value_elev_get_button_signal == 0);
	printf("_tr_node_id:Node_8_311;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_elev_get_button_signal == 0)) goto Node_8_314;
	unsigned int __iv__index_expr_var0 = (unsigned) ((signed long int)(button));
	unsigned int __iv__index_expr_var1 = (unsigned) ((signed long int)(floorNum));
		orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] = 1;
	printf("_tr_node_id:Node_8_312;_tr_assign:orderMatrix[%u][%u]=%d;\n", __iv__index_expr_var0, __iv__index_expr_var1, orderMatrix[__iv__index_expr_var0][__iv__index_expr_var1]);fflush(stdout);
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:55;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(button));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", floorNum);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 1);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(button), floorNum, 1);
	Node_8_314:;
		floorNum = (floorNum + 1);
	printf("_tr_node_id:Node_8_317;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	goto Node_8_306;
	Node_8_319:;
		button = (button + 1);
	printf("_tr_node_id:Node_8_321;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_8_302;
	Node_8_323:;
	printf("_tr_return;\n");fflush(stdout);
}
signed int setDirection(signed int currentFloor, signed int lastDirection) {
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:56;\n");fflush(stdout);
	__CPROVER_assume((currentFloor >= 0));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:57;\n");fflush(stdout);
	__CPROVER_assume((currentFloor < 4));
	printf("_tr_node_id:Node_9_329;_tr_decl:return_value_elev_get_floor_sensor_signal;\n");fflush(stdout);
	signed int return_value_elev_get_floor_sensor_signal;
	printf("_tr_call:elev_get_floor_sensor_signal;_tr_call_id:58;\n");fflush(stdout);
		return_value_elev_get_floor_sensor_signal = elev_get_floor_sensor_signal();
	printf("_tr_node_id:Node_9_330;_tr_assign:return_value_elev_get_floor_sensor_signal=%d;\n", return_value_elev_get_floor_sensor_signal);fflush(stdout);
	__iv__branch_expr = !((return_value_elev_get_floor_sensor_signal == -1));
	printf("_tr_node_id:Node_9_332;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_elev_get_floor_sensor_signal == -1))) goto Node_9_334;
		currentFloor = (signed int)(((double)(currentFloor) + ((double)(lastDirection) / 2.0)));
	printf("_tr_node_id:Node_9_333;_tr_assign:currentFloor=%d;\n", currentFloor);fflush(stdout);
	Node_9_334:;
	printf("_tr_node_id:Node_9_335;_tr_decl:upOrders;\n");fflush(stdout);
	signed int upOrders;
		upOrders = 0;
	printf("_tr_node_id:Node_9_336;_tr_assign:upOrders=%d;\n", upOrders);fflush(stdout);
	printf("_tr_node_id:Node_9_337;_tr_decl:downOrders;\n");fflush(stdout);
	signed int downOrders;
		downOrders = 0;
	printf("_tr_node_id:Node_9_338;_tr_assign:downOrders=%d;\n", downOrders);fflush(stdout);
	printf("_tr_node_id:Node_9_339;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_9_340;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_9_342:;
	__iv__branch_expr = (button >= 3);
	printf("_tr_node_id:Node_9_342;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 3)) goto Node_9_360;
	printf("_tr_node_id:Node_9_343;_tr_decl:floorNum;\n");fflush(stdout);
	signed int floorNum;
		floorNum = 0;
	printf("_tr_node_id:Node_9_344;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	Node_9_346:;
	__iv__branch_expr = (floorNum >= 4);
	printf("_tr_node_id:Node_9_346;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorNum >= 4)) goto Node_9_356;
	__iv__branch_expr = !((orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_9_347;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] == 1))) goto Node_9_353;
	__iv__branch_expr = (currentFloor >= floorNum);
	printf("_tr_node_id:Node_9_348;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((currentFloor >= floorNum)) goto Node_9_351;
		upOrders = (upOrders + 1);
	printf("_tr_node_id:Node_9_349;_tr_assign:upOrders=%d;\n", upOrders);fflush(stdout);
	goto Node_9_352;
	Node_9_351:;
		downOrders = (downOrders + 1);
	printf("_tr_node_id:Node_9_351;_tr_assign:downOrders=%d;\n", downOrders);fflush(stdout);
	Node_9_352:;
	Node_9_353:;
		floorNum = (floorNum + 1);
	printf("_tr_node_id:Node_9_354;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	goto Node_9_346;
	Node_9_356:;
		button = (button + 1);
	printf("_tr_node_id:Node_9_358;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_9_342;
	Node_9_360:;
	__iv__branch_expr = (downOrders >= upOrders);
	printf("_tr_node_id:Node_9_361;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((downOrders >= upOrders)) goto Node_9_370;
	__iv__return_expr_setDirection = 	1;
	printf("_tr_node_id:Node_9_362;_tr_assign:__iv__return_expr_setDirection=%d;\n", __iv__return_expr_setDirection);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_setDirection;
	Node_9_370:;
	__iv__return_expr_setDirection = 	-1;
	printf("_tr_node_id:Node_9_370;_tr_assign:__iv__return_expr_setDirection=%d;\n", __iv__return_expr_setDirection);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_setDirection;
}
signed int isButtonPressed() {
	printf("_tr_node_id:Node_10_385;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_10_386;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_10_388:;
	__iv__branch_expr = (button >= 3);
	printf("_tr_node_id:Node_10_388;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 3)) goto Node_10_405;
	printf("_tr_node_id:Node_10_389;_tr_decl:floorNum;\n");fflush(stdout);
	signed int floorNum;
		floorNum = 0;
	printf("_tr_node_id:Node_10_390;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	Node_10_392:;
	__iv__branch_expr = (floorNum >= 4);
	printf("_tr_node_id:Node_10_392;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorNum >= 4)) goto Node_10_401;
	__iv__branch_expr = !((orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_10_393;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] == 1))) goto Node_10_398;
	__iv__return_expr_isButtonPressed = 	1;
	printf("_tr_node_id:Node_10_394;_tr_assign:__iv__return_expr_isButtonPressed=%d;\n", __iv__return_expr_isButtonPressed);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_isButtonPressed;
	Node_10_398:;
		floorNum = (floorNum + 1);
	printf("_tr_node_id:Node_10_399;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	goto Node_10_392;
	Node_10_401:;
		button = (button + 1);
	printf("_tr_node_id:Node_10_403;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_10_388;
	Node_10_405:;
	__iv__return_expr_isButtonPressed = 	0;
	printf("_tr_node_id:Node_10_406;_tr_assign:__iv__return_expr_isButtonPressed=%d;\n", __iv__return_expr_isButtonPressed);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_isButtonPressed;
}
signed int io_read_bit(signed int channel) {
	printf("_tr_node_id:Node_11_410;_tr_decl:data;\n");fflush(stdout);
	unsigned int data;
		data = 0u;
	printf("_tr_node_id:Node_11_411;_tr_assign:data=%u;\n", data);fflush(stdout);
	printf("_tr_call:comedi_dio_read;_tr_call_id:59;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:comedi_dio_read__it_g=it_g;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:port=%d;\n", (channel >> 8));fflush(stdout);
	printf("_tr_param;_tr_assign:i=%d;\n", (channel & 0xFF));fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:data=(signed int*)(&data);\n");fflush(stdout);
	comedi_dio_read(it_g, (channel >> 8), (channel & 0xFF), (signed int*)(&data));
	__iv__return_expr_io_read_bit = 	(signed int)(data);
	printf("_tr_node_id:Node_11_413;_tr_assign:__iv__return_expr_io_read_bit=%d;\n", __iv__return_expr_io_read_bit);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_io_read_bit;
}
signed int io_init() {
	printf("_tr_node_id:Node_12_417;_tr_decl:i;\n");fflush(stdout);
	signed int i;
	printf("_tr_node_id:Node_12_418;_tr_decl:status;\n");fflush(stdout);
	signed int status;
		status = 0;
	printf("_tr_node_id:Node_12_419;_tr_assign:status=%d;\n", status);fflush(stdout);
	printf("_tr_call:comedi_open;_tr_call_id:60;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:src=\"/dev/comedi0\";\n");fflush(stdout);
		it_g = comedi_open("/dev/comedi0");
	printf("_tr_node_id:Node_12_420;_tr_dynamic_assign:	it_g = comedi_open(\"/dev/comedi0\");\n");fflush(stdout);
	__iv__branch_expr = !((it_g == (comedi_t*)((void*)(0))));
	printf("_tr_node_id:Node_12_421;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((it_g == (comedi_t*)((void*)(0))))) goto Node_12_427;
	__iv__return_expr_io_init = 	0;
	printf("_tr_node_id:Node_12_422;_tr_assign:__iv__return_expr_io_init=%d;\n", __iv__return_expr_io_init);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_io_init;
	Node_12_427:;
		i = 0;
	printf("_tr_node_id:Node_12_427;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_12_429:;
	__iv__branch_expr = (i >= 8);
	printf("_tr_node_id:Node_12_429;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 8)) goto Node_12_460;
	printf("_tr_node_id:Node_12_430;_tr_decl:return_value_comedi_dio_config;\n");fflush(stdout);
	signed int return_value_comedi_dio_config;
	printf("_tr_call:comedi_dio_config;_tr_call_id:61;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:comedi_dio_config__it_g=it_g;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:port=%d;\n", 2);fflush(stdout);
	printf("_tr_param;_tr_assign:i=%d;\n", i);fflush(stdout);
	printf("_tr_param;_tr_assign:mode=%d;\n", 0);fflush(stdout);
		return_value_comedi_dio_config = comedi_dio_config(it_g, 2, i, 0);
	printf("_tr_node_id:Node_12_432;_tr_assign:return_value_comedi_dio_config=%d;\n", return_value_comedi_dio_config);fflush(stdout);
		status = (status | return_value_comedi_dio_config);
	printf("_tr_node_id:Node_12_434;_tr_assign:status=%d;\n", status);fflush(stdout);
	printf("_tr_node_id:Node_12_435;_tr_decl:return_value_comedi_dio_config_0;\n");fflush(stdout);
	signed int return_value_comedi_dio_config_0;
	printf("_tr_call:comedi_dio_config;_tr_call_id:62;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:comedi_dio_config__it_g=it_g;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:port=%d;\n", 3);fflush(stdout);
	printf("_tr_param;_tr_assign:i=%d;\n", i);fflush(stdout);
	printf("_tr_param;_tr_assign:mode=%d;\n", 1);fflush(stdout);
		return_value_comedi_dio_config_0 = comedi_dio_config(it_g, 3, i, 1);
	printf("_tr_node_id:Node_12_437;_tr_assign:return_value_comedi_dio_config_0=%d;\n", return_value_comedi_dio_config_0);fflush(stdout);
		status = (status | return_value_comedi_dio_config_0);
	printf("_tr_node_id:Node_12_439;_tr_assign:status=%d;\n", status);fflush(stdout);
	printf("_tr_node_id:Node_12_440;_tr_decl:return_value_comedi_dio_config_1;\n");fflush(stdout);
	signed int return_value_comedi_dio_config_1;
	printf("_tr_call:comedi_dio_config;_tr_call_id:63;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:comedi_dio_config__it_g=it_g;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:port=%d;\n", 3);fflush(stdout);
	printf("_tr_param;_tr_assign:i=%d;\n", (i + 8));fflush(stdout);
	printf("_tr_param;_tr_assign:mode=%d;\n", 1);fflush(stdout);
		return_value_comedi_dio_config_1 = comedi_dio_config(it_g, 3, (i + 8), 1);
	printf("_tr_node_id:Node_12_442;_tr_assign:return_value_comedi_dio_config_1=%d;\n", return_value_comedi_dio_config_1);fflush(stdout);
		status = (status | return_value_comedi_dio_config_1);
	printf("_tr_node_id:Node_12_444;_tr_assign:status=%d;\n", status);fflush(stdout);
	printf("_tr_node_id:Node_12_445;_tr_decl:return_value_comedi_dio_config_2;\n");fflush(stdout);
	signed int return_value_comedi_dio_config_2;
	printf("_tr_call:comedi_dio_config;_tr_call_id:64;\n");fflush(stdout);
	printf("_tr_param;_tr_dynamic_assign:comedi_dio_config__it_g=it_g;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:port=%d;\n", 3);fflush(stdout);
	printf("_tr_param;_tr_assign:i=%d;\n", (i + 16));fflush(stdout);
	printf("_tr_param;_tr_assign:mode=%d;\n", 0);fflush(stdout);
		return_value_comedi_dio_config_2 = comedi_dio_config(it_g, 3, (i + 16), 0);
	printf("_tr_node_id:Node_12_447;_tr_assign:return_value_comedi_dio_config_2=%d;\n", return_value_comedi_dio_config_2);fflush(stdout);
		status = (status | return_value_comedi_dio_config_2);
	printf("_tr_node_id:Node_12_449;_tr_assign:status=%d;\n", status);fflush(stdout);
		i = (i + 1);
	printf("_tr_node_id:Node_12_458;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_12_429;
	Node_12_460:;
	__iv__return_expr_io_init = 	(signed int)((status == 0));
	printf("_tr_node_id:Node_12_461;_tr_assign:__iv__return_expr_io_init=%d;\n", __iv__return_expr_io_init);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_io_init;
}
signed int getTimerStatus() {
	printf("_tr_node_id:Node_13_470;_tr_decl:deltaTime;\n");fflush(stdout);
	long double deltaTime;
	printf("_tr_node_id:Node_13_471;_tr_decl:return_value_clock;\n");fflush(stdout);
	clock_t return_value_clock;
	printf("_tr_call:clock;_tr_call_id:65;\n");fflush(stdout);
		return_value_clock = clock();
	printf("_tr_node_id:Node_13_473;_tr_assign:return_value_clock=%ld;\n", return_value_clock);fflush(stdout);
		deltaTime = ((long double)((return_value_clock - timerStarted)) / 1.0l);
	printf("_tr_node_id:Node_13_475;_tr_assign:deltaTime=%Lf;\n", deltaTime);fflush(stdout);
	__iv__branch_expr = !(((deltaTime >= (long double)(duration)) && !((timerActive == 0))));
	printf("_tr_node_id:Node_13_476;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((deltaTime >= (long double)(duration)) && !((timerActive == 0))))) goto Node_13_483;
	__iv__return_expr_getTimerStatus = 	1;
	printf("_tr_node_id:Node_13_477;_tr_assign:__iv__return_expr_getTimerStatus=%d;\n", __iv__return_expr_getTimerStatus);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_getTimerStatus;
	Node_13_483:;
	__iv__return_expr_getTimerStatus = 	0;
	printf("_tr_node_id:Node_13_483;_tr_assign:__iv__return_expr_getTimerStatus=%d;\n", __iv__return_expr_getTimerStatus);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_getTimerStatus;
}
void flushOrders() {
	printf("_tr_node_id:Node_14_494;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_14_495;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_14_497:;
	__iv__branch_expr = (button >= 3);
	printf("_tr_node_id:Node_14_497;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 3)) goto Node_14_510;
	printf("_tr_node_id:Node_14_498;_tr_decl:floorNum;\n");fflush(stdout);
	signed int floorNum;
		floorNum = 0;
	printf("_tr_node_id:Node_14_499;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	Node_14_501:;
	__iv__branch_expr = (floorNum >= 4);
	printf("_tr_node_id:Node_14_501;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorNum >= 4)) goto Node_14_506;
	unsigned int __iv__index_expr_var2 = (unsigned) ((signed long int)(button));
	unsigned int __iv__index_expr_var3 = (unsigned) ((signed long int)(floorNum));
		orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] = 0;
	printf("_tr_node_id:Node_14_502;_tr_assign:orderMatrix[%u][%u]=%d;\n", __iv__index_expr_var2, __iv__index_expr_var3, orderMatrix[__iv__index_expr_var2][__iv__index_expr_var3]);fflush(stdout);
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:66;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(button));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", floorNum);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 0);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(button), floorNum, 0);
		floorNum = (floorNum + 1);
	printf("_tr_node_id:Node_14_504;_tr_assign:floorNum=%d;\n", floorNum);fflush(stdout);
	goto Node_14_501;
	Node_14_506:;
		button = (button + 1);
	printf("_tr_node_id:Node_14_508;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_14_497;
	Node_14_510:;
	printf("_tr_return;\n");fflush(stdout);
}
signed int floorIsOrdered(signed int floorNum, signed int motorDir) {
	printf("_tr_node_id:Node_15_513;_tr_decl:floorBeyond;\n");fflush(stdout);
	signed int floorBeyond;
	__iv__branch_expr = !((orderMatrix[2][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_15_514;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[2][(signed long int)(floorNum)] == 1))) goto Node_15_519;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_515;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_519:;
	__iv__branch_expr = !((motorDir == 0));
	printf("_tr_node_id:Node_15_519;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((motorDir == 0))) goto Node_15_533;
	printf("_tr_node_id:Node_15_520;_tr_decl:tmp_if_expr;\n");fflush(stdout);
	__CPROVER_bool tmp_if_expr;
	__iv__branch_expr = !((orderMatrix[0][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_15_521;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[0][(signed long int)(floorNum)] == 1))) goto Node_15_524;
		tmp_if_expr = (1 != 0);
	printf("_tr_node_id:Node_15_522;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	goto Node_15_525;
	Node_15_524:;
		tmp_if_expr = ((orderMatrix[1][(signed long int)(floorNum)] == 1) ? 1 : 0 != 0);
	printf("_tr_node_id:Node_15_524;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	Node_15_525:;
	__iv__branch_expr = !tmp_if_expr;
	printf("_tr_node_id:Node_15_526;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!tmp_if_expr) goto Node_15_531;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_527;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_531:;
	Node_15_533:;
	__iv__branch_expr = !((motorDir == 1));
	printf("_tr_node_id:Node_15_534;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((motorDir == 1))) goto Node_15_571;
		floorBeyond = 0;
	printf("_tr_node_id:Node_15_535;_tr_assign:floorBeyond=%d;\n", floorBeyond);fflush(stdout);
	printf("_tr_node_id:Node_15_536;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_15_537;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_15_539:;
	__iv__branch_expr = (button >= 2);
	printf("_tr_node_id:Node_15_539;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 2)) goto Node_15_551;
	printf("_tr_node_id:Node_15_540;_tr_decl:i;\n");fflush(stdout);
	signed int i;
		i = (floorNum + 1);
	printf("_tr_node_id:Node_15_541;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_15_543:;
	__iv__branch_expr = (i >= 4);
	printf("_tr_node_id:Node_15_543;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 4)) goto Node_15_547;
		floorBeyond = (floorBeyond + orderMatrix[(signed long int)(button)][(signed long int)(i)]);
	printf("_tr_node_id:Node_15_544;_tr_assign:floorBeyond=%d;\n", floorBeyond);fflush(stdout);
		i = (i + 1);
	printf("_tr_node_id:Node_15_545;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_15_543;
	Node_15_547:;
		button = (button + 1);
	printf("_tr_node_id:Node_15_549;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_15_539;
	Node_15_551:;
	__iv__branch_expr = !((orderMatrix[0][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_15_552;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[0][(signed long int)(floorNum)] == 1))) goto Node_15_557;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_553;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_557:;
	__iv__branch_expr = !((orderMatrix[1][(signed long int)(floorNum)] == 0));
	printf("_tr_node_id:Node_15_558;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[1][(signed long int)(floorNum)] == 0))) goto Node_15_561;
	goto Node_15_571;
	Node_15_561:;
	__iv__branch_expr = (floorBeyond == 0);
	printf("_tr_node_id:Node_15_562;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorBeyond == 0)) goto Node_15_565;
	goto Node_15_571;
	Node_15_565:;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_566;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_571:;
	__iv__branch_expr = !((motorDir == -1));
	printf("_tr_node_id:Node_15_572;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((motorDir == -1))) goto Node_15_609;
		floorBeyond = 0;
	printf("_tr_node_id:Node_15_573;_tr_assign:floorBeyond=%d;\n", floorBeyond);fflush(stdout);
	printf("_tr_node_id:Node_15_574;_tr_decl:floorIsOrdered__1__4__1__button;\n");fflush(stdout);
	signed int floorIsOrdered__1__4__1__button;
		floorIsOrdered__1__4__1__button = 0;
	printf("_tr_node_id:Node_15_575;_tr_assign:floorIsOrdered__1__4__1__button=%d;\n", floorIsOrdered__1__4__1__button);fflush(stdout);
	Node_15_577:;
	__iv__branch_expr = (floorIsOrdered__1__4__1__button >= 2);
	printf("_tr_node_id:Node_15_577;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorIsOrdered__1__4__1__button >= 2)) goto Node_15_589;
	printf("_tr_node_id:Node_15_578;_tr_decl:floorIsOrdered__1__4__1__1__1__i;\n");fflush(stdout);
	signed int floorIsOrdered__1__4__1__1__1__i;
		floorIsOrdered__1__4__1__1__1__i = 0;
	printf("_tr_node_id:Node_15_579;_tr_assign:floorIsOrdered__1__4__1__1__1__i=%d;\n", floorIsOrdered__1__4__1__1__1__i);fflush(stdout);
	Node_15_581:;
	__iv__branch_expr = (floorIsOrdered__1__4__1__1__1__i >= floorNum);
	printf("_tr_node_id:Node_15_581;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorIsOrdered__1__4__1__1__1__i >= floorNum)) goto Node_15_585;
		floorBeyond = (floorBeyond + orderMatrix[(signed long int)(floorIsOrdered__1__4__1__button)][(signed long int)(floorIsOrdered__1__4__1__1__1__i)]);
	printf("_tr_node_id:Node_15_582;_tr_assign:floorBeyond=%d;\n", floorBeyond);fflush(stdout);
		floorIsOrdered__1__4__1__1__1__i = (floorIsOrdered__1__4__1__1__1__i + 1);
	printf("_tr_node_id:Node_15_583;_tr_assign:floorIsOrdered__1__4__1__1__1__i=%d;\n", floorIsOrdered__1__4__1__1__1__i);fflush(stdout);
	goto Node_15_581;
	Node_15_585:;
		floorIsOrdered__1__4__1__button = (floorIsOrdered__1__4__1__button + 1);
	printf("_tr_node_id:Node_15_587;_tr_assign:floorIsOrdered__1__4__1__button=%d;\n", floorIsOrdered__1__4__1__button);fflush(stdout);
	goto Node_15_577;
	Node_15_589:;
	__iv__branch_expr = !((orderMatrix[1][(signed long int)(floorNum)] == 1));
	printf("_tr_node_id:Node_15_590;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[1][(signed long int)(floorNum)] == 1))) goto Node_15_595;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_591;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_595:;
	__iv__branch_expr = !((orderMatrix[0][(signed long int)(floorNum)] == 0));
	printf("_tr_node_id:Node_15_596;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[0][(signed long int)(floorNum)] == 0))) goto Node_15_599;
	goto Node_15_609;
	Node_15_599:;
	__iv__branch_expr = (floorBeyond == 0);
	printf("_tr_node_id:Node_15_600;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((floorBeyond == 0)) goto Node_15_603;
	goto Node_15_609;
	Node_15_603:;
	__iv__return_expr_floorIsOrdered = 	1;
	printf("_tr_node_id:Node_15_604;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
	Node_15_609:;
	__iv__return_expr_floorIsOrdered = 	0;
	printf("_tr_node_id:Node_15_610;_tr_assign:__iv__return_expr_floorIsOrdered=%d;\n", __iv__return_expr_floorIsOrdered);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
}
signed int isTimerActive() {
	__iv__return_expr_isTimerActive = 	timerActive;
	printf("_tr_node_id:Node_16_619;_tr_assign:__iv__return_expr_isTimerActive=%d;\n", __iv__return_expr_isTimerActive);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_isTimerActive;
}
signed int elev_get_button_signal(elev_button_type_t button, signed int floor) {
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:67;\n");fflush(stdout);
	__CPROVER_assume((floor >= 0));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:68;\n");fflush(stdout);
	__CPROVER_assume((floor < 4));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:69;\n");fflush(stdout);
	__CPROVER_assume(((((signed int)(button) == 0) || ((signed int)(button) == 1)) || ((signed int)(button) == 2)));
	printf("_tr_node_id:Node_17_626;_tr_decl:return_value_io_read_bit;\n");fflush(stdout);
	signed int return_value_io_read_bit;
	printf("_tr_call:io_read_bit;_tr_call_id:70;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:channel=%d;\n", button_channel_matrix[(signed long int)(floor)][(signed long int)(button)]);fflush(stdout);
		return_value_io_read_bit = io_read_bit(button_channel_matrix[(signed long int)(floor)][(signed long int)(button)]);
	printf("_tr_node_id:Node_17_627;_tr_assign:return_value_io_read_bit=%d;\n", return_value_io_read_bit);fflush(stdout);
	__iv__branch_expr = (return_value_io_read_bit == 0);
	printf("_tr_node_id:Node_17_629;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_io_read_bit == 0)) goto Node_17_635;
	__iv__return_expr_elev_get_button_signal = 	1;
	printf("_tr_node_id:Node_17_630;_tr_assign:__iv__return_expr_elev_get_button_signal=%d;\n", __iv__return_expr_elev_get_button_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_button_signal;
	Node_17_635:;
	__iv__return_expr_elev_get_button_signal = 	0;
	printf("_tr_node_id:Node_17_635;_tr_assign:__iv__return_expr_elev_get_button_signal=%d;\n", __iv__return_expr_elev_get_button_signal);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_button_signal;
}
comedi_t* comedi_open(char* src) {
	printf("_tr_node_id:Node_18_644;_tr_decl:pointer;\n");fflush(stdout);
	comedi_t *pointer;
	printf("_tr_node_id:Node_18_645;_tr_decl:pointed;\n");fflush(stdout);
	comedi_t pointed;
		pointer = &pointed;
	printf("_tr_node_id:Node_18_646;_tr_dynamic_assign:	pointer = &pointed;\n");fflush(stdout);
	__iv__return_expr_comedi_open = 	pointer;
	printf("_tr_node_id:Node_18_647;_tr_assign:__iv__return_expr_comedi_open=%p;\n", __iv__return_expr_comedi_open);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_comedi_open;
}
void comedi_dio_read(comedi_t* comedi_dio_read__it_g, signed int port, signed int i, signed int* data) {
	printf("_tr_node_id:Node_19_652;_tr_decl:read;\n");fflush(stdout);
	signed int read;
	printf("_tr_node_id:Node_19_653;_tr_decl:return_value___VERIFIER_nondet_signed_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_signed_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:71;\n");fflush(stdout);
		return_value___VERIFIER_nondet_signed_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_19_656;_tr_assign:return_value___VERIFIER_nondet_signed_int=%d;\n", return_value___VERIFIER_nondet_signed_int);fflush(stdout);
		read = return_value___VERIFIER_nondet_signed_int;
	printf("_tr_node_id:Node_19_657;_tr_assign:read=%d;\n", read);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:72;\n");fflush(stdout);
	__CPROVER_assume(((0 <= read) && (read <= 1)));
		*data = read;
	printf("_tr_node_id:Node_19_659;_tr_dynamic_assign:	*data = read;\n");fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
clock_t clock() {
	__iv__return_expr_clock = 	elev_clock;
	printf("_tr_node_id:Node_20_664;_tr_assign:__iv__return_expr_clock=%ld;\n", __iv__return_expr_clock);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_clock;
}
void update_prop_automata() {
	__iv__branch_expr = !((state == 0));
	printf("_tr_node_id:Node_21_667;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((state == 0))) goto Node_21_673;
		timer = 0l;
	printf("_tr_node_id:Node_21_668;_tr_assign:timer=%ld;\n", timer);fflush(stdout);
	__iv__branch_expr = !(((currentFloorLocation == myFloor) && ((signed int)(previousState) == 3)));
	printf("_tr_node_id:Node_21_669;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((currentFloorLocation == myFloor) && ((signed int)(previousState) == 3)))) goto Node_21_671;
		state = 1;
	printf("_tr_node_id:Node_21_670;_tr_assign:state=%d;\n", state);fflush(stdout);
	Node_21_671:;
	goto Node_21_691;
	Node_21_673:;
	__iv__branch_expr = !((state == 1));
	printf("_tr_node_id:Node_21_673;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((state == 1))) goto Node_21_678;
	__iv__branch_expr = !((orderMatrix[2][(signed long int)(dstFloor)] == 1));
	printf("_tr_node_id:Node_21_674;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[2][(signed long int)(dstFloor)] == 1))) goto Node_21_676;
		state = 2;
	printf("_tr_node_id:Node_21_675;_tr_assign:state=%d;\n", state);fflush(stdout);
	Node_21_676:;
	goto Node_21_690;
	Node_21_678:;
	__iv__branch_expr = !((state == 2));
	printf("_tr_node_id:Node_21_678;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((state == 2))) goto Node_21_689;
		timer = (timer + 1l);
	printf("_tr_node_id:Node_21_679;_tr_assign:timer=%ld;\n", timer);fflush(stdout);
	__iv__branch_expr = !((orderMatrix[2][(signed long int)(dstFloor)] == 0) ? TRUE : ((currentFloorLocation == dstFloor) && ((signed int)(previousState) == 3)) ? TRUE : FALSE);
	printf("_tr_node_id:Node_21_680;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((orderMatrix[2][(signed long int)(dstFloor)] == 0) ? TRUE : ((currentFloorLocation == dstFloor) && ((signed int)(previousState) == 3)) ? TRUE : FALSE)) goto Node_21_685;
		state = 0;
	printf("_tr_node_id:Node_21_683;_tr_assign:state=%d;\n", state);fflush(stdout);
	goto Node_21_688;
	Node_21_685:;
	__iv__branch_expr = !((timer >= 600l));
	printf("_tr_node_id:Node_21_685;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((timer >= 600l))) goto Node_21_687;
		state = 3;
	printf("_tr_node_id:Node_21_686;_tr_assign:state=%d;\n", state);fflush(stdout);
	Node_21_687:;
	Node_21_688:;
	Node_21_689:;
	Node_21_690:;
	Node_21_691:;
	printf("_tr_return;\n");fflush(stdout);
}
void timerDeactivate() {
		timerActive = 0;
	printf("_tr_node_id:Node_22_693;_tr_assign:timerActive=%d;\n", timerActive);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
void startTimer(double length) {
	printf("_tr_call:clock;_tr_call_id:73;\n");fflush(stdout);
		timerStarted = clock();
	printf("_tr_node_id:Node_23_695;_tr_assign:timerStarted=%ld;\n", timerStarted);fflush(stdout);
		duration = length;
	printf("_tr_node_id:Node_23_696;_tr_assign:duration=%lf;\n", duration);fflush(stdout);
		timerActive = 1;
	printf("_tr_node_id:Node_23_697;_tr_assign:timerActive=%d;\n", timerActive);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
signed int io_read_analog(signed int channel) {
	printf("_tr_return;\n");fflush(stdout);
}
void io_write_analog(signed int channel, signed int value) {
	printf("_tr_return;\n");fflush(stdout);
}
void comedi_data_read(comedi_t* comedi_data_read__it_g, signed int port, signed int channel, signed int i, signed int j, signed int* data) {
	printf("_tr_return;\n");fflush(stdout);
}
void check_property() {
	(void)sizeof(signed int)  ;
	if(!((state != 3))) { printf("violated property: Node_27_707\n"); fflush(stdout); exit(0); }
	printf("_tr_return;\n");fflush(stdout);
}
void io_set_bit(signed int channel) {
	printf("_tr_return;\n");fflush(stdout);
}
void io_clear_bit(signed int channel) {
	printf("_tr_return;\n");fflush(stdout);
}
void comedi_data_write(comedi_t* comedi_data_write__it_g, signed int port, signed int channel, signed int i, signed int j, signed int mode) {
	printf("_tr_return;\n");fflush(stdout);
}
void removeFromOrderMatrix(signed int floorNum) {
	printf("_tr_node_id:Node_32_720;_tr_decl:button;\n");fflush(stdout);
	signed int button;
		button = 0;
	printf("_tr_node_id:Node_32_721;_tr_assign:button=%d;\n", button);fflush(stdout);
	Node_32_723:;
	__iv__branch_expr = (button >= 3);
	printf("_tr_node_id:Node_32_723;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((button >= 3)) goto Node_32_728;
	unsigned int __iv__index_expr_var4 = (unsigned) ((signed long int)(button));
	unsigned int __iv__index_expr_var5 = (unsigned) ((signed long int)(floorNum));
		orderMatrix[(signed long int)(button)][(signed long int)(floorNum)] = 0;
	printf("_tr_node_id:Node_32_724;_tr_assign:orderMatrix[%u][%u]=%d;\n", __iv__index_expr_var4, __iv__index_expr_var5, orderMatrix[__iv__index_expr_var4][__iv__index_expr_var5]);fflush(stdout);
	printf("_tr_call:elev_set_button_lamp;_tr_call_id:76;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:button=%d;\n", (elev_button_type_t)(button));fflush(stdout);
	printf("_tr_param;_tr_assign:floor=%d;\n", floorNum);fflush(stdout);
	printf("_tr_param;_tr_assign:value=%d;\n", 0);fflush(stdout);
	elev_set_button_lamp((elev_button_type_t)(button), floorNum, 0);
		button = (button + 1);
	printf("_tr_node_id:Node_32_726;_tr_assign:button=%d;\n", button);fflush(stdout);
	goto Node_32_723;
	Node_32_728:;
	printf("_tr_return;\n");fflush(stdout);
}
void comedi_dio_write(comedi_t* comedi_dio_write__it_g, signed int port, signed int i, signed int mode) {
	printf("_tr_return;\n");fflush(stdout);
}
signed int elev_get_obstruction_signal() {
	printf("_tr_call:io_read_bit;_tr_call_id:77;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:channel=%d;\n", (0x300 + 23));fflush(stdout);
	io_read_bit((0x300 + 23));
	printf("_tr_return;\n");fflush(stdout);
}
void elev_set_button_lamp(elev_button_type_t button, signed int floor, signed int value) {
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:79;\n");fflush(stdout);
	__CPROVER_assume((floor >= 0));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:80;\n");fflush(stdout);
	__CPROVER_assume((floor < 4));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:81;\n");fflush(stdout);
	__CPROVER_assume(((((signed int)(button) == 0) || ((signed int)(button) == 1)) || ((signed int)(button) == 2)));
	printf("_tr_return;\n");fflush(stdout);
}
void elev_set_door_open_lamp(signed int value) {
	printf("_tr_return;\n");fflush(stdout);
}
void elev_set_floor_indicator(signed int floor) {
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:82;\n");fflush(stdout);
	__CPROVER_assume((floor >= 0));
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:83;\n");fflush(stdout);
	__CPROVER_assume((floor < 4));
	printf("_tr_return;\n");fflush(stdout);
}
void elev_set_motor_direction(elev_motor_direction_t dirn) {
	__iv__branch_expr = !(((signed int)(dirn) == 0));
	printf("_tr_node_id:Node_39_784;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((signed int)(dirn) == 0))) goto Node_39_787;
		elev_motor = 0;
	printf("_tr_node_id:Node_39_785;_tr_assign:elev_motor=%d;\n", elev_motor);fflush(stdout);
	goto Node_39_796;
	Node_39_787:;
	__iv__branch_expr = !(((signed int)(dirn) >= 1));
	printf("_tr_node_id:Node_39_787;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((signed int)(dirn) >= 1))) goto Node_39_791;
		elev_motor = 1;
	printf("_tr_node_id:Node_39_788;_tr_assign:elev_motor=%d;\n", elev_motor);fflush(stdout);
	printf("_tr_call:startTimer;_tr_call_id:84;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:length=%lf;\n", 3.0);fflush(stdout);
	startTimer(3.0);
	goto Node_39_795;
	Node_39_791:;
	__iv__branch_expr = ((signed int)(dirn) >= 0);
	printf("_tr_node_id:Node_39_791;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(dirn) >= 0)) goto Node_39_794;
		elev_motor = -1;
	printf("_tr_node_id:Node_39_792;_tr_assign:elev_motor=%d;\n", elev_motor);fflush(stdout);
	printf("_tr_call:startTimer;_tr_call_id:85;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:length=%lf;\n", 3.0);fflush(stdout);
	startTimer(3.0);
	Node_39_794:;
	Node_39_795:;
	Node_39_796:;
	printf("_tr_return;\n");fflush(stdout);
}
void elev_set_stop_lamp(signed int value) {
	printf("_tr_return;\n");fflush(stdout);
}
signed int __iv__floorIsOrdered_stub(signed int floorNum, signed int motorDir){
	signed int __iv__return_expr_floorIsOrdered;
	if(motorDir>=2) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[1][2]<(-1)) __iv__return_expr_floorIsOrdered = 0; else if((-1)==orderMatrix[1][2]) __iv__return_expr_floorIsOrdered = orderMatrix[0][0]; else if((-1)>=orderMatrix[2][1]) __iv__return_expr_floorIsOrdered = 0; else if((-1)>=orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(3==orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = 0; else if((-1)>=orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[0][3]>=2) __iv__return_expr_floorIsOrdered = 0; else if((-1)>=orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = 0; else if(floorNum<orderMatrix[1][2]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][3]<orderMatrix[1][3]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(floorNum<orderMatrix[1][3]) __iv__return_expr_floorIsOrdered = orderMatrix[1][3]; else if(floorNum<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[0][1]; else if(floorNum<orderMatrix[0][3]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(floorNum<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(floorNum<orderMatrix[2][1]) __iv__return_expr_floorIsOrdered = 0; else if(floorNum<orderMatrix[2][3]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(floorNum<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[0][0]; else if(floorNum<orderMatrix[2][0]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(floorNum<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(floorNum<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if((-1)==motorDir) __iv__return_expr_floorIsOrdered = orderMatrix[2][1]; else if(orderMatrix[0][3]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[0][3]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[0][0]; else if(orderMatrix[2][3]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[0][3]<orderMatrix[2][0]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][3]<orderMatrix[2][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][1]; else if(orderMatrix[0][3]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[1][1]==floorNum) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(motorDir<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[2][0]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][0]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[0][2]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[2][3]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][3]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[2][2]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][0]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[0][0]; else if(motorDir<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[1][3]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[1][3]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[1][2]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[1][1]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][0]; else if(orderMatrix[0][1]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[0][0]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[0][0]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][1]<orderMatrix[1][0]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][1]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[0][1]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[1][2]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[2][2]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[0][2]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[0][2]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][2]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[2][1]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[1][3]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[1][1]<orderMatrix[0][0]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[1][0]<orderMatrix[1][1]) __iv__return_expr_floorIsOrdered = orderMatrix[1][1]; else if(orderMatrix[1][3]==floorNum) __iv__return_expr_floorIsOrdered = orderMatrix[1][3]; else if(orderMatrix[2][1]==floorNum) __iv__return_expr_floorIsOrdered = orderMatrix[2][1]; else if(orderMatrix[2][0]<orderMatrix[0][3]) __iv__return_expr_floorIsOrdered = orderMatrix[0][3]; else if(orderMatrix[0][1]==floorNum) __iv__return_expr_floorIsOrdered = orderMatrix[0][1]; else if(orderMatrix[2][3]<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[0][2]==floorNum) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[2][3]<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][3]==floorNum) __iv__return_expr_floorIsOrdered = 0; else if(motorDir<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[0][2]; else if(orderMatrix[2][2]<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[0][2]; else if(orderMatrix[1][2]<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[0][2]; else if(orderMatrix[0][1]<orderMatrix[0][2]) __iv__return_expr_floorIsOrdered = orderMatrix[0][2]; else if(orderMatrix[0][3]<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = 0; else if(motorDir<orderMatrix[1][3]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][2]<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][1]<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[0][3]<orderMatrix[1][3]) __iv__return_expr_floorIsOrdered = 0; else if(orderMatrix[2][1]<orderMatrix[2][3]) __iv__return_expr_floorIsOrdered = orderMatrix[2][3]; else if(orderMatrix[1][3]<orderMatrix[0][1]) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(floorNum>=3) __iv__return_expr_floorIsOrdered = orderMatrix[2][0]; else if(orderMatrix[2][2]<orderMatrix[2][1]) __iv__return_expr_floorIsOrdered = 0; else __iv__return_expr_floorIsOrdered = orderMatrix[2][1]; 
	__CPROVER_assume(__iv__return_expr_floorIsOrdered == 0 || __iv__return_expr_floorIsOrdered == 1);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_floorIsOrdered;
}
signed int __iv__elev_get_button_signal_stub(elev_button_type_t button, signed int floor){
	signed int __iv__return_expr_elev_get_button_signal;
	signed int __iv__nondet_input_elev_get_button_signal_1 = __VERIFIER_nondet_signed_int();
	__iv__return_expr_elev_get_button_signal = __iv__nondet_input_elev_get_button_signal_1;
	__CPROVER_assume(__iv__return_expr_elev_get_button_signal == 0 || __iv__return_expr_elev_get_button_signal == 1);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_elev_get_button_signal;
}
signed int __iv__isButtonPressed_stub(){
	signed int __iv__return_expr_isButtonPressed;
	if(orderMatrix[2][1]>=2) __iv__return_expr_isButtonPressed = 0; else if((-1)>=orderMatrix[2][1]) __iv__return_expr_isButtonPressed = 0; else if(orderMatrix[1][1]>=2) __iv__return_expr_isButtonPressed = orderMatrix[2][0]; else __iv__return_expr_isButtonPressed = 1; 
	__CPROVER_assume(__iv__return_expr_isButtonPressed == 0 || __iv__return_expr_isButtonPressed == 1);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_isButtonPressed;
}
