#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#define __CPROVER_assume(a) if (!(a)) exit(0)
typedef _Bool __CPROVER_bool;
FILE *__iv__fp;
#include <assert.h>
#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
enum FSM { STANDBY=0, SCAN_PRIMARY=1, SCAN_SECONDARY=2, DRIVE_PATROL=3, DRIVE_TO_BEACON_FAST=4, DRIVE_TO_BEACON_SLOW=5, DRIVE_TO_WALL=6, TARGET_ACQUIRING=7, TARGET_DISPOSING=8, SIGNAL_COMPLETION=9 };
typedef enum FSM State;
signed int SensorValue(signed int sensor);
State acquireTarget();
void backUp();
void check_property();
void clearTimer(signed int t1);
State closeRangeApproach();
State disposeOfTarget();
State findAWall();
void initialize();
State longRangeApproach();
signed int medianFilter();
State onPatrol();
State primaryScan();
State secondaryScan();
State standingBy();
void stopWheels();
State taskComplete();
signed int time1(signed int t1);
void turnAround();
void update_prop_automata();
void wait1Msec(signed int sec);
signed int IRMax=0;
signed int ambientIR=5000;
signed int brobot_max_loss;
signed int __VERIFIER_nondet_signed_int(){ signed int __iv_temp; if (-1 == fscanf(__iv__fp, "%d", &__iv_temp)) exit(0); return __iv_temp; }
signed int brobot_signal_loss;
signed int cycle=0;
State machineState=/*enum*/STANDBY;
float motor[4l];
signed int sonarMax=0;
signed int state=0;
__CPROVER_bool __iv__branch_expr;
int __iv__return_expr_main;
signed int __iv__return_expr_time1;
State __iv__return_expr_standingBy;
State __iv__return_expr_secondaryScan;
State __iv__return_expr_primaryScan;
State __iv__return_expr_onPatrol;
State __iv__return_expr_longRangeApproach;
State __iv__return_expr_closeRangeApproach;
signed int __iv__return_expr_SensorValue;
State __iv__return_expr_findAWall;
State __iv__return_expr_disposeOfTarget;
State __iv__return_expr_acquireTarget;
signed int __iv__return_expr_medianFilter;
State __iv__return_expr_taskComplete;
signed int __iv__medianFilter_stub();
int medianFilter_stub_index;
signed int medianFilter___iv__return_expr_medianFilter_list[] = {601, 4224, 32768};
int main(int argc, char* argv[]) {
	__iv__fp = fopen(argv[1], "r");
	printf("_tr_call:initialize;_tr_call_id:0;\n");fflush(stdout);
	initialize();
	Node_0_1:;
	__iv__branch_expr = !((1 != 0));
	printf("_tr_node_id:Node_0_1;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((1 != 0))) goto Node_0_39;
	__iv__branch_expr = ((signed int)(machineState) == 0);
	printf("_tr_node_id:Node_0_3;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 0)) goto Node_0_14;
	__iv__branch_expr = ((signed int)(machineState) == 1);
	printf("_tr_node_id:Node_0_4;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 1)) goto Node_0_16;
	__iv__branch_expr = ((signed int)(machineState) == 2);
	printf("_tr_node_id:Node_0_5;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 2)) goto Node_0_18;
	__iv__branch_expr = ((signed int)(machineState) == 3);
	printf("_tr_node_id:Node_0_6;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 3)) goto Node_0_20;
	__iv__branch_expr = ((signed int)(machineState) == 4);
	printf("_tr_node_id:Node_0_7;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 4)) goto Node_0_22;
	__iv__branch_expr = ((signed int)(machineState) == 5);
	printf("_tr_node_id:Node_0_8;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 5)) goto Node_0_24;
	__iv__branch_expr = ((signed int)(machineState) == 7);
	printf("_tr_node_id:Node_0_9;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 7)) goto Node_0_26;
	__iv__branch_expr = ((signed int)(machineState) == 6);
	printf("_tr_node_id:Node_0_10;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 6)) goto Node_0_28;
	__iv__branch_expr = ((signed int)(machineState) == 8);
	printf("_tr_node_id:Node_0_11;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 8)) goto Node_0_30;
	__iv__branch_expr = ((signed int)(machineState) == 9);
	printf("_tr_node_id:Node_0_12;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((signed int)(machineState) == 9)) goto Node_0_32;
	goto Node_0_34;
	Node_0_14:;
	printf("_tr_call:standingBy;_tr_call_id:1;\n");fflush(stdout);
		machineState = standingBy();
	printf("_tr_node_id:Node_0_14;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_16:;
	printf("_tr_call:primaryScan;_tr_call_id:2;\n");fflush(stdout);
		machineState = primaryScan();
	printf("_tr_node_id:Node_0_16;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_18:;
	printf("_tr_call:secondaryScan;_tr_call_id:3;\n");fflush(stdout);
		machineState = secondaryScan();
	printf("_tr_node_id:Node_0_18;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_20:;
	printf("_tr_call:onPatrol;_tr_call_id:4;\n");fflush(stdout);
		machineState = onPatrol();
	printf("_tr_node_id:Node_0_20;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_22:;
	printf("_tr_call:longRangeApproach;_tr_call_id:5;\n");fflush(stdout);
		machineState = longRangeApproach();
	printf("_tr_node_id:Node_0_22;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_24:;
	printf("_tr_call:closeRangeApproach;_tr_call_id:6;\n");fflush(stdout);
		machineState = closeRangeApproach();
	printf("_tr_node_id:Node_0_24;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_26:;
	printf("_tr_call:acquireTarget;_tr_call_id:7;\n");fflush(stdout);
		machineState = acquireTarget();
	printf("_tr_node_id:Node_0_26;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_28:;
	printf("_tr_call:findAWall;_tr_call_id:8;\n");fflush(stdout);
		machineState = findAWall();
	printf("_tr_node_id:Node_0_28;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_30:;
	printf("_tr_call:disposeOfTarget;_tr_call_id:9;\n");fflush(stdout);
		machineState = disposeOfTarget();
	printf("_tr_node_id:Node_0_30;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_32:;
	printf("_tr_call:taskComplete;_tr_call_id:10;\n");fflush(stdout);
		machineState = taskComplete();
	printf("_tr_node_id:Node_0_32;_tr_assign:machineState=%d;\n", machineState);fflush(stdout);
	goto Node_0_35;
	Node_0_34:;
	Node_0_35:;
	printf("_tr_call:update_prop_automata;_tr_call_id:11;\n");fflush(stdout);
	update_prop_automata();
	printf("_tr_call:check_property;_tr_call_id:12;\n");fflush(stdout);
	check_property();
	goto Node_0_1;
	Node_0_39:;
	printf("_tr_return;\n");fflush(stdout);
}
signed int time1(signed int t1) {
	printf("_tr_node_id:Node_2_47;_tr_decl:res;\n");fflush(stdout);
	signed int res;
	printf("_tr_node_id:Node_2_48;_tr_decl:return_value___VERIFIER_nondet_unsigned_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:14;\n");fflush(stdout);
		return_value___VERIFIER_nondet_unsigned_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_2_51;_tr_assign:return_value___VERIFIER_nondet_unsigned_int=%d;\n", return_value___VERIFIER_nondet_unsigned_int);fflush(stdout);
		res = return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_node_id:Node_2_52;_tr_assign:res=%d;\n", res);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:15;\n");fflush(stdout);
	__CPROVER_assume(((0 <= res) && (res <= 65535)));
	__iv__return_expr_time1 = 	res;
	printf("_tr_node_id:Node_2_54;_tr_assign:__iv__return_expr_time1=%d;\n", __iv__return_expr_time1);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_time1;
}
State standingBy() {
	printf("_tr_call:stopWheels;_tr_call_id:16;\n");fflush(stdout);
	stopWheels();
	printf("_tr_node_id:Node_3_61;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:17;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 3);fflush(stdout);
		return_value_SensorValue = SensorValue(3);
	printf("_tr_node_id:Node_3_63;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue == 0);
	printf("_tr_node_id:Node_3_65;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue == 0)) goto Node_3_71;
	__iv__return_expr_standingBy = 	(State)(1);
	printf("_tr_node_id:Node_3_66;_tr_assign:__iv__return_expr_standingBy=%d;\n", __iv__return_expr_standingBy);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_standingBy;
	Node_3_71:;
	__iv__return_expr_standingBy = 	(State)(0);
	printf("_tr_node_id:Node_3_71;_tr_assign:__iv__return_expr_standingBy=%d;\n", __iv__return_expr_standingBy);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_standingBy;
}
State secondaryScan() {
		IRMax = 0;
	printf("_tr_node_id:Node_4_80;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:18;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_4_82;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_4_83:;
	printf("_tr_call:time1;_tr_call_id:19;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_4_83;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 3000);
	printf("_tr_node_id:Node_4_84;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 3000)) goto Node_4_99;
	printf("_tr_node_id:Node_4_87;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:20;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_4_89;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (IRMax >= return_value_SensorValue);
	printf("_tr_node_id:Node_4_91;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((IRMax >= return_value_SensorValue)) goto Node_4_93;
	printf("_tr_call:SensorValue;_tr_call_id:21;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_4_92;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_4_93:;
	unsigned int __iv__index_expr_var0 = (unsigned) (0);
		motor[0] = (float)((25.0 * 1.3));
	printf("_tr_node_id:Node_4_94;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var0, motor[__iv__index_expr_var0]);fflush(stdout);
	unsigned int __iv__index_expr_var1 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_4_95;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var1, motor[__iv__index_expr_var1]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_4_98;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_4_83;
	Node_4_99:;
	printf("_tr_call:stopWheels;_tr_call_id:22;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:23;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	printf("_tr_call:clearTimer;_tr_call_id:24;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_4_103;_tr_decl:return_value_time1_0;\n");fflush(stdout);
	signed int return_value_time1_0;
	Node_4_104:;
	printf("_tr_call:time1;_tr_call_id:25;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_0 = time1(0);
	printf("_tr_node_id:Node_4_104;_tr_assign:return_value_time1_0=%d;\n", return_value_time1_0);fflush(stdout);
	__iv__branch_expr = (return_value_time1_0 >= 6000);
	printf("_tr_node_id:Node_4_105;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_0 >= 6000)) goto Node_4_120;
	printf("_tr_node_id:Node_4_108;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:26;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(2);
	printf("_tr_node_id:Node_4_110;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = !((return_value_SensorValue_0 >= IRMax));
	printf("_tr_node_id:Node_4_112;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_SensorValue_0 >= IRMax))) goto Node_4_114;
	printf("_tr_call:SensorValue;_tr_call_id:27;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_4_113;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_4_114:;
	unsigned int __iv__index_expr_var2 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_4_115;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var2, motor[__iv__index_expr_var2]);fflush(stdout);
	unsigned int __iv__index_expr_var3 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_4_116;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var3, motor[__iv__index_expr_var3]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_4_119;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_4_104;
	Node_4_120:;
	printf("_tr_call:stopWheels;_tr_call_id:28;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:29;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	printf("_tr_call:clearTimer;_tr_call_id:30;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_4_124;_tr_decl:return_value_time1_1;\n");fflush(stdout);
	signed int return_value_time1_1;
	Node_4_125:;
	printf("_tr_call:time1;_tr_call_id:31;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_1 = time1(0);
	printf("_tr_node_id:Node_4_125;_tr_assign:return_value_time1_1=%d;\n", return_value_time1_1);fflush(stdout);
	__iv__branch_expr = (return_value_time1_1 >= 6000);
	printf("_tr_node_id:Node_4_126;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_1 >= 6000)) goto Node_4_150;
	printf("_tr_node_id:Node_4_129;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	printf("_tr_call:SensorValue;_tr_call_id:32;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(2);
	printf("_tr_node_id:Node_4_131;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
	__iv__branch_expr = ((IRMax + -20) >= return_value_SensorValue_1);
	printf("_tr_node_id:Node_4_133;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((IRMax + -20) >= return_value_SensorValue_1)) goto Node_4_142;
	printf("_tr_call:stopWheels;_tr_call_id:33;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_secondaryScan = 	(State)(5);
	printf("_tr_node_id:Node_4_135;_tr_assign:__iv__return_expr_secondaryScan=%d;\n", __iv__return_expr_secondaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_secondaryScan;
	Node_4_142:;
	unsigned int __iv__index_expr_var4 = (unsigned) (0);
		motor[0] = (float)((25.0 * 1.3));
	printf("_tr_node_id:Node_4_143;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var4, motor[__iv__index_expr_var4]);fflush(stdout);
	unsigned int __iv__index_expr_var5 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_4_144;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var5, motor[__iv__index_expr_var5]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_4_145;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:34;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_4_149;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_4_125;
	Node_4_150:;
	printf("_tr_call:stopWheels;_tr_call_id:35;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_secondaryScan = 	(State)(3);
	printf("_tr_node_id:Node_4_152;_tr_assign:__iv__return_expr_secondaryScan=%d;\n", __iv__return_expr_secondaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_secondaryScan;
}
State primaryScan() {
		IRMax = 0;
	printf("_tr_node_id:Node_5_158;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
		sonarMax = 0;
	printf("_tr_node_id:Node_5_159;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:36;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_5_161;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_5_162:;
	printf("_tr_call:time1;_tr_call_id:37;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_5_162;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 4000);
	printf("_tr_node_id:Node_5_163;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 4000)) goto Node_5_187;
	printf("_tr_node_id:Node_5_166;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:38;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_5_168;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (IRMax >= return_value_SensorValue);
	printf("_tr_node_id:Node_5_170;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((IRMax >= return_value_SensorValue)) goto Node_5_172;
	printf("_tr_call:SensorValue;_tr_call_id:39;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		IRMax = SensorValue(2);
	printf("_tr_node_id:Node_5_171;_tr_assign:IRMax=%d;\n", IRMax);fflush(stdout);
	Node_5_172:;
	printf("_tr_node_id:Node_5_173;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:40;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(2);
	printf("_tr_node_id:Node_5_175;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue_0 >= ambientIR);
	printf("_tr_node_id:Node_5_177;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 >= ambientIR)) goto Node_5_179;
	printf("_tr_call:SensorValue;_tr_call_id:41;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		ambientIR = SensorValue(2);
	printf("_tr_node_id:Node_5_178;_tr_assign:ambientIR=%d;\n", ambientIR);fflush(stdout);
	Node_5_179:;
	unsigned int __iv__index_expr_var6 = (unsigned) (0);
		motor[0] = (float)(-((30.0 * 1.3)));
	printf("_tr_node_id:Node_5_180;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var6, motor[__iv__index_expr_var6]);fflush(stdout);
	unsigned int __iv__index_expr_var7 = (unsigned) (1);
		motor[1] = 30.0f;
	printf("_tr_node_id:Node_5_181;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var7, motor[__iv__index_expr_var7]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_5_186;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_5_162;
	Node_5_187:;
	printf("_tr_call:clearTimer;_tr_call_id:42;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_5_189;_tr_decl:return_value_time1_0;\n");fflush(stdout);
	signed int return_value_time1_0;
	Node_5_190:;
	printf("_tr_call:time1;_tr_call_id:43;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1_0 = time1(0);
	printf("_tr_node_id:Node_5_190;_tr_assign:return_value_time1_0=%d;\n", return_value_time1_0);fflush(stdout);
	__iv__branch_expr = (return_value_time1_0 >= 4000);
	printf("_tr_node_id:Node_5_191;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1_0 >= 4000)) goto Node_5_214;
	printf("_tr_node_id:Node_5_194;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	printf("_tr_call:SensorValue;_tr_call_id:44;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(2);
	printf("_tr_node_id:Node_5_196;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 50) >= return_value_SensorValue_1);
	printf("_tr_node_id:Node_5_198;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 50) >= return_value_SensorValue_1)) goto Node_5_206;
	printf("_tr_call:stopWheels;_tr_call_id:45;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_primaryScan = 	(State)(4);
	printf("_tr_node_id:Node_5_200;_tr_assign:__iv__return_expr_primaryScan=%d;\n", __iv__return_expr_primaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_primaryScan;
	Node_5_206:;
	unsigned int __iv__index_expr_var8 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_5_207;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var8, motor[__iv__index_expr_var8]);fflush(stdout);
	unsigned int __iv__index_expr_var9 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_5_208;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var9, motor[__iv__index_expr_var9]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_5_209;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:46;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_5_213;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_5_190;
	Node_5_214:;
	printf("_tr_call:stopWheels;_tr_call_id:47;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_primaryScan = 	(State)(3);
	printf("_tr_node_id:Node_5_216;_tr_assign:__iv__return_expr_primaryScan=%d;\n", __iv__return_expr_primaryScan);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_primaryScan;
}
State onPatrol() {
		sonarMax = 0;
	printf("_tr_node_id:Node_6_221;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	printf("_tr_call:clearTimer;_tr_call_id:48;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_6_223;_tr_decl:return_value_time1;\n");fflush(stdout);
	signed int return_value_time1;
	Node_6_224:;
	printf("_tr_call:time1;_tr_call_id:49;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
		return_value_time1 = time1(0);
	printf("_tr_node_id:Node_6_224;_tr_assign:return_value_time1=%d;\n", return_value_time1);fflush(stdout);
	__iv__branch_expr = (return_value_time1 >= 6000);
	printf("_tr_node_id:Node_6_225;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_time1 >= 6000)) goto Node_6_240;
	printf("_tr_node_id:Node_6_228;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:50;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		return_value_SensorValue = SensorValue(1);
	printf("_tr_node_id:Node_6_230;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = !((return_value_SensorValue >= sonarMax));
	printf("_tr_node_id:Node_6_232;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_SensorValue >= sonarMax))) goto Node_6_234;
	printf("_tr_call:SensorValue;_tr_call_id:51;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		sonarMax = SensorValue(1);
	printf("_tr_node_id:Node_6_233;_tr_assign:sonarMax=%d;\n", sonarMax);fflush(stdout);
	Node_6_234:;
	unsigned int __iv__index_expr_var10 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_6_235;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var10, motor[__iv__index_expr_var10]);fflush(stdout);
	unsigned int __iv__index_expr_var11 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_6_236;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var11, motor[__iv__index_expr_var11]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_6_239;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_6_224;
	Node_6_240:;
	printf("_tr_call:clearTimer;_tr_call_id:52;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:t1=%d;\n", 0);fflush(stdout);
	clearTimer(0);
	printf("_tr_node_id:Node_6_242;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	Node_6_243:;
	printf("_tr_call:SensorValue;_tr_call_id:53;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(1);
	printf("_tr_node_id:Node_6_243;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = !(((sonarMax + -100) >= return_value_SensorValue_0));
	printf("_tr_node_id:Node_6_244;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((sonarMax + -100) >= return_value_SensorValue_0))) goto Node_6_250;
	unsigned int __iv__index_expr_var12 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_6_247;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var12, motor[__iv__index_expr_var12]);fflush(stdout);
	unsigned int __iv__index_expr_var13 = (unsigned) (1);
		motor[1] = 25.0f;
	printf("_tr_node_id:Node_6_248;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var13, motor[__iv__index_expr_var13]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_6_249;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_6_243;
	Node_6_250:;
	printf("_tr_call:stopWheels;_tr_call_id:54;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var14 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_6_252;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var14, motor[__iv__index_expr_var14]);fflush(stdout);
	unsigned int __iv__index_expr_var15 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_6_253;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var15, motor[__iv__index_expr_var15]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:55;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 2500);fflush(stdout);
	wait1Msec(2500);
	printf("_tr_call:stopWheels;_tr_call_id:56;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_onPatrol = 	(State)(1);
	printf("_tr_node_id:Node_6_256;_tr_assign:__iv__return_expr_onPatrol=%d;\n", __iv__return_expr_onPatrol);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_onPatrol;
}
State longRangeApproach() {
	printf("_tr_node_id:Node_7_261;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:57;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_7_263;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	printf("_tr_node_id:Node_7_265;_tr_decl:return_value_medianFilter_0;\n");fflush(stdout);
	signed int return_value_medianFilter_0;
	printf("_tr_node_id:Node_7_266;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_node_id:Node_7_267;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	__iv__branch_expr = (return_value_medianFilter >= 601);
	printf("_tr_node_id:Node_7_268;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_medianFilter >= 601)) goto Node_7_277;
	__iv__return_expr_longRangeApproach = 	(State)(5);
	printf("_tr_node_id:Node_7_269;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
	Node_7_277:;
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_7_277;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:58;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	Node_7_279:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:59;\n");fflush(stdout);
		return_value_medianFilter_0 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_7_279;_tr_assign:return_value_medianFilter_0=%d;\n", return_value_medianFilter_0);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_0 >= 601));
	printf("_tr_node_id:Node_7_280;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_0 >= 601))) goto Node_7_320;
	printf("_tr_call:SensorValue;_tr_call_id:60;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_7_283;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 50) >= return_value_SensorValue);
	printf("_tr_node_id:Node_7_284;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 50) >= return_value_SensorValue)) goto Node_7_320;
	unsigned int __iv__index_expr_var16 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_7_287;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var16, motor[__iv__index_expr_var16]);fflush(stdout);
	unsigned int __iv__index_expr_var17 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_7_288;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var17, motor[__iv__index_expr_var17]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_7_289;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:61;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	printf("_tr_node_id:Node_7_291;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:62;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(4);
	printf("_tr_node_id:Node_7_294;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	printf("_tr_node_id:Node_7_295;_tr_decl:tmp_if_expr;\n");fflush(stdout);
	__CPROVER_bool tmp_if_expr;
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_7_296;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_7_299;
		tmp_if_expr = (1 != 0);
	printf("_tr_node_id:Node_7_297;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	goto Node_7_301;
	Node_7_299:;
	printf("_tr_call:SensorValue;_tr_call_id:63;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(5);
	printf("_tr_node_id:Node_7_299;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
		tmp_if_expr = ((return_value_SensorValue_1 != 0) ? 1 : 0 != 0);
	printf("_tr_node_id:Node_7_300;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	Node_7_301:;
	__iv__branch_expr = !tmp_if_expr;
	printf("_tr_node_id:Node_7_302;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!tmp_if_expr) goto Node_7_315;
	printf("_tr_call:backUp;_tr_call_id:64;\n");fflush(stdout);
	backUp();
	printf("_tr_call:stopWheels;_tr_call_id:65;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_longRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_7_305;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
	Node_7_315:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_7_319;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_7_279;
	Node_7_320:;
	__iv__return_expr_longRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_7_321;_tr_assign:__iv__return_expr_longRangeApproach=%d;\n", __iv__return_expr_longRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_longRangeApproach;
}
State closeRangeApproach() {
	printf("_tr_node_id:Node_9_365;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_node_id:Node_9_366;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_node_id:Node_9_367;_tr_decl:return_value_SensorValue_1;\n");fflush(stdout);
	signed int return_value_SensorValue_1;
	Node_9_368:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:66;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_9_368;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter >= 141));
	printf("_tr_node_id:Node_9_369;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter >= 141))) goto Node_9_407;
	printf("_tr_call:SensorValue;_tr_call_id:67;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 2);fflush(stdout);
		return_value_SensorValue = SensorValue(2);
	printf("_tr_node_id:Node_9_372;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = ((ambientIR + 20) >= return_value_SensorValue);
	printf("_tr_node_id:Node_9_373;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (((ambientIR + 20) >= return_value_SensorValue)) goto Node_9_407;
	unsigned int __iv__index_expr_var18 = (unsigned) (0);
		motor[0] = (float)((20.0 * 1.3));
	printf("_tr_node_id:Node_9_376;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var18, motor[__iv__index_expr_var18]);fflush(stdout);
	unsigned int __iv__index_expr_var19 = (unsigned) (1);
		motor[1] = 20.0f;
	printf("_tr_node_id:Node_9_377;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var19, motor[__iv__index_expr_var19]);fflush(stdout);
		brobot_signal_loss = (brobot_signal_loss + 1);
	printf("_tr_node_id:Node_9_378;_tr_assign:brobot_signal_loss=%d;\n", brobot_signal_loss);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:68;\n");fflush(stdout);
	__CPROVER_assume((brobot_signal_loss <= brobot_max_loss));
	printf("_tr_node_id:Node_9_380;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:69;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(4);
	printf("_tr_node_id:Node_9_383;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	printf("_tr_node_id:Node_9_384;_tr_decl:tmp_if_expr;\n");fflush(stdout);
	__CPROVER_bool tmp_if_expr;
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_9_385;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_9_388;
		tmp_if_expr = (1 != 0);
	printf("_tr_node_id:Node_9_386;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	goto Node_9_390;
	Node_9_388:;
	printf("_tr_call:SensorValue;_tr_call_id:70;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_1 = SensorValue(5);
	printf("_tr_node_id:Node_9_388;_tr_assign:return_value_SensorValue_1=%d;\n", return_value_SensorValue_1);fflush(stdout);
		tmp_if_expr = ((return_value_SensorValue_1 != 0) ? 1 : 0 != 0);
	printf("_tr_node_id:Node_9_389;_tr_assign:tmp_if_expr=%hhu;\n", tmp_if_expr);fflush(stdout);
	Node_9_390:;
	__iv__branch_expr = !tmp_if_expr;
	printf("_tr_node_id:Node_9_391;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!tmp_if_expr) goto Node_9_402;
	printf("_tr_call:backUp;_tr_call_id:71;\n");fflush(stdout);
	backUp();
	printf("_tr_call:stopWheels;_tr_call_id:72;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_closeRangeApproach = 	(State)(2);
	printf("_tr_node_id:Node_9_394;_tr_assign:__iv__return_expr_closeRangeApproach=%d;\n", __iv__return_expr_closeRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_closeRangeApproach;
	Node_9_402:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_9_406;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_9_368;
	Node_9_407:;
	__iv__return_expr_closeRangeApproach = 	(State)(7);
	printf("_tr_node_id:Node_9_408;_tr_assign:__iv__return_expr_closeRangeApproach=%d;\n", __iv__return_expr_closeRangeApproach);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_closeRangeApproach;
}
signed int SensorValue(signed int sensor) {
	printf("_tr_node_id:Node_10_414;_tr_decl:res;\n");fflush(stdout);
	signed int res;
	printf("_tr_node_id:Node_10_415;_tr_decl:return_value___VERIFIER_nondet_unsigned_int;\n");fflush(stdout);
	signed int return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_system_call:__VERIFIER_nondet_signed_int;_tr_call_id:73;\n");fflush(stdout);
		return_value___VERIFIER_nondet_unsigned_int = __VERIFIER_nondet_signed_int();
	printf("_tr_node_id:Node_10_418;_tr_assign:return_value___VERIFIER_nondet_unsigned_int=%d;\n", return_value___VERIFIER_nondet_unsigned_int);fflush(stdout);
		res = return_value___VERIFIER_nondet_unsigned_int;
	printf("_tr_node_id:Node_10_419;_tr_assign:res=%d;\n", res);fflush(stdout);
	printf("_tr_system_call:__CPROVER_assume;_tr_call_id:74;\n");fflush(stdout);
	__CPROVER_assume(((0 <= res) && (res <= 65535)));
	__iv__return_expr_SensorValue = 	res;
	printf("_tr_node_id:Node_10_421;_tr_assign:__iv__return_expr_SensorValue=%d;\n", __iv__return_expr_SensorValue);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_SensorValue;
}
State findAWall() {
	printf("_tr_call:backUp;_tr_call_id:75;\n");fflush(stdout);
	backUp();
	printf("_tr_call:turnAround;_tr_call_id:76;\n");fflush(stdout);
	turnAround();
	printf("_tr_node_id:Node_11_429;_tr_decl:return_value_medianFilter;\n");fflush(stdout);
	signed int return_value_medianFilter;
	printf("_tr_node_id:Node_11_430;_tr_decl:return_value_medianFilter_0;\n");fflush(stdout);
	signed int return_value_medianFilter_0;
	printf("_tr_node_id:Node_11_431;_tr_decl:return_value_medianFilter_1;\n");fflush(stdout);
	signed int return_value_medianFilter_1;
	Node_11_432:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:77;\n");fflush(stdout);
		return_value_medianFilter = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_11_432;_tr_assign:return_value_medianFilter=%d;\n", return_value_medianFilter);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter >= 141));
	printf("_tr_node_id:Node_11_433;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter >= 141))) goto Node_11_479;
	unsigned int __iv__index_expr_var20 = (unsigned) (0);
		motor[0] = (float)((40.0 * 1.3));
	printf("_tr_node_id:Node_11_436;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var20, motor[__iv__index_expr_var20]);fflush(stdout);
	unsigned int __iv__index_expr_var21 = (unsigned) (1);
		motor[1] = 40.0f;
	printf("_tr_node_id:Node_11_437;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var21, motor[__iv__index_expr_var21]);fflush(stdout);
	printf("_tr_node_id:Node_11_438;_tr_decl:return_value_SensorValue;\n");fflush(stdout);
	signed int return_value_SensorValue;
	printf("_tr_call:SensorValue;_tr_call_id:78;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 4);fflush(stdout);
		return_value_SensorValue = SensorValue(4);
	printf("_tr_node_id:Node_11_440;_tr_assign:return_value_SensorValue=%d;\n", return_value_SensorValue);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue == 0);
	printf("_tr_node_id:Node_11_442;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue == 0)) goto Node_11_455;
	unsigned int __iv__index_expr_var22 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_11_443;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var22, motor[__iv__index_expr_var22]);fflush(stdout);
	unsigned int __iv__index_expr_var23 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_11_444;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var23, motor[__iv__index_expr_var23]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:79;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	Node_11_446:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:80;\n");fflush(stdout);
		return_value_medianFilter_0 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_11_446;_tr_assign:return_value_medianFilter_0=%d;\n", return_value_medianFilter_0);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_0 >= 141));
	printf("_tr_node_id:Node_11_447;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_0 >= 141))) goto Node_11_453;
	unsigned int __iv__index_expr_var24 = (unsigned) (0);
		motor[0] = (float)(-((20.0 * 1.3)));
	printf("_tr_node_id:Node_11_450;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var24, motor[__iv__index_expr_var24]);fflush(stdout);
	unsigned int __iv__index_expr_var25 = (unsigned) (1);
		motor[1] = 20.0f;
	printf("_tr_node_id:Node_11_451;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var25, motor[__iv__index_expr_var25]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_11_452;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_11_446;
	Node_11_453:;
	goto Node_11_479;
	Node_11_455:;
	printf("_tr_node_id:Node_11_456;_tr_decl:return_value_SensorValue_0;\n");fflush(stdout);
	signed int return_value_SensorValue_0;
	printf("_tr_call:SensorValue;_tr_call_id:81;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 5);fflush(stdout);
		return_value_SensorValue_0 = SensorValue(5);
	printf("_tr_node_id:Node_11_458;_tr_assign:return_value_SensorValue_0=%d;\n", return_value_SensorValue_0);fflush(stdout);
	__iv__branch_expr = (return_value_SensorValue_0 == 0);
	printf("_tr_node_id:Node_11_460;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((return_value_SensorValue_0 == 0)) goto Node_11_473;
	unsigned int __iv__index_expr_var26 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_11_461;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var26, motor[__iv__index_expr_var26]);fflush(stdout);
	unsigned int __iv__index_expr_var27 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_11_462;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var27, motor[__iv__index_expr_var27]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:82;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	Node_11_464:;
	printf("_tr_call:__iv__medianFilter_stub;_tr_call_id:83;\n");fflush(stdout);
		return_value_medianFilter_1 = __iv__medianFilter_stub();
	printf("_tr_node_id:Node_11_464;_tr_assign:return_value_medianFilter_1=%d;\n", return_value_medianFilter_1);fflush(stdout);
	__iv__branch_expr = !((return_value_medianFilter_1 >= 141));
	printf("_tr_node_id:Node_11_465;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((return_value_medianFilter_1 >= 141))) goto Node_11_471;
	unsigned int __iv__index_expr_var28 = (unsigned) (0);
		motor[0] = (float)((20.0 * 1.3));
	printf("_tr_node_id:Node_11_468;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var28, motor[__iv__index_expr_var28]);fflush(stdout);
	unsigned int __iv__index_expr_var29 = (unsigned) (1);
		motor[1] = (float)(-20);
	printf("_tr_node_id:Node_11_469;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var29, motor[__iv__index_expr_var29]);fflush(stdout);
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_11_470;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_11_464;
	Node_11_471:;
	goto Node_11_479;
	Node_11_473:;
	__iv__branch_expr = (1 != 0);
	printf("_tr_node_id:Node_11_478;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((1 != 0)) goto Node_11_432;
	Node_11_479:;
	printf("_tr_call:stopWheels;_tr_call_id:84;\n");fflush(stdout);
	stopWheels();
	__iv__return_expr_findAWall = 	(State)(8);
	printf("_tr_node_id:Node_11_481;_tr_assign:__iv__return_expr_findAWall=%d;\n", __iv__return_expr_findAWall);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_findAWall;
}
State disposeOfTarget() {
	unsigned int __iv__index_expr_var30 = (unsigned) (2);
		motor[2] = (float)(-10);
	printf("_tr_node_id:Node_12_487;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var30, motor[__iv__index_expr_var30]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:85;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 800);fflush(stdout);
	wait1Msec(800);
	unsigned int __iv__index_expr_var31 = (unsigned) (3);
		motor[3] = 20.0f;
	printf("_tr_node_id:Node_12_489;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var31, motor[__iv__index_expr_var31]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:86;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1200);fflush(stdout);
	wait1Msec(1200);
	printf("_tr_node_id:Node_12_491;_tr_decl:tmp_assign;\n");fflush(stdout);
	float tmp_assign;
		tmp_assign = 0.0f;
	printf("_tr_node_id:Node_12_492;_tr_assign:tmp_assign=%f;\n", tmp_assign);fflush(stdout);
	unsigned int __iv__index_expr_var32 = (unsigned) (2);
		motor[2] = tmp_assign;
	printf("_tr_node_id:Node_12_493;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var32, motor[__iv__index_expr_var32]);fflush(stdout);
	unsigned int __iv__index_expr_var33 = (unsigned) (3);
		motor[3] = tmp_assign;
	printf("_tr_node_id:Node_12_494;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var33, motor[__iv__index_expr_var33]);fflush(stdout);
	__iv__return_expr_disposeOfTarget = 	(State)(9);
	printf("_tr_node_id:Node_12_495;_tr_assign:__iv__return_expr_disposeOfTarget=%d;\n", __iv__return_expr_disposeOfTarget);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_disposeOfTarget;
}
void clearTimer(signed int t1) {
	printf("_tr_return;\n");fflush(stdout);
}
void check_property() {
	(void)sizeof(signed int)  ;
	(void)sizeof(signed int)  ;
	if(!((state != 2))) { printf("violated property: Node_14_503\n"); fflush(stdout); exit(0); }
	printf("_tr_return;\n");fflush(stdout);
}
State acquireTarget() {
	printf("_tr_call:stopWheels;_tr_call_id:88;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var34 = (unsigned) (2);
		motor[2] = (float)(-20);
	printf("_tr_node_id:Node_15_506;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var34, motor[__iv__index_expr_var34]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:89;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1500);fflush(stdout);
	wait1Msec(1500);
	unsigned int __iv__index_expr_var35 = (unsigned) (2);
		motor[2] = 0.0f;
	printf("_tr_node_id:Node_15_508;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var35, motor[__iv__index_expr_var35]);fflush(stdout);
	unsigned int __iv__index_expr_var36 = (unsigned) (3);
		motor[3] = (float)(-10);
	printf("_tr_node_id:Node_15_509;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var36, motor[__iv__index_expr_var36]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:90;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	unsigned int __iv__index_expr_var37 = (unsigned) (3);
		motor[3] = (float)(-30);
	printf("_tr_node_id:Node_15_511;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var37, motor[__iv__index_expr_var37]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:91;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 500);fflush(stdout);
	wait1Msec(500);
	unsigned int __iv__index_expr_var38 = (unsigned) (3);
		motor[3] = (float)(-10);
	printf("_tr_node_id:Node_15_513;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var38, motor[__iv__index_expr_var38]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:92;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 200);fflush(stdout);
	wait1Msec(200);
	unsigned int __iv__index_expr_var39 = (unsigned) (2);
		motor[2] = 30.0f;
	printf("_tr_node_id:Node_15_515;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var39, motor[__iv__index_expr_var39]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:93;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 900);fflush(stdout);
	wait1Msec(900);
	unsigned int __iv__index_expr_var40 = (unsigned) (2);
		motor[2] = 10.0f;
	printf("_tr_node_id:Node_15_517;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var40, motor[__iv__index_expr_var40]);fflush(stdout);
	__iv__return_expr_acquireTarget = 	(State)(6);
	printf("_tr_node_id:Node_15_518;_tr_assign:__iv__return_expr_acquireTarget=%d;\n", __iv__return_expr_acquireTarget);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_acquireTarget;
}
signed int medianFilter() {
	printf("_tr_node_id:Node_16_521;_tr_decl:first;\n");fflush(stdout);
	signed int first;
		first = 0;
	printf("_tr_node_id:Node_16_522;_tr_assign:first=%d;\n", first);fflush(stdout);
	printf("_tr_node_id:Node_16_523;_tr_decl:second;\n");fflush(stdout);
	signed int second;
		second = 0;
	printf("_tr_node_id:Node_16_524;_tr_assign:second=%d;\n", second);fflush(stdout);
	printf("_tr_node_id:Node_16_525;_tr_decl:third;\n");fflush(stdout);
	signed int third;
		third = 0;
	printf("_tr_node_id:Node_16_526;_tr_assign:third=%d;\n", third);fflush(stdout);
	printf("_tr_call:SensorValue;_tr_call_id:94;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		first = SensorValue(1);
	printf("_tr_node_id:Node_16_527;_tr_assign:first=%d;\n", first);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:95;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	printf("_tr_call:SensorValue;_tr_call_id:96;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		second = SensorValue(1);
	printf("_tr_node_id:Node_16_529;_tr_assign:second=%d;\n", second);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:97;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	printf("_tr_call:SensorValue;_tr_call_id:98;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sensor=%d;\n", 1);fflush(stdout);
		third = SensorValue(1);
	printf("_tr_node_id:Node_16_531;_tr_assign:third=%d;\n", third);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:99;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 70);fflush(stdout);
	wait1Msec(70);
	__iv__branch_expr = !((((first >= second) && (third >= first)) || ((second >= first) && (first >= third))));
	printf("_tr_node_id:Node_16_533;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((((first >= second) && (third >= first)) || ((second >= first) && (first >= third))))) goto Node_16_540;
	__iv__return_expr_medianFilter = 	first;
	printf("_tr_node_id:Node_16_534;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
	Node_16_540:;
	__iv__branch_expr = !((((second >= first) && (third >= second)) || ((first >= second) && (second >= third))));
	printf("_tr_node_id:Node_16_540;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((((second >= first) && (third >= second)) || ((first >= second) && (second >= third))))) goto Node_16_547;
	__iv__return_expr_medianFilter = 	second;
	printf("_tr_node_id:Node_16_541;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
	Node_16_547:;
	__iv__return_expr_medianFilter = 	third;
	printf("_tr_node_id:Node_16_547;_tr_assign:__iv__return_expr_medianFilter=%d;\n", __iv__return_expr_medianFilter);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
}
void backUp() {
	printf("_tr_call:stopWheels;_tr_call_id:100;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:wait1Msec;_tr_call_id:101;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 400);fflush(stdout);
	wait1Msec(400);
	unsigned int __iv__index_expr_var41 = (unsigned) (0);
		motor[0] = (float)(-((25.0 * 1.3)));
	printf("_tr_node_id:Node_17_561;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var41, motor[__iv__index_expr_var41]);fflush(stdout);
	unsigned int __iv__index_expr_var42 = (unsigned) (1);
		motor[1] = (float)(-25);
	printf("_tr_node_id:Node_17_562;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var42, motor[__iv__index_expr_var42]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:102;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1500);fflush(stdout);
	wait1Msec(1500);
	printf("_tr_call:stopWheels;_tr_call_id:103;\n");fflush(stdout);
	stopWheels();
	printf("_tr_return;\n");fflush(stdout);
}
void initialize() {
		brobot_max_loss = 5;
	printf("_tr_node_id:Node_18_566;_tr_assign:brobot_max_loss=%d;\n", brobot_max_loss);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
void stopWheels() {
	printf("_tr_node_id:Node_19_568;_tr_decl:tmp_assign;\n");fflush(stdout);
	float tmp_assign;
		tmp_assign = 0.0f;
	printf("_tr_node_id:Node_19_569;_tr_assign:tmp_assign=%f;\n", tmp_assign);fflush(stdout);
	unsigned int __iv__index_expr_var43 = (unsigned) (1);
		motor[1] = tmp_assign;
	printf("_tr_node_id:Node_19_570;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var43, motor[__iv__index_expr_var43]);fflush(stdout);
	unsigned int __iv__index_expr_var44 = (unsigned) (0);
		motor[0] = tmp_assign;
	printf("_tr_node_id:Node_19_571;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var44, motor[__iv__index_expr_var44]);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
}
State taskComplete() {
	printf("_tr_call:stopWheels;_tr_call_id:104;\n");fflush(stdout);
	stopWheels();
	printf("_tr_call:backUp;_tr_call_id:105;\n");fflush(stdout);
	backUp();
	printf("_tr_node_id:Node_20_576;_tr_decl:i;\n");fflush(stdout);
	signed int i;
		i = 0;
	printf("_tr_node_id:Node_20_577;_tr_assign:i=%d;\n", i);fflush(stdout);
	Node_20_579:;
	__iv__branch_expr = (i >= 3);
	printf("_tr_node_id:Node_20_579;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if ((i >= 3)) goto Node_20_587;
	unsigned int __iv__index_expr_var45 = (unsigned) (2);
		motor[2] = 30.0f;
	printf("_tr_node_id:Node_20_580;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var45, motor[__iv__index_expr_var45]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:106;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 2000);fflush(stdout);
	wait1Msec(2000);
	unsigned int __iv__index_expr_var46 = (unsigned) (2);
		motor[2] = (float)(-30);
	printf("_tr_node_id:Node_20_582;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var46, motor[__iv__index_expr_var46]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:107;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	printf("_tr_call:turnAround;_tr_call_id:108;\n");fflush(stdout);
	turnAround();
		i = (i + 1);
	printf("_tr_node_id:Node_20_585;_tr_assign:i=%d;\n", i);fflush(stdout);
	goto Node_20_579;
	Node_20_587:;
	__iv__return_expr_taskComplete = 	(State)(0);
	printf("_tr_node_id:Node_20_588;_tr_assign:__iv__return_expr_taskComplete=%d;\n", __iv__return_expr_taskComplete);fflush(stdout);
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_taskComplete;
}
void turnAround() {
	printf("_tr_call:stopWheels;_tr_call_id:109;\n");fflush(stdout);
	stopWheels();
	unsigned int __iv__index_expr_var47 = (unsigned) (0);
		motor[0] = (float)(-((30.0 * 1.3)));
	printf("_tr_node_id:Node_21_593;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var47, motor[__iv__index_expr_var47]);fflush(stdout);
	unsigned int __iv__index_expr_var48 = (unsigned) (1);
		motor[1] = 30.0f;
	printf("_tr_node_id:Node_21_594;_tr_assign:motor[%u]=%f;\n", __iv__index_expr_var48, motor[__iv__index_expr_var48]);fflush(stdout);
	printf("_tr_call:wait1Msec;_tr_call_id:110;\n");fflush(stdout);
	printf("_tr_param;_tr_assign:sec=%d;\n", 1000);fflush(stdout);
	wait1Msec(1000);
	printf("_tr_call:stopWheels;_tr_call_id:111;\n");fflush(stdout);
	stopWheels();
	printf("_tr_return;\n");fflush(stdout);
}
void wait1Msec(signed int sec) {
	printf("_tr_return;\n");fflush(stdout);
}
void update_prop_automata() {
	__iv__branch_expr = !((state == 0));
	printf("_tr_node_id:Node_23_600;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((state == 0))) goto Node_23_606;
		cycle = 0;
	printf("_tr_node_id:Node_23_601;_tr_assign:cycle=%d;\n", cycle);fflush(stdout);
	__iv__branch_expr = !((((signed int)(machineState) == 4) || ((signed int)(machineState) == 5)));
	printf("_tr_node_id:Node_23_602;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((((signed int)(machineState) == 4) || ((signed int)(machineState) == 5)))) goto Node_23_604;
		state = 1;
	printf("_tr_node_id:Node_23_603;_tr_assign:state=%d;\n", state);fflush(stdout);
	Node_23_604:;
	goto Node_23_616;
	Node_23_606:;
	__iv__branch_expr = !((state == 1));
	printf("_tr_node_id:Node_23_606;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((state == 1))) goto Node_23_615;
		cycle = (cycle + 1);
	printf("_tr_node_id:Node_23_607;_tr_assign:cycle=%d;\n", cycle);fflush(stdout);
	__iv__branch_expr = !(((signed int)(machineState) == 9));
	printf("_tr_node_id:Node_23_608;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!(((signed int)(machineState) == 9))) goto Node_23_611;
		state = 0;
	printf("_tr_node_id:Node_23_609;_tr_assign:state=%d;\n", state);fflush(stdout);
	goto Node_23_614;
	Node_23_611:;
	__iv__branch_expr = !((cycle >= 20));
	printf("_tr_node_id:Node_23_611;_tr_assign:__iv__branch_expr=%d;\n", __iv__branch_expr);fflush(stdout);
	if (!((cycle >= 20))) goto Node_23_613;
		state = 2;
	printf("_tr_node_id:Node_23_612;_tr_assign:state=%d;\n", state);fflush(stdout);
	Node_23_613:;
	Node_23_614:;
	Node_23_615:;
	Node_23_616:;
	printf("_tr_return;\n");fflush(stdout);
}
signed int __iv__medianFilter_stub(){
	__iv__return_expr_medianFilter = medianFilter___iv__return_expr_medianFilter_list[medianFilter_stub_index];
	medianFilter_stub_index++;
	printf("_tr_return;\n");fflush(stdout);
	return __iv__return_expr_medianFilter;
}
